"use client";
import {createPortal} from "react-dom";
import {useRef,useState,useEffect} from "react";
import Image from "next/image";
import {Check,Plus,X} from "lucide-react";
import {money,type Product} from "@/lib/demo-data";
import {emptyFoodOptions,priceFoodSelection,type FoodSelection} from "@/lib/food-options";
import {useCart,cartLimit} from "./cart-provider";
import styles from "./food-configurator.module.css";
export function FoodConfigurator({product,variantId,lineId,label="Выбрать"}:{product:Product;variantId:string;lineId?:string;label?:string}){
 const [mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);const {add,edit,items}=useCart();const options=product.foodOptions??emptyFoodOptions;
 const dialog=useRef<HTMLDialogElement>(null);const [selection,setSelection]=useState<FoodSelection>({removed:[],choices:{}}),[error,setError]=useState("");
 const existing=items.find(i=>i.lineId===lineId);let extra=0;let validation="";try{extra=priceFoodSelection(options,selection).extra;}catch(cause){validation=cause instanceof Error?cause.message:"Выберите состав";}
 function open(){setError("");setSelection(existing?.selection??{removed:[],choices:Object.fromEntries(options.groups.map(g=>[g.id,g.options.slice(0,g.min).map(o=>o.id)]))});dialog.current?.showModal();}
 function toggle(groupId:string,optionId:string,max:number){const current=selection.choices[groupId]??[];const next=current.includes(optionId)?current.filter(id=>id!==optionId):max===1?[optionId]:current.length<max?[...current,optionId]:current;setSelection({...selection,choices:{...selection.choices,[groupId]:next}});}
 function save(){if(validation){setError(validation);return;}if(!lineId&&items.filter(i=>i.variantId===variantId).reduce((sum,i)=>sum+i.qty,0)>=cartLimit(product,variantId)){setError("Всё доступное количество уже в корзине.");return;}if(lineId)edit(lineId,selection);else add(product,variantId,selection);dialog.current?.close();}
 return <><button type="button" className={styles.trigger} onClick={open} aria-label={`${lineId?"Изменить состав":"Выбрать состав"}: ${product.title}`}>{label}</button>{mounted&&createPortal(<dialog ref={dialog} className={styles.dialog} aria-label={`Соберите ${product.title}`} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><div className={styles.panel}><button type="button" className={styles.close} aria-label="Закрыть состав" onClick={()=>dialog.current?.close()}><X size={22}/></button><div className={styles.content}>{product.images?.[0]&&<Image src={product.images[0]} alt={product.title} width={500} height={350} unoptimized className={styles.photo}/>}<div className={styles.body}><p className={styles.eyebrow}>НА ВАШ ВКУС</p><h2>{product.title}</h2>{product.description&&<p className={styles.description}>{product.description}</p>}{options.ingredients.length>0&&<section><h3>Состав блюда</h3><p className={styles.hint}>Нажмите на ингредиент, чтобы убрать его</p><div className={styles.ingredients}>{options.ingredients.map(i=><button type="button" key={i.id} disabled={!i.removable} aria-pressed={selection.removed.includes(i.id)} onClick={()=>setSelection({...selection,removed:selection.removed.includes(i.id)?selection.removed.filter(id=>id!==i.id):[...selection.removed,i.id]})}>{i.name}{i.removable&&(selection.removed.includes(i.id)?<Plus size={13}/>:<X size={13}/>)}</button>)}</div></section>}{options.groups.map(group=><section key={group.id}><div className={styles.groupTitle}><h3>{group.title}</h3><span>{group.min===0?"Необязательно":`Выберите ${group.min===group.max?group.min:`${group.min}–${group.max}`}`}</span></div><div className={styles.options}>{group.options.map(option=>{const checked=selection.choices[group.id]?.includes(option.id)??false;return <button type="button" key={option.id} aria-pressed={checked} onClick={()=>toggle(group.id,option.id,group.max)}><span className={styles.optionCheck}>{checked?<Check size={16}/>:<Plus size={16}/>}</span><b>{option.label}</b><small>{option.price?`+${money(option.price)}`:"Входит в цену"}</small></button>;})}</div></section>)}</div></div><footer className={styles.footer}>{(error||validation)&&<p role="alert">{error||validation}</p>}<button type="button" onClick={save} disabled={Boolean(validation)}>{lineId?"Сохранить состав":"Добавить в корзину"}<b>{money(product.price+extra)}</b></button></footer></div></dialog>,document.body)}</>;
}
