import Link from "next/link";
import Image from "next/image";
import { ArrowRight, RefreshCw, Truck } from "lucide-react";
import { CatalogBrowser } from "@/components/store/catalog-browser";
import { nichePresets } from "@/lib/niche-presets";
import type { Product } from "@/lib/demo-data";
import type { Database, BusinessVertical } from "@/types/database";
import { approachForTemplate, configurationFor, type CommerceApproach } from "@/lib/commerce-configurations";
import styles from "./commerce-layouts.module.css";
import { storefrontPath } from "@/lib/storefront-path";
import { EditorialCover } from "./editorial-cover";
import { personalStoreLayout } from "@/lib/personal-store-layout";
import { FoodFulfilmentGate } from "./food-fulfilment-gate";
import { FoodQuickMenu } from "./food-quick-menu";
import { FoodStoryRail } from "./food-story-rail";
import type { StoreStory } from "@/lib/food-stories";
import { ApprovedConceptHome } from "./approved-concept-home";

type Settings = Database["public"]["Tables"]["tenant_storefront_settings"]["Row"];
type Campaign = Pick<Database["public"]["Tables"]["storefront_campaigns"]["Row"], "title" | "eyebrow" | "body" | "cta_label" | "cta_href" | "image_url">;
export type StoreHomeProps = { slug: string; tenant: { name: string; catalog_name: string | null; tagline: string | null; business_vertical: BusinessVertical | null }; products: Product[]; settings: Settings | null; campaign: Campaign | null; storePolicies: { delivery_policy: string | null; return_policy: string | null } | null; approach?: CommerceApproach; checkoutOptions?: { deliveryEnabled: boolean; pickupEnabled: boolean }; foodStories?: StoreStory[]; approvedConceptPreview?: boolean };

// The authenticated preview and published shop share this render tree.
export function StoreHome({ slug, tenant, products, settings, campaign, storePolicies, approach: requestedApproach, checkoutOptions, foodStories, approvedConceptPreview = false }: StoreHomeProps) {
  const layout = personalStoreLayout(settings?.layout_config);
  const approach = requestedApproach ?? approachForTemplate(settings?.template_key ?? "atelier");
  const configuration = configurationFor(tenant.business_vertical ?? "other", approach);
  const categories = Array.from(new Set(products.map((product) => product.category).filter(Boolean)));
  const preset = nichePresets[tenant.business_vertical ?? "other"];
  const title = settings?.hero_title || tenant.catalog_name || tenant.name;
  const subtitle = settings?.hero_subtitle || tenant.tagline || preset.headline;
  const heroImage = settings?.hero_image_url && /^https?:\/\//.test(settings.hero_image_url) ? settings.hero_image_url : null;
  const campaignImage = campaign?.image_url?.startsWith("https://") ? campaign.image_url : null;
  const food = tenant.business_vertical === "food";

  if (approvedConceptPreview && tenant.business_vertical && ["fashion", "beauty", "flowers", "home", "other"].includes(tenant.business_vertical)) return <ApprovedConceptHome vertical={tenant.business_vertical as "fashion" | "beauty" | "flowers" | "home" | "other"} products={products} slug={slug} heroImage={heroImage}/>;

  if (food && (approach === "assortment" || approach === "collection")) return <main className="storefront-theme bg-[var(--store-bg)]" data-approach={approach} data-vertical="food" data-template={settings?.template_key ?? "atelier"}>
    {approach === "collection" && <section className="container pb-3 pt-3 sm:pb-8 sm:pt-7" aria-label="Обложка меню"><div className="overflow-hidden rounded-[var(--store-card-radius)] border border-black/10 bg-[var(--store-surface)] p-4 shadow-[0_24px_70px_rgba(84,37,20,.10)] sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] opacity-55 sm:text-xs">{tenant.name}</p><h1 className="mt-2 max-w-lg font-[family-name:var(--store-display-font)] text-[1.7rem] font-extrabold leading-[1.05] sm:mt-3 sm:text-5xl">{title}</h1><p className="mt-2 line-clamp-2 max-w-xl text-xs opacity-70 sm:mt-3 sm:text-base">{subtitle}</p><a href="#catalog" className="mt-3 inline-flex min-h-10 items-center bg-[var(--tenant-accent)] px-4 py-2 text-xs font-extrabold sm:mt-5 sm:min-h-12 sm:px-5 sm:py-3 sm:text-sm" style={{ borderRadius: "var(--store-button-radius)", color: "var(--store-accent-ink)" }}>Открыть меню →</a><div className="mt-3 grid h-36 min-w-0 grid-cols-3 gap-2 sm:mt-6 sm:h-auto sm:gap-4">{products.filter((product) => product.images?.[0]).slice(0, 3).map((product, index) => <Link key={product.id} href={`${storefrontPath(slug)}/product/${product.id}`} className={`min-w-0 overflow-hidden border-2 border-black/10 bg-[var(--store-bg)] ${index === 0 ? "col-span-2 row-span-2" : ""}`} style={{ borderRadius: "var(--store-card-radius)" }}><Image src={product.images![0]} alt={product.title} width={720} height={720} unoptimized priority={index === 0} className="block size-full max-w-full object-cover sm:aspect-square" /></Link>)}</div></div></section>}
    {approach === "collection" && categories.length > 0 && <nav className={`container ${styles.foodCategoryCircles}`} aria-label="Категории меню">{categories.slice(0, 5).map((category) => { const product = products.find((item) => item.category === category && item.images?.[0]); return <Link key={category} href={`${storefrontPath(slug)}/category/${encodeURIComponent(category)}`}><span>{product?.images?.[0] ? <Image src={product.images[0]} alt="" width={160} height={160} unoptimized /> : null}</span><strong>{category}</strong></Link>; })}</nav>}
    {checkoutOptions && <FoodFulfilmentGate slug={slug} deliveryEnabled={checkoutOptions.deliveryEnabled} pickupEnabled={checkoutOptions.pickupEnabled} />}
    <div id="catalog" style={{ paddingTop: 0 }}><FoodQuickMenu products={products} slug={slug} name={tenant.catalog_name || tenant.name} curatedStories={foodStories} premium={approach === "collection"} /></div>
    {campaign && <section className="container pb-8"><div className="rounded-3xl bg-[#eeeafa] p-6 text-[#352665]">{campaign.eyebrow && <span className="text-sm">{campaign.eyebrow}</span>}<h2 className="mt-2 text-2xl font-bold">{campaign.title}</h2>{campaign.body && <p className="mt-3">{campaign.body}</p>}<Link className="mt-4 inline-block font-semibold underline" href={campaign.cta_href || "#catalog"}>{campaign.cta_label || "Посмотреть меню"} →</Link></div></section>}
    {storePolicies?.delivery_policy && <section className="container border-t py-8"><h2 className="font-semibold">Доставка и самовывоз</h2><p className="mt-3 whitespace-pre-line text-sm opacity-70">{storePolicies.delivery_policy}</p></section>}
    {storePolicies?.return_policy && <section className="container border-t py-8"><h2 className="font-semibold">Условия возврата</h2><p className="mt-3 whitespace-pre-line text-sm opacity-70">{storePolicies.return_policy}</p></section>}
  </main>;

  return <main className={`storefront-theme ${styles.root}`} data-personal={layout ? "true" : undefined} data-typography={layout?.typography} data-hero={layout?.hero} data-density={layout?.density} data-columns={layout?.columns} data-corners={layout?.corners} data-ratio={layout?.imageRatio} data-approach={approach} data-template={settings?.template_key ?? "atelier"} data-vertical={tenant.business_vertical ?? "other"}>
    {(layout ? layout.hero === "editorial" : approach === "collection") ? <EditorialCover templateKey={settings?.template_key} vertical={tenant.business_vertical ?? "other"} title={title} subtitle={subtitle} cta={settings?.hero_cta_label || "Открыть каталог"} heroImage={heroImage} products={products} slug={slug} /> : <header className={`container ${styles.intro}`}><div><span className={styles.sectionCount}>Каталог бренда</span><h1>{title}</h1><p>{subtitle}</p></div>{approach === "assortment" && categories.length > 0 && <nav className={styles.quickSections} aria-label="Выбор раздела">{categories.map((category) => <Link key={category} href={`${storefrontPath(slug)}/category/${encodeURIComponent(category)}`}>{category}<ArrowRight size={16} /></Link>)}</nav>}</header>}
    {tenant.business_vertical === "flowers" && approach === "collection" && categories.length > 0 && <nav className={`container ${styles.categoryCircles}`} aria-label="Категории букетов">{categories.slice(0, 4).map((category) => { const product = products.find((item) => item.category === category && item.images?.[0]); return <Link key={category} href={`${storefrontPath(slug)}/category/${encodeURIComponent(category)}`}><span className={styles.categoryPicture}>{product?.images?.[0] ? <Image src={product.images[0]} alt="" width={240} height={240} unoptimized /> : <span aria-hidden="true" />}</span><strong>{category}</strong></Link>; })}</nav>}
    {Boolean(foodStories?.length) && <div className="container pt-6"><FoodStoryRail products={products} slug={slug} name={tenant.catalog_name || tenant.name} curatedStories={foodStories} placement={approach} /></div>}
    {!food && products.some((product) => product.images?.[0]) && <section className={`container ${styles.conceptStories}`} aria-labelledby="concept-stories-title"><div className={styles.conceptStoriesHead}><h2 id="concept-stories-title">Истории</h2><Link href={`${storefrontPath(slug)}/catalog`}>Смотреть все <ArrowRight size={17} /></Link></div><div>{products.filter((product) => product.images?.[0]).slice(0, 4).map((product, index) => <Link key={product.id} href={`${storefrontPath(slug)}/product/${product.id}`}><Image src={product.images![0]} alt="" width={640} height={420} unoptimized /><span>{index === 0 ? "Что в тренде" : index === 1 ? "Материалы и детали" : index === 2 ? "Выбор команды" : "Новая коллекция"}</span></Link>)}</div></section>}
    {approach === "guided" && categories.length > 0 && <section className="container pb-8" aria-label="Выбор раздела"><h2 className="mb-6 text-2xl font-semibold">{configuration?.title ?? "Выберите раздел"}</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-3">{categories.map((category) => { const product = products.find((item) => item.category === category && item.images?.[0]); return <Link key={category} href={`${storefrontPath(slug)}/category/${encodeURIComponent(category)}`} className="min-w-0 overflow-hidden rounded-2xl border border-black/10 bg-[var(--store-surface)]">{product && <Image src={product.images![0]} alt={category} width={640} height={480} unoptimized className="block aspect-[4/3] w-full max-w-full object-cover" />}<span className="flex items-center justify-between p-5 font-semibold">{category}<ArrowRight size={18} /></span></Link>; })}</div></section>}
    {campaign && <section className="container pt-6"><div className={`storefront-campaign ${campaignImage ? "has-image" : ""}`} style={campaignImage ? { backgroundImage: `linear-gradient(90deg, rgba(2, 19, 15, .94) 0%, rgba(2, 19, 15, .76) 55%, rgba(2, 19, 15, .2) 100%), url(${campaignImage})`, backgroundSize: "cover", backgroundPosition: "center" } : undefined}><div>{campaign.eyebrow && <span>{campaign.eyebrow}</span>}<h2>{campaign.title}</h2>{campaign.body && <p>{campaign.body}</p>}</div><Link href={campaign.cta_href || "#catalog"}>{campaign.cta_label}<ArrowRight size={17} /></Link></div></section>}
    <section id="catalog" className="container py-20"><div className="mb-10"><h2 className="text-4xl font-semibold tracking-[-.035em]">Каталог</h2></div>{products.length ? <CatalogBrowser products={products} slug={slug} food={food} approach={approach} /> : <div className="rounded-2xl border border-dashed border-black/20 py-16 text-center"><h3 className="text-xl font-bold">Каталог готовится</h3><p className="mt-2 opacity-60">Владелец магазина скоро добавит товары.</p></div>}</section>
    {(storePolicies?.delivery_policy || storePolicies?.return_policy) && <section className="container grid gap-5 py-16 md:grid-cols-2"><div><h2 className="text-3xl font-semibold tracking-[-.035em]">Условия магазина</h2><p className="mt-2 max-w-lg text-[var(--store-muted)]">Актуальная информация от продавца.</p></div><div className="grid gap-4">{storePolicies.delivery_policy && <article className="rounded-xl border border-black/10 bg-[var(--store-surface)] p-5"><div className="flex items-center gap-2 font-extrabold"><Truck size={18} />Доставка</div><p className="mt-3 whitespace-pre-line text-sm leading-6 opacity-75">{storePolicies.delivery_policy}</p></article>}{storePolicies.return_policy && <article className="rounded-xl border border-black/10 bg-[var(--store-surface)] p-5"><div className="flex items-center gap-2 font-extrabold"><RefreshCw size={18} />Обмен и возврат</div><p className="mt-3 whitespace-pre-line text-sm leading-6 opacity-75">{storePolicies.return_policy}</p></article>}</div></section>}
  </main>;
}
