"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {Check,Clock3} from "lucide-react";
import {PickupLocationCard} from "@/components/store/pickup-location";
import {buyerOrderProgress} from "@/lib/buyer-order-progress";
type Order={id:string;order_number:number;status:string;total:number;delivery_method:string;fulfilment_snapshot?:{pickup?:unknown};reservation?:{status:string;expires_at:string}|null};
export function MyOrders({slug}:{slug:string}){
 const[orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let disposed=false;const controller=new AbortController();async function load(){if(document.visibilityState==="hidden")return;try{const response=await fetch(`/api/my-orders?slug=${encodeURIComponent(slug)}`,{cache:"no-store",signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error);if(!disposed){setOrders(data.orders);setError("");}}catch(cause){if(!disposed)setError(cause instanceof Error?cause.message:"Нет связи");}finally{if(!disposed)setLoading(false);}}void load();const timer=setInterval(load,10000);document.addEventListener("visibilitychange",load);return()=>{disposed=true;controller.abort();clearInterval(timer);document.removeEventListener("visibilitychange",load);};},[slug]);
 return <main className="container mx-auto max-w-3xl space-y-6 py-10"><Link href={`/s/${slug}`} className="underline">← В каталог</Link><h1 className="text-3xl font-semibold">Мои заказы</h1><p className="text-neutral-500">Заказы, оформленные в этом браузере за последние 30 дней. Статус обновляется автоматически. После очистки cookies история здесь недоступна — обратитесь в магазин.</p>{error&&<p role="alert">{error} Последний показанный статус может быть неактуален.</p>}{loading?<p role="status">Загружаем заказы…</p>:!orders.length?<p>В этом браузере пока нет сохранённых заказов.</p>:orders.map(order=>{
 const {pickup,index:current,closed,expired}=buyerOrderProgress(order);const stages=pickup?["Заказ получен","Продавец проверяет и собирает","Можно забрать","Выдан"]:["Заказ получен","Продавец проверяет и собирает","Передан в доставку","Доставлен"];
 return <article key={order.id} className="space-y-5 rounded-2xl border bg-neutral-50 p-6"><h2 className="text-xl font-semibold">{order.reservation?"Бронь":"Заказ"} №{order.order_number} · {order.total.toLocaleString("ru-RU")} ₸</h2>{order.reservation&&<p>Срок брони: {new Date(order.reservation.expires_at).toLocaleString("ru-KZ")}.</p>}{closed?<p>{expired?"Срок брони истёк. Уточните наличие в магазине перед поездкой.":"Заказ отменён. Не приезжайте за получением."}</p>:<><ol className="space-y-4" aria-label="Этапы заказа">{stages.map((label,index)=><li key={label} aria-current={current===index?"step":undefined} className={`flex items-center gap-3 ${index>current?"text-neutral-400":""}`}><span className={`grid size-8 shrink-0 place-items-center rounded-full ${index<=current?"bg-neutral-900 text-white":"border"}`}>{index<=current?<Check size={17}/>:<Clock3 size={17}/>}</span>{label}</li>)}</ol>{pickup&&current<2&&<p>Пока не приезжайте: продавец проверяет наличие. Адрес получения появится после подтверждения готовности.</p>}{pickup&&current>=2&&<PickupLocationCard value={order.fulfilment_snapshot?.pickup}/>}</>}</article>;
 })}</main>;
}
