version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Asia/Qyzylorda
    open-pull-requests-limit: 5
    groups:
      production-security-updates:
        dependency-type: production
        update-types:
          - patch
          - minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
