"use client";
import {useActionState,useEffect,useState} from "react";
import Link from "next/link";
import {acceptInvitation,registerStaff} from "./actions";
export default function JoinTeam(){
 const[token,setToken]=useState("");const[state,action,pending]=useActionState(acceptInvitation,{});
 const[registration,register,registering]=useActionState(registerStaff,{});
 useEffect(()=>{const query=new URLSearchParams(window.location.search).get("token")??window.location.hash.slice(1);setToken(query);},[]);
 const next=token?`/staff/join?token=${token}`:"/staff/join";
 return <main className="mx-auto grid min-h-[100dvh] max-w-lg place-content-center gap-5 p-6"><div><p className="data-label">КОМАНДА МАГАЗИНА</p><h1 className="mt-3 text-3xl font-semibold">Присоединиться к команде</h1><p className="mt-3 leading-7 text-[var(--ink-60)]">Приглашение привязано к вашему email. После входа вы увидите только те разделы, которые разрешил владелец.</p></div>{!token&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">Ссылка приглашения неполная. Попросите владельца создать и скопировать новую ссылку.</p>}<section className="card space-y-4 p-5"><h2 className="text-lg font-bold">Уже есть аккаунт</h2><p className="text-sm text-[var(--ink-60)]">Войдите с тем же email, на который создано приглашение.</p><Link href={`/login?next=${encodeURIComponent(next)}`} className="btn btn-primary w-full">Войти и продолжить</Link></section><details className="card p-5"><summary className="cursor-pointer font-bold">Нет аккаунта? Создать аккаунт сотрудника</summary><form action={register} className="mt-4 space-y-3"><input type="hidden" name="token" value={token}/><label className="block text-sm font-bold">Email приглашения<input required type="email" name="email" autoComplete="email" className="input mt-2"/></label><label className="block text-sm font-bold">Новый пароль<input required type="password" name="password" minLength={10} maxLength={128} autoComplete="new-password" className="input mt-2"/></label><button disabled={registering||!token} className="btn btn-secondary w-full">{registering?"Создаём…":"Создать аккаунт"}</button>{registration.error&&<p role="alert" className="text-sm text-red-700">{registration.error}</p>}{registration.success&&<p role="status" className="text-sm text-emerald-700">{registration.success}</p>}</form></details><form action={action} className="card p-5"><input type="hidden" name="token" value={token}/><p className="mb-4 text-sm text-[var(--ink-60)]">После входа нажмите кнопку один раз — доступ появится сразу.</p><button disabled={pending||!token} className="btn btn-primary w-full">{pending?"Проверяем…":"Принять приглашение"}</button>{state.error&&<p role="alert" className="mt-4 text-sm text-red-700">{state.error}</p>}</form></main>;
}
