import type{SupabaseClient}from"@supabase/supabase-js";import type{Database,Json,ProductRow,VariantRow}from"@/types/database";
export async function getTenant(client:SupabaseClient<Database>,tenantId:string){return client.from("tenants").select("*").eq("id",tenantId).single()}
export async function updateTenantBranding(client:SupabaseClient<Database>,tenantId:string,values:{name:string;tagline:string;city:string;phone:string;accent_color:string}){return client.from("tenants").update(values).eq("id",tenantId)}
export async function getOwnerCatalog(client:SupabaseClient<Database>,tenantId:string){const[{data:products,error},{data:variants,error:variantError}]=await Promise.all([client.from("products").select("*").eq("tenant_id",tenantId).order("created_at",{ascending:false}),client.from("product_variants").select("*").eq("tenant_id",tenantId)]);if(error)throw error;if(variantError)throw variantError;return{products:products as ProductRow[],variants:variants as VariantRow[]}}
export async function getOwnerOrders(client:SupabaseClient<Database>,tenantId:string){return client.from("orders").select("*").eq("tenant_id",tenantId).order("created_at",{ascending:false}).limit(100)}
export async function getOwnerCustomers(client:SupabaseClient<Database>,tenantId:string){return client.from("customers").select("*").eq("tenant_id",tenantId).order("total_spent",{ascending:false})}
export async function getOwnerRequests(client:SupabaseClient<Database>,tenantId:string){return client.from("change_requests").select("*").eq("tenant_id",tenantId).order("created_at")}
export async function getOwnerMessages(client:SupabaseClient<Database>,tenantId:string){return client.from("messages").select("*").eq("tenant_id",tenantId).order("created_at")}
export async function setProductActive(client:SupabaseClient<Database>,tenantId:string,productId:string,isActive:boolean){return client.from("products").update({is_active:isActive}).eq("tenant_id",tenantId).eq("id",productId)}
export async function updateProduct(client:SupabaseClient<Database>,tenantId:string,productId:string,values:{title:string;description:string;price:number;old_price:number|null;is_active:boolean}){return client.from("products").update(values).eq("tenant_id",tenantId).eq("id",productId)}
export async function updateVariant(client:SupabaseClient<Database>,tenantId:string,variantId:string,values:{size:string|null;color:string|null;sku:string|null}){return client.from("product_variants").update(values).eq("tenant_id",tenantId).eq("id",variantId)}
export async function addStockCorrection(client:SupabaseClient<Database>,tenantId:string,variantId:string,delta:number){return client.from("stock_movements").insert({tenant_id:tenantId,variant_id:variantId,delta,reason:"correction"})}
export async function updateOrderStatus(client:SupabaseClient<Database>,tenantId:string,orderId:string,status:Database["public"]["Enums"]["order_status"]){return client.from("orders").update({status}).eq("tenant_id",tenantId).eq("id",orderId)}
export async function createChangeRequest(client:SupabaseClient<Database>,tenantId:string,text:string){return client.from("change_requests").insert({tenant_id:tenantId,text,status:"new"})}
export async function createMessage(client:SupabaseClient<Database>,tenantId:string,text:string){return client.from("messages").insert({tenant_id:tenantId,text,from_role:"owner"})}
export async function createProduct(client:SupabaseClient<Database>,input:{tenantId:string;title:string;description:string;price:number;oldPrice:number|null;categoryId:string|null;images:string[];isActive:boolean;variants:{size:string;color:string;sku:string;stock:number}[]}){return client.rpc("create_product_with_variants",{p_tenant_id:input.tenantId,p_title:input.title,p_description:input.description,p_price:input.price,p_old_price:input.oldPrice,p_category_id:input.categoryId,p_images:input.images,p_is_active:input.isActive,p_variants:input.variants as Json})}
export async function createOfflineSale(client:SupabaseClient<Database>,tenantId:string,variantId:string,qty:number){return client.rpc("create_offline_sale",{p_tenant_id:tenantId,p_variant_id:variantId,p_qty:qty})}
export async function uploadProductImage(client:SupabaseClient<Database>,tenantId:string,file:File){const extension=file.name.split(".").pop()?.toLowerCase()??"jpg";const path=`${tenantId}/${crypto.randomUUID()}.${extension}`;const{error}=await client.storage.from("product-images").upload(path,file,{contentType:file.type,upsert:false});if(error)return{url:null,error};return{url:client.storage.from("product-images").getPublicUrl(path).data.publicUrl,error:null}}
