import type{SupabaseClient}from"@supabase/supabase-js";import type{Database}from"@/types/database";import type{Plan}from"@/lib/plans";
export async function getPlatformTenants(client:SupabaseClient<Database>){return client.from("tenants").select("*").order("created_at",{ascending:false})}
export async function getPlatformOrders(client:SupabaseClient<Database>){return client.from("orders").select("*").order("created_at",{ascending:false}).limit(500)}
export async function getPlatformRequests(client:SupabaseClient<Database>){return client.from("change_requests").select("*").order("created_at",{ascending:false}).limit(100)}
export async function getPlatformMessages(client:SupabaseClient<Database>,tenantId:string){return client.from("messages").select("*").eq("tenant_id",tenantId).order("created_at")}
export async function createTenantAndOwner(client:SupabaseClient<Database>,input:{email:string;password:string;slug:string;name:string;color:string;plan:Plan}){const{data:userData,error:userError}=await client.auth.admin.createUser({email:input.email,password:input.password,email_confirm:true});if(userError||!userData.user)return{error:userError??new Error("Owner was not created")};const userId=userData.user.id;const{data:tenant,error:tenantError}=await client.from("tenants").insert({slug:input.slug,name:input.name,accent_color:input.color,plan:input.plan,status:"trial"}).select("id").single();if(tenantError||!tenant){await client.auth.admin.deleteUser(userId);return{error:tenantError??new Error("Tenant was not created")}}const[profile,membership,settings]=await Promise.all([client.from("profiles").insert({user_id:userId,role:"owner"}),client.from("tenant_users").insert({tenant_id:tenant.id,user_id:userId,role:"owner"}),client.from("tenant_settings").insert({tenant_id:tenant.id,delivery_enabled:true,pickup_enabled:true,payment_online:input.plan!=="basic",min_order:0})]);const error=profile.error??membership.error??settings.error;if(error){await client.auth.admin.deleteUser(userId);return{error}}return{data:{tenantId:tenant.id,userId},error:null}}
export async function changeTenantStatus(client:SupabaseClient<Database>,tenantId:string,status:"active"|"paused"|"trial"){return client.from("tenants").update({status}).eq("id",tenantId)}
export async function changeTenantPlan(client:SupabaseClient<Database>,tenantId:string,plan:Plan){return client.from("tenants").update({plan}).eq("id",tenantId)}
export async function rootMessage(client:SupabaseClient<Database>,tenantId:string,text:string){return client.from("messages").insert({tenant_id:tenantId,from_role:"superadmin",text})}
export async function setRequestStatus(client:SupabaseClient<Database>,requestId:string,status:"new"|"in_progress"|"done"){return client.from("change_requests").update({status}).eq("id",requestId)}
