import { ThemeColorControls } from "@/components/admin/theme-color-controls";
import { requireRole } from "@/lib/auth";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { getStorefrontSettings, getTenant, getTenantSettings } from "@/lib/queries/owner";
import { saveStorePolicies, saveStoreSettings, saveThemeSettings } from "@/app/admin/actions";
import { hasPlan, type Plan } from "@/lib/plans";
import { templateCatalog } from "@/lib/storefront-theme";
import { computeEntitlement } from "@/lib/entitlement";

export default async function Settings(){
  const {tenantId}=await requireRole(["owner","superadmin"]);
  const demo={name:"Серик Шоп",slug:"demo-shop",tagline:"Вещи, которые остаются с вами",city:"Кызылорда",phone:"+7 777 000 00 00",accent_color:"#0E5C4A",plan:"standard" as const,next_plan:"standard" as const,status:"active" as const,trial_ends_at:null};
  const client=process.env.NEXT_PUBLIC_SUPABASE_URL?await createClient():null;
  const tenant=client?(await getTenant(client,tenantId!)).data:demo;if(!tenant)return null;
  const settings=client?(await getStorefrontSettings(client,tenantId!)).data:null;
  const storePolicies=client?(await getTenantSettings(client,tenantId!)).data:null;
  const plan=computeEntitlement(tenant).plan as Plan;
  return <div className="mx-auto max-w-5xl space-y-8">
    <Link href="/admin/settings/usage" className="btn btn-secondary">Использование AI →</Link>
    <Link href="/admin/settings/delivery" className="btn btn-secondary">Зоны и стоимость доставки →</Link>
    <div><p className="data-label">КОНСТРУКТОР ВИТРИНЫ</p><h1 className="mt-2 text-3xl font-semibold">Настройки магазина</h1><p className="muted mt-2 max-w-2xl">Собирайте витрину из качественных блоков: название, каталог, шаблон, палитра и кампания. Подпись Dukenim на витрине всегда остаётся — на «Бренде» она становится тише и наследует стиль магазина.</p></div>
    <form action={saveStoreSettings} className="card space-y-5 p-6"><h2 className="text-xl font-bold">Основа магазина</h2><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Название<input name="name" className="input mt-2" defaultValue={tenant.name}/></label><label className="text-sm font-bold">Город<input name="city" className="input mt-2" defaultValue={tenant.city??""}/></label></div><label className="block text-sm font-bold">Слоган<input name="tagline" className="input mt-2" defaultValue={tenant.tagline??""}/></label><label className="block text-sm font-bold">Телефон<input name="phone" className="input mt-2" defaultValue={tenant.phone??""}/></label><label className="block text-sm font-bold">Базовый цвет<input name="accentColor" className="ml-4 h-10 w-20 align-middle" type="color" defaultValue={tenant.accent_color}/></label><button className="btn btn-primary">Сохранить основу</button></form>
    <form action={saveThemeSettings} className="card space-y-6 p-6"><div><h2 className="text-xl font-bold">Шаблон и тема</h2><p className="muted mt-1 text-sm">Выберите подачу товаров и свои цвета. Настройки доступны для изменения в любой момент.</p></div><div className="grid gap-3 md:grid-cols-3">{templateCatalog.map(item=>{const locked=!hasPlan(plan,item.minPlan as Plan);return <label key={item.key} className={`rounded-xl border p-4 ${locked?"border-[var(--line)] opacity-50":"border-[var(--accent)]/35"}`}><input className="sr-only" type="radio" name="templateKey" value={item.key} defaultChecked={(settings?.template_key??"atelier")===item.key} disabled={locked}/><b>{item.name}{locked&&<small className="ml-2 text-[var(--accent)]">Бренд</small>}</b><span className="muted mt-2 block text-xs leading-5">{item.description}</span></label>})}</div><ThemeColorControls value={settings?.color_theme} paletteKey={settings?.palette_key??"mono"}/><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Заголовок обложки<input name="heroTitle" className="input mt-2" defaultValue={settings?.hero_title??""}/></label><label className="text-sm font-bold">Кнопка<input name="heroCtaLabel" className="input mt-2" defaultValue={settings?.hero_cta_label??"Смотреть каталог"}/></label></div><label className="block text-sm font-bold">Короткое описание<input name="heroSubtitle" className="input mt-2" defaultValue={settings?.hero_subtitle??""}/></label><label className="block text-sm font-bold">Ссылка на фото обложки (необязательно)<input name="heroImageUrl" type="url" className="input mt-2" defaultValue={settings?.hero_image_url??""}/></label><button className="btn btn-primary">Сохранить оформление</button></form>
    <form action={saveStorePolicies} className="card space-y-5 p-6"><div><h2 className="text-xl font-bold">Доставка и возврат</h2><p className="muted mt-1 text-sm">Необязательные условия. Пока поле пустое, соответствующий блок не появится у покупателя.</p></div><label className="block text-sm font-bold">Условия доставки<textarea name="deliveryPolicy" maxLength={2000} defaultValue={storePolicies?.delivery_policy??""} className="input mt-2 min-h-28 py-3" placeholder="Например: Доставка по Кызылорде 1–2 дня. Стоимость уточнит менеджер."/></label><label className="block text-sm font-bold">Обмен и возврат<textarea name="returnPolicy" maxLength={2000} defaultValue={storePolicies?.return_policy??""} className="input mt-2 min-h-28 py-3" placeholder="Например: Обмен возможен в течение 14 дней при сохранении товарного вида."/></label><button className="btn btn-primary">Сохранить условия</button></form>
    <section className="card p-6"><h2 className="text-xl font-bold">Адрес магазина</h2><p className="muted mt-2">Постоянная ссылка уже готова: <b>dukenim.kz/s/{tenant.slug}</b>. Она работает на любом устройстве и не меняется при обновлении шаблона или тарифа.</p></section>
  </div>
}
