import{createHmac}from"node:crypto";
import{describe,expect,it,vi}from"vitest";
import{applyPaddleEntitlementEvent,normalizePaddleEntitlementEvent,PaddleSandboxAdapter,paddleSandboxReadiness,verifyPaddleSignature}from"./paddle-adapter";

const readyEnv={NODE_ENV:"test",PADDLE_ENV:"sandbox",PADDLE_SANDBOX_ENABLED:"true",PADDLE_PROVIDER_REVIEW_APPROVED:"true",PREMIUM_BILLING_PERIOD_CONFIRMED:"monthly",PADDLE_API_KEY:"sandbox-key",PADDLE_WEBHOOK_SECRET:"webhook-secret",PADDLE_PREMIUM_MONTHLY_PRICE_ID:"pri_test"} as NodeJS.ProcessEnv;
describe("Paddle sandbox adapter",()=>{
  it("fails closed until review, period, ids and secrets are all explicit",()=>{expect(paddleSandboxReadiness({NODE_ENV:"test"} as NodeJS.ProcessEnv).available).toBe(false);expect(paddleSandboxReadiness(readyEnv).available).toBe(true);});
  it("verifies the raw body, timestamp and HMAC without transforming JSON",()=>{const raw='{"event_id":"evt"}';const ts="1700000000";const h1=createHmac("sha256","secret").update(`${ts}:${raw}`).digest("hex");expect(verifyPaddleSignature({rawBody:raw,signatureHeader:`ts=${ts};h1=${h1}`,secret:"secret",nowMs:1700000000000})).toEqual({timestamp:1700000000});expect(()=>verifyPaddleSignature({rawBody:`${raw} `,signatureHeader:`ts=${ts};h1=${h1}`,secret:"secret",nowMs:1700000000000})).toThrow();});
  it("normalizes only tenant-mapped subscription events",()=>{const payload={event_id:"evt_1",event_type:"subscription.activated",occurred_at:"2026-10-04T00:00:00Z",data:{id:"sub_1",customer_id:"ctm_1",status:"active",custom_data:{tenantId:"00000000-0000-4000-8000-000000000001"},items:[{price:{id:"pri_test"}}],current_billing_period:{ends_at:"2026-11-04T00:00:00Z"}}};expect(normalizePaddleEntitlementEvent(payload)).toMatchObject({tenantId:"00000000-0000-4000-8000-000000000001",status:"active",priceId:"pri_test"});expect(normalizePaddleEntitlementEvent({...payload,data:{...payload.data,custom_data:{}}})).toBeNull();});
  it("delegates event idempotency and entitlement mutation to one atomic server repository",async()=>{const applyAtomically=vi.fn(async()=>"duplicate" as const);const event=normalizePaddleEntitlementEvent({event_id:"evt_1",event_type:"subscription.canceled",data:{id:"sub_1",customer_id:"ctm_1",status:"canceled",custom_data:{tenantId:"00000000-0000-4000-8000-000000000001"},items:[{price:{id:"pri_test"}}]}})!;await expect(applyPaddleEntitlementEvent(event,{applyAtomically})).resolves.toBe("duplicate");expect(applyAtomically).toHaveBeenCalledOnce();});
  it("creates sandbox transactions only behind every release gate",async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({data:{id:"txn_1",checkout:{url:"https://sandbox-pay.test"}}}),{status:200})) as unknown as typeof fetch;const adapter=new PaddleSandboxAdapter(readyEnv,fetcher);await expect(adapter.createPremiumCheckout({tenantId:"00000000-0000-4000-8000-000000000001",successUrl:"https://example.test/success"})).resolves.toMatchObject({transactionId:"txn_1"});expect(fetcher).toHaveBeenCalledWith("https://sandbox-api.paddle.com/transactions",expect.objectContaining({method:"POST"}));});
});
