"use client";

import { useActionState, useMemo, useState } from "react";
import { ArrowRight, Check, LoaderCircle } from "lucide-react";
import { createCatalogAction, type CatalogActionState } from "@/app/admin/actions";
import { launchTemplatesForPlan, palettes, paletteByKey } from "@/lib/storefront-theme";

const initialState: CatalogActionState = {};

export function CatalogSetupForm({ defaultName, slug, plan }: { defaultName: string; slug: string; plan: "basic" | "standard" | "pro" }) {
  const [state, action, pending] = useActionState(createCatalogAction, initialState);
  const templates = launchTemplatesForPlan(plan);
  const [templateKey, setTemplateKey] = useState<string>(templates[0].key);
  const [paletteKey, setPaletteKey] = useState("ink-brass");
  const selectedTemplate = useMemo(() => templates.find((item) => item.key === templateKey) ?? templates[0], [templateKey, templates]);
  const palette = paletteByKey(paletteKey);
  const isBrand = plan !== "basic";

  return <form action={action} className="mt-7 max-w-6xl space-y-8"><section className="card p-6 md:p-8"><h2 className="text-xl font-extrabold">Основа витрины</h2><label className="mt-5 block max-w-xl text-sm font-bold">Название каталога<input name="catalogName" required minLength={2} maxLength={80} defaultValue={defaultName} className="input mt-2" placeholder="Например, Aru Store" /></label><p className="mt-3 text-sm text-[var(--ink-60)]">Адрес витрины: <b className="text-[var(--ink)]">dukenim.kz/s/{slug}</b>. Его можно открыть после добавления первого товара.</p></section>

    <section><div><h2 className="text-xl font-extrabold">Выберите основу дизайна</h2><p className="mt-2 text-sm text-[var(--ink-60)]">На тарифе «{isBrand ? "Бренд" : "Старт"}» доступны две разные витрины. Обе адаптированы под телефон и каталог; их можно изменить позже.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2">{templates.map((option) => { const selected = option.key === templateKey; const name = option.key === "atelier" ? "Ателье" : option.key === "market" ? "Маркет" : option.key === "journal" ? "Журнал" : "Галерея"; return <label key={option.key} className={`cursor-pointer rounded-[14px] border p-5 transition ${selected ? "border-[var(--accent)] bg-[var(--accent-soft)] shadow-sm" : "border-[var(--line)] bg-[var(--surface)] hover:border-[var(--accent)]"}`}><input className="sr-only" type="radio" name="templateKey" value={option.key} checked={selected} onChange={() => setTemplateKey(option.key)} /><div className="flex items-start justify-between gap-4"><div><b className="text-lg">{name}</b><p className="mt-2 text-sm leading-6 text-[var(--ink-60)]">{option.benefit}</p></div>{selected && <span className="grid size-7 shrink-0 place-items-center rounded-full bg-[var(--accent)] text-[var(--accent-ink)]"><Check size={16} /></span>}</div><div className={`mt-5 grid h-24 grid-cols-4 gap-2 overflow-hidden rounded-xl p-3 ${option.key === "atelier" || option.key === "gallery" ? "bg-[var(--accent-dark)]" : "bg-[var(--surface-muted)]"}`}><span className="col-span-2 rounded-md bg-[var(--accent)]/70" /><span className="rounded-md bg-white/70" /><span className="rounded-md bg-white/40" /><span className="rounded-md bg-white/40" /><span className="rounded-md bg-white/70" /><span className="col-span-2 rounded-md bg-[var(--accent)]/45" /></div></label>})}</div></section>

    <section className="card p-6 md:p-8"><h2 className="text-xl font-extrabold">Палитра витрины</h2><p className="mt-2 text-sm text-[var(--ink-60)]">Готовые сочетания сохраняют контраст и читаемость. Выберите то, что подходит вашему товару.</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{palettes.map((option) => <label key={option.key} className={`cursor-pointer rounded-xl border p-3 transition ${paletteKey === option.key ? "border-[var(--accent)] ring-1 ring-[var(--accent)]" : "border-[var(--line)] hover:border-[var(--accent)]"}`}><input className="sr-only" name="paletteKey" type="radio" value={option.key} checked={paletteKey === option.key} onChange={() => setPaletteKey(option.key)} /><span className="flex h-8 overflow-hidden rounded-md"><i className="flex-1" style={{ background: option.background }} /><i className="flex-1" style={{ background: option.surface }} /><i className="flex-1" style={{ background: option.accent }} /></span><b className="mt-2 block text-xs">{option.name}</b></label>)}</div>{isBrand && <label className="mt-6 flex flex-wrap items-center gap-3 text-sm font-bold">Фирменный акцент <input name="brandColor" type="color" defaultValue={palette.accent} className="h-10 w-16 cursor-pointer rounded border border-[var(--line)] bg-white p-1" /><span className="font-normal text-[var(--ink-60)]">Используем поверх выбранной палитры, если цвет остаётся читаемым.</span></label>}</section>

    <section className="card overflow-hidden"><div className="grid md:grid-cols-[.9fr_1.1fr]"><div className="p-6 md:p-8"><h2 className="text-xl font-extrabold">Так будет выглядеть каталог</h2><p className="mt-2 text-sm leading-6 text-[var(--ink-60)]">«{selectedTemplate.key === "atelier" ? "Ателье" : selectedTemplate.key === "market" ? "Маркет" : selectedTemplate.key === "journal" ? "Журнал" : "Галерея"}» + «{palette.name}» — стартовая версия. Товары, логотип и контент вы добавите следующим шагом.</p>{state.error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm font-medium text-red-700">{state.error}</p>}<button disabled={pending} className="btn btn-cta mt-7">{pending ? <><LoaderCircle className="animate-spin" size={18} />Создаём…</> : <>Создать каталог и продолжить <ArrowRight size={18} /></>}</button></div><div className="min-h-64 p-6" style={{ background: palette.background, color: palette.ink }}><div className="mx-auto max-w-sm rounded-xl p-5 shadow-lg" style={{ background: palette.surface }}><div className="flex items-center justify-between"><b>Ваш магазин</b><span className="size-3 rounded-full" style={{ background: palette.accent }} /></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="aspect-[4/5] rounded-lg" style={{ background: palette.accent }} /><div className="aspect-[4/5] rounded-lg opacity-60" style={{ background: palette.muted }} /></div><p className="mt-4 text-sm font-bold">Новая коллекция</p></div></div></div></section>
  </form>;
}
