"use client";
import {useState} from "react";
import {CircleHelp,Plus,Trash2,UtensilsCrossed} from "lucide-react";
import {readFoodOptions,type FoodOptions} from "@/lib/food-options";
type Choice={id:string;label:string};
export function FoodOptionsEditor({initial,choices=[]}:{initial?:unknown;choices?:Choice[]}){
 const [value,setValue]=useState<FoodOptions>(()=>readFoodOptions(initial));
 const [expanded,setExpanded]=useState(Boolean(value.ingredients.length||value.groups.length));
 const uid=()=>crypto.randomUUID();
 function groupChange(index:number,patch:Partial<FoodOptions["groups"][number]>){setValue({...value,groups:value.groups.map((g,i)=>i===index?{...g,...patch}:g)});}
 return <section className="rounded-2xl border border-purple-100 bg-[#faf8fe] p-5"><input type="hidden" name="foodOptions" value={JSON.stringify(value)}/><button type="button" onClick={()=>setExpanded(!expanded)} className="flex w-full items-center gap-3 text-left"><UtensilsCrossed size={21} className="text-purple-600"/><span className="flex-1"><b className="block">Состав, добавки и комбо</b><small className="mt-1 block text-neutral-500">Необязательно · гость соберёт блюдо на свой вкус</small></span><span>{expanded?"−":"+"}</span></button>
 {expanded&&<div className="mt-6 space-y-6">
 <section className="rounded-xl border border-neutral-200 bg-white p-4"><h3 className="font-semibold">Вес и КБЖУ · необязательно</h3><p className="mt-1 text-xs text-neutral-500">Укажите на порцию. Можно заполнить после сохранения товара.</p><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-5">{([['weightGrams','Вес, г'],['kcal','Ккал'],['protein','Белки, г'],['fat','Жиры, г'],['carbs','Углеводы, г']] as const).map(([key,label])=><label key={key} className="text-xs">{label}<input type="number" inputMode="decimal" min={0} max={key==='weightGrams'||key==='kcal'?100000:10000} step={key==='weightGrams'||key==='kcal'?1:0.1} value={value.nutrition?.[key]??''} className="input mt-1" onChange={event=>{const next={weightGrams:0,kcal:0,protein:0,fat:0,carbs:0,...value.nutrition,[key]:Number(event.target.value)||0};setValue({...value,nutrition:event.target.value===''&&Object.values(next).every(v=>v===0)?undefined:next});}}/></label>)}</div></section>
 <div><h3 className="font-semibold">Что входит в блюдо</h3><p className="mt-1 text-xs leading-6 text-neutral-500">Добавляйте ингредиенты отдельно. Отметьте, какие гость может убрать бесплатно.</p><div className="mt-3 space-y-2">{value.ingredients.map((ingredient,index)=><div key={ingredient.id} className="flex flex-wrap items-center gap-2 rounded-xl bg-white p-3"><input aria-label={`Ингредиент ${index+1}`} className="input min-w-0 flex-1 basis-36" value={ingredient.name} maxLength={60} placeholder="Например, огурцы" onChange={e=>setValue({...value,ingredients:value.ingredients.map((i,n)=>n===index?{...i,name:e.target.value}:i)})}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={ingredient.removable} onChange={e=>setValue({...value,ingredients:value.ingredients.map((i,n)=>n===index?{...i,removable:e.target.checked}:i)})}/>Можно убрать</label><button type="button" aria-label={`Удалить ингредиент ${index+1}`} className="p-2 text-neutral-400" onClick={()=>setValue({...value,ingredients:value.ingredients.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div>)}</div>{value.ingredients.length<30&&<button type="button" className="mt-3 flex items-center gap-2 text-sm text-purple-700" onClick={()=>setValue({...value,ingredients:[...value.ingredients,{id:uid(),name:"",removable:true}]})}><Plus size={15}/>Добавить ингредиент</button>}</div>
 {value.groups.map((group,index)=><section key={group.id} className="space-y-4 rounded-2xl border border-neutral-200 bg-white p-4"><div className="flex items-center justify-between"><b>{group.kind==="combo"?"Часть комбо":"Добавки к блюду"}</b><button type="button" aria-label={`Удалить группу ${index+1}`} className="p-2 text-neutral-400" onClick={()=>setValue({...value,groups:value.groups.filter((_,i)=>i!==index)})}><Trash2 size={17}/></button></div><label className="block text-xs">Название блока<input className="input mt-2" maxLength={80} value={group.title} placeholder={group.kind==="combo"?"Выберите напиток":"Добавить к блюду"} onChange={e=>groupChange(index,{title:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Минимум вариантов<select className="input mt-2" value={group.min} onChange={e=>groupChange(index,{min:Number(e.target.value)})}>{Array.from({length:11},(_,n)=><option key={n} value={n}>{n}</option>)}</select></label><label className="text-xs">Максимум вариантов<select className="input mt-2" value={group.max} onChange={e=>groupChange(index,{max:Number(e.target.value)})}>{Array.from({length:10},(_,n)=><option key={n+1} value={n+1}>{n+1}</option>)}</select></label></div><p className="text-xs text-neutral-400">Минимум 0 — необязательно. Для одной обязательной позиции укажите 1 и 1.</p>
 {group.options.map((option,oi)=><div key={option.id} className="grid grid-cols-[minmax(0,1fr)_90px_32px] items-end gap-2 rounded-xl bg-neutral-50 p-3"><label className="min-w-0 text-xs">{group.kind==="combo"?"Товар из меню":"Название добавки"}{group.kind==="combo"?<select className="input mt-2" value={option.variantId??""} onChange={e=>groupChange(index,{options:group.options.map((o,n)=>n===oi?{...o,variantId:e.target.value||null,label:choices.find(c=>c.id===e.target.value)?.label??""}:o)})}><option value="">Выберите товар</option>{choices.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select>:<input className="input mt-2" maxLength={80} value={option.label} placeholder="Сыр" onChange={e=>groupChange(index,{options:group.options.map((o,n)=>n===oi?{...o,label:e.target.value}:o)})}/>}</label><label className="text-xs">Доплата, ₸<input className="input mt-2" type="number" min={0} max={1000000} value={option.price} onChange={e=>groupChange(index,{options:group.options.map((o,n)=>n===oi?{...o,price:Number(e.target.value)}:o)})}/></label><button type="button" aria-label={`Удалить вариант ${oi+1}`} className="h-11 text-neutral-400" onClick={()=>groupChange(index,{options:group.options.filter((_,n)=>n!==oi)})}><Trash2 size={15}/></button></div>)}{group.options.length<20&&<button type="button" className="flex items-center gap-2 text-xs text-purple-700" onClick={()=>groupChange(index,{options:[...group.options,{id:uid(),label:"",price:0,variantId:null}]})}><Plus size={14}/>Добавить вариант</button>}
 </section>)}
 {value.groups.length<8&&<div className="flex flex-wrap items-center gap-3">{(["addon","combo"] as const).map(kind=><span key={kind} className="inline-flex items-center gap-2"><button type="button" className="btn btn-secondary text-sm" disabled={kind==="combo"&&!choices.length} onClick={()=>setValue({...value,groups:[...value.groups,{id:uid(),title:kind==="combo"?"Выберите напиток":"Добавки",kind,min:kind==="combo"?1:0,max:kind==="combo"?1:3,options:[{id:uid(),label:"",price:0,variantId:null}]}]})}><Plus size={15}/>{kind==="combo"?"Добавить часть комбо":"Добавить блок добавок"}</button>{kind==="combo"&&<span title={!choices.length?"Сначала сохраните первое блюдо, затем добавьте отдельный товар или напиток и вернитесь сюда. В комбо выбираются только существующие товары меню.":"Выберите готовые товары меню, которые входят в набор. Их остатки будут списаны вместе с основным блюдом."} aria-label={!choices.length?"Сначала добавьте отдельный товар для комбо":"Комбо объединяет существующие товары меню"} tabIndex={0} className="cursor-help text-neutral-500"><CircleHelp size={18}/></span>}</span>)}</div>}
 <p className="text-xs leading-6 text-neutral-500">Цена блюда — основа комбо. Доплаты прибавляются к ней. Товары комбо списываются из меню; добавки и убранные ингредиенты передаются кухне без складского учёта сырья.{!choices.length?" Сначала создайте отдельные блюда и напитки, затем объедините их в комбо.":""}</p>
 </div>}
 </section>;
}
