"use client";
import {useState} from "react";
import {CalendarDays,Sparkles} from "lucide-react";
import {holidayDesignBrief,holidayIdeas,holidayPromotionBrief,nextHolidayIdeas,type HolidayIdea} from "@/lib/holiday-ideas";
export function HolidayIdeas({disabled,onDesign,onPromotion}:{disabled:boolean;onDesign:(brief:string)=>void;onPromotion:(brief:string)=>void}){
 const[now]=useState(()=>new Date());const upcoming=nextHolidayIdeas(now);const[next]=useState(()=>{const all=nextHolidayIdeas(now,366);return all[0]??null;});
 const[custom,setCustom]=useState("");const[customDate,setCustomDate]=useState("");
 const show=(idea:HolidayIdea)=>{onDesign(holidayDesignBrief(idea));};
 return <section className="rounded-3xl border border-sky-200 bg-gradient-to-br from-[#10253d] via-[#315f78] to-[#376e97] p-5 text-white shadow-[0_20px_50px_rgba(16,37,61,.18)] md:p-6" aria-label="Календарь идей для витрины"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.17em] text-sky-200"><Sparkles size={16}/> Идея для магазина</p><h2 className="mt-2 text-xl font-extrabold md:text-2xl">Оформление к важным датам</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-sky-100">За неделю до события здесь появится предложение. AI подготовит дизайн и текст; примените только то, что подходит вашему бизнесу.</p></div><CalendarDays className="text-sky-200" size={27}/></div>
  {upcoming.length?<div className="mt-5 grid gap-3">{upcoming.map(idea=><article key={idea.key} className="rounded-2xl border border-white/25 bg-white/12 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b>{idea.name}</b><span className="rounded-full bg-white/20 px-3 py-1 text-xs font-bold">{idea.daysUntil===0?"Сегодня":`Через ${idea.daysUntil} дн.`}</span></div><p className="mt-1 text-sm text-sky-100">{idea.hint}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={disabled} onClick={()=>show(idea)} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-[#10253d] disabled:opacity-50">Предложить дизайн</button><button type="button" disabled={disabled} onClick={()=>onPromotion(holidayPromotionBrief(idea))} className="rounded-xl border border-white/40 px-4 py-2 text-sm font-bold disabled:opacity-50">Текст кампании</button></div></article>)}</div>:<p className="mt-5 rounded-2xl border border-white/20 bg-white/10 p-4 text-sm text-sky-100">Следующая дата: <b className="text-white">{next?.name??"уточняется"}</b>. Вы можете выбрать её заранее или указать свою.</p>}
  <details className="mt-4 rounded-xl border border-white/20 p-3 text-sm"><summary className="cursor-pointer font-semibold">Календарь дат и своё событие</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{holidayIdeas.map(idea=><button type="button" key={idea.key} disabled={disabled} onClick={()=>show(idea)} className="flex justify-between gap-2 rounded-xl bg-white/10 px-3 py-2 text-left hover:bg-white/20 disabled:opacity-50"><span>{idea.name}</span><span className="text-sky-200">{String(idea.day).padStart(2,"0")}.{String(idea.month).padStart(2,"0")}</span></button>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input className="input text-[#142334]" value={custom} onChange={event=>setCustom(event.target.value)} maxLength={60} placeholder="Ваше событие" aria-label="Название своего события"/><input className="input text-[#142334]" type="date" value={customDate} onChange={event=>setCustomDate(event.target.value)} aria-label="Дата своего события"/><button type="button" disabled={disabled||custom.trim().length<3||!customDate} onClick={()=>onDesign(`Подготовь оформление витрины к событию «${custom.trim()}» ${customDate}. Предложи согласованную палитру и текст главного экрана. Не придумывай цены, скидки, товары или наличие. Покажи черновик для подтверждения владельцем.`)} className="rounded-xl bg-white px-4 py-2 font-bold text-[#10253d] disabled:opacity-50">Подготовить</button></div></details><p className="mt-3 text-xs text-sky-100/80">Указаны основные фиксированные даты. Переносы выходных и даты по лунному календарю здесь не рассчитываются.</p></section>;
}
