import Link from "next/link";
import { CreditCard, QrCode, ArrowUpRight } from "lucide-react";

export function PaymentConnectionGuide({preference="later"}:{preference?:string}) {
  return <section aria-labelledby="goods-payments" className="mt-8 rounded-3xl border border-neutral-200 bg-neutral-50 p-5 sm:p-7">
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 id="goods-payments" className="text-xl font-semibold">Оплата товаров</h2><span className="rounded-full border bg-white px-3 py-1 text-xs">Онлайн-оплата не подключена</span></div>
    <p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-600">Деньги покупателей должны поступать на счёт вашего бизнеса. Оплата подписки Dukenim — отдельная операция.</p>
    {preference!=="later"&&<p className="mt-3 text-sm">При создании магазина выбран {({freedompay:"FreedomPay",halyk:"Halyk ePay",kaspi:"Kaspi Pay"} as Record<string,string>)[preference]??"провайдер"}. Это сохранённое пожелание, не активная оплата.</p>}
    <div className="mt-5 grid gap-4 lg:grid-cols-3">
      <article className="rounded-2xl border border-neutral-200 bg-white p-5"><CreditCard aria-hidden="true" size={26}/><h3 className="mt-4 font-semibold">FreedomPay · карты</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Платёжная страница с суммой заказа в тенге и возвратом на сайт. Для подключения ваш бизнес проходит оформление у провайдера; деньги не собираются на счёте Dukenim.</p><a className="mt-4 block text-sm font-semibold underline" href="https://freedompay.kz/" target="_blank" rel="noopener noreferrer">Официальный сайт и подключение ↗</a><Link className="mt-4 block text-sm underline" href="/admin/requests?source=integrations&intent=freedompay">Подготовить подключение с поддержкой</Link></article>
      <article className="rounded-2xl border border-neutral-200 bg-white p-5"><CreditCard aria-hidden="true" size={26}/><h3 className="mt-4 font-semibold">Банковские карты</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Интернет-эквайринг с суммой заказа на защищённой платёжной странице. Возможный провайдер — Halyk ePay. Подключение требует заявки и одобрения банка.</p><a className="mt-4 inline-flex items-center gap-1 text-sm font-semibold underline underline-offset-4" href="https://halykbank.kz/business/payment/epay" target="_blank" rel="noopener noreferrer">Условия и заявка ePay <ArrowUpRight size={15}/></a><Link className="mt-4 block text-sm underline underline-offset-4" href="/admin/requests?source=integrations&intent=card-payments">Уже есть эквайринг? Написать в поддержку</Link></article>
      <article className="rounded-2xl border border-neutral-200 bg-white p-5"><QrCode aria-hidden="true" size={26}/><h3 className="mt-4 font-semibold">Kaspi Pay</h3><p className="mt-2 text-sm leading-6 text-neutral-600">Обычная платёжная ссылка требует ручного ввода суммы. Точная сумма корзины и автоматическое подтверждение требуют согласованной интеграции с Kaspi, а не добавления параметра к ссылке.</p><a className="mt-4 inline-flex items-center gap-1 text-sm font-semibold underline underline-offset-4" href="https://guide.kaspi.kz/partner/ru/payments/distributor/connection/q4389" target="_blank" rel="noopener noreferrer">Официальный порядок обращения <ArrowUpRight size={15}/></a><Link className="mt-4 block text-sm underline underline-offset-4" href="/admin/requests?source=integrations&intent=kaspi-payments">Обсудить подключение Kaspi</Link></article>
    </div>
    <ol className="mt-6 grid list-inside list-decimal gap-3 text-sm leading-6 sm:grid-cols-3"><li>Откройте свой аккаунт у провайдера.</li><li>Согласуйте подключение с поддержкой Dukenim. Не отправляйте ключи и пароли в чат.</li><li>После разработки интеграции проверим сумму, подтверждение и возврат. Только затем включим оплату.</li></ol>
    <p className="mt-4 text-xs leading-5 text-neutral-500">Пока эти способы не активны в кассе. Переход по ссылке и возвращение на сайт не являются подтверждением оплаты.</p>
  </section>;
}
