import{productAnalyticsCollectionEnabled,syntheticAnalyticsFixture}from"@/lib/product-analytics-pipeline";

export function ProductAnalyticsPanel(){
  const collectionEnabled=productAnalyticsCollectionEnabled();
  const prototype=syntheticAnalyticsFixture().snapshot("merchant.analytics");
  return <section className="card mt-6 p-6" aria-labelledby="product-analytics-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-widest text-neutral-500">Product analytics prototype</p><h2 id="product-analytics-title" className="mt-2 text-xl font-semibold">Путь пользователя и карта действий</h2></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-900">Сбор реальных событий выключен</span></div>
    <p className="mt-3 max-w-3xl text-sm leading-6 text-neutral-600">Ниже — локальный прототип только на синтетических событиях. В продукте нет endpoint для приёма реальных действий, стороннего analytics SDK, постоянного хранилища или фоновой отправки.</p>
    {collectionEnabled&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">Флаг окружения включён, но ingestion намеренно не смонтирован. Реальные события всё равно не принимаются.</p>}
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-neutral-200 p-4"><small className="text-neutral-500">Синтетические сессии</small><b className="mt-2 block text-lg">{prototype.sessions}</b></div><div className="rounded-2xl border border-neutral-200 p-4"><small className="text-neutral-500">Просмотры экрана</small><b className="mt-2 block text-lg">{prototype.screenViews}</b></div><div className="rounded-2xl border border-neutral-200 p-4"><small className="text-neutral-500">Действия</small><b className="mt-2 block text-lg">{prototype.actions}</b></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-neutral-200 p-4"><h3 className="font-semibold">Прототип воронки</h3><p className="mt-2 text-sm text-neutral-500">Фиксированный локальный сценарий для проверки композиции будущего отчёта.</p><div className="mt-4 space-y-2">{["Создание магазина","Оформление","Первый товар","Предпросмотр","Публикация"].map((step,index)=><div key={step} className="flex items-center gap-3 text-sm"><span className="grid size-7 place-items-center rounded-full bg-neutral-100">{index+1}</span><span>{step}</span><span className="ml-auto text-neutral-400">demo</span></div>)}</div></div>
    <div className="rounded-2xl border border-neutral-200 p-4"><h3 className="font-semibold">Синтетическая heatmap</h3><p className="mt-2 text-sm text-neutral-500">Нормализованная сетка 0–1000; не данные клиентов.</p><div className="mt-4 grid aspect-[5/4] grid-cols-5 gap-1 rounded-2xl bg-neutral-50 p-2" aria-label="Синтетическая карта действий">{prototype.cells.map(cell=><span key={`${cell.x}-${cell.y}`} title={`${cell.count} synthetic events`} className="rounded-md border border-white/70" style={{backgroundColor:`rgba(128,31,83,${0.04+cell.intensity*0.72})`}}/>)}</div></div></div>
    <p className="mt-5 text-xs leading-5 text-neutral-500">Следующий отдельный этап — privacy/retention review, tenant-scoped storage и server ingestion. До него эта секция не является готовой аналитикой.</p>
  </section>;
}
