import {NextResponse} from "next/server";
import {z} from "zod";
import {getMobileStaff} from "@/lib/mobile-auth";
import {computeEntitlement} from "@/lib/entitlement";
import {createConsultation} from "@/lib/ai/consultation";
import {consultationSchema,type ConsultationTurn} from "@/lib/ai/consultation-schema";
import {getAiStudioStatus} from "@/lib/ai/studio";
const inputSchema=z.object({accessId:z.string().uuid(),message:z.string().trim().min(2).max(800)}).strict();
const headers={"Cache-Control":"private, no-store"};
export async function POST(request:Request){let raw:unknown;try{const length=Number(request.headers.get("content-length")||0);if(length>20_000)return NextResponse.json({error:"Запрос слишком большой."},{status:413,headers});raw=await request.json();}catch{return NextResponse.json({error:"Некорректный запрос."},{status:400,headers});}const input=inputSchema.safeParse(raw);if(!input.success)return NextResponse.json({error:"Введите сообщение от 2 до 800 символов."},{status:400,headers});const context=await getMobileStaff(request,input.data.accessId,"studio","write");if(!context)return NextResponse.json({error:"Владелец не дал доступ к AI Studio."},{status:403,headers});const tenantId=context.member.tenant_id;const{data:tenant}=await context.admin.from("tenants").select("id,name,business_vertical,catalog_status,plan,next_plan,status,trial_ends_at").eq("id",tenantId).maybeSingle();if(!tenant||!computeEntitlement(tenant).active)return NextResponse.json({error:"AI Studio недоступна на текущем тарифе."},{status:403,headers});if(!getAiStudioStatus().configured)return NextResponse.json({error:"AI Studio временно недоступна."},{status:503,headers});const recent=await context.admin.from("ai_studio_generations").select("id,input_summary,output").eq("tenant_id",tenantId).eq("intent","consultation").order("created_at",{ascending:false}).limit(12);if(recent.error)return NextResponse.json({error:"Не удалось восстановить контекст."},{status:503,headers});const history:ConsultationTurn[]=[];for(const row of(recent.data??[]).reverse()){const parsed=consultationSchema.safeParse(row.output);if(parsed.success)history.push({id:row.id,message:row.input_summary,response:parsed.data});}const rpc=context.admin as unknown as{rpc:(name:string,args:Record<string,unknown>)=>Promise<{error:unknown}>};const reserved=await rpc.rpc("reserve_ai_credits",{p_tenant_id:tenantId,p_cost:1,p_monthly_allotment:120});if(reserved.error)return NextResponse.json({error:"Лимит AI недоступен. Обратитесь к владельцу."},{status:429,headers});try{const result=await createConsultation(input.data.message,{...tenant,actor:"Сотрудник: готовит предложения, не публикует магазин",permissions:context.member.permissions},history);if(!await getMobileStaff(request,input.data.accessId,"studio","write"))throw new Error("Access revoked");const saved=await context.admin.from("ai_studio_generations").insert({tenant_id:tenantId,requested_by:context.user.id,intent:"consultation",input_summary:input.data.message,output:result.consultation,model:getAiStudioStatus().deployment,usage:result.usage??{},credit_cost:1}).select("id").single();if(saved.error||!saved.data)throw new Error("save");return NextResponse.json({id:saved.data.id,consultation:result.consultation},{headers});}catch{await rpc.rpc("refund_ai_credits",{p_tenant_id:tenantId,p_cost:1});return NextResponse.json({error:"Ответ не сохранён. Лимит возвращён."},{status:503,headers});}}
