import Link from "next/link";
import {ArrowRight,BarChart3,Boxes,Check,PackageCheck,ShoppingBag,Store} from "lucide-react";
const demoUrl="https://dukenim-new.vercel.app/s/demo-shop";
const rows=[
  {time:"10:42",icon:PackageCheck,title:"Заказ #1048",note:"Готов к выдаче",state:"ГОТОВ"},
  {time:"10:38",icon:Boxes,title:"Остатки обновлены",note:"42 позиции синхронизированы",state:"ТОЧНО"},
  {time:"10:31",icon:ShoppingBag,title:"Продажа в магазине",note:"18 900 ₸",state:"ОПЛАЧЕНО"},
];
const features=[
  ["Витрина", "Каталог, корзина и оформление заказа под брендом вашего магазина.", ShoppingBag],
  ["Операции", "Онлайн- и офлайн-продажи сразу отражаются в заказах и остатках.", Boxes],
  ["Решения", "Выручка, клиенты и популярные товары собраны в ясный обзор.", BarChart3],
] as const;
export default function Home(){return <main className="min-h-[100dvh] overflow-hidden">
  <header className="sticky top-0 z-40 border-b border-black/6 bg-[color:rgb(240_242_238/.92)] backdrop-blur-xl"><div className="container flex h-18 items-center justify-between"><Link href="/" className="flex items-center gap-3 text-lg font-extrabold"><span className="grid size-9 place-items-center rounded-[10px] bg-[var(--accent-dark)] text-[var(--accent-bright)]"><Store size={19}/></span>Dukenim</Link><nav className="flex items-center gap-2"><a href="#system" className="desktop-only px-4 py-2 text-sm font-bold text-[var(--ink-60)]">Возможности</a><Link href={demoUrl} className="desktop-only px-4 py-2 text-sm font-bold text-[var(--ink-60)]">Демо-магазин</Link><Link href="/login" className="btn btn-primary">Войти <ArrowRight size={17}/></Link></nav></div></header>
  <section className="border-b border-black/7"><div className="container grid min-h-[720px] items-center gap-14 py-16 lg:grid-cols-[.88fr_1.12fr] lg:py-20"><div><h1 className="max-w-[760px] text-5xl font-extrabold leading-[.98] tracking-[-.04em] md:text-[78px]">Весь магазин.<br/><span className="text-[var(--accent)]">Один ритм.</span></h1><p className="mt-7 max-w-[58ch] text-lg leading-8 text-[var(--ink-60)]">Dukenim связывает витрину, продажи, склад, заказы и клиентов. Вы видите, что происходит сейчас, и сразу понимаете, что делать дальше.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="btn btn-cta">Открыть кабинет <ArrowRight size={18}/></Link><Link href={demoUrl} className="btn btn-secondary">Посмотреть витрину</Link></div><div className="mt-12 flex flex-wrap gap-x-8 gap-y-3 text-sm font-bold text-[var(--ink-60)]"><span className="flex items-center gap-2"><Check size={17} className="text-[var(--success)]"/>Без программиста</span><span className="flex items-center gap-2"><Check size={17} className="text-[var(--success)]"/>С телефона и компьютера</span></div></div>
    <div className="overflow-hidden rounded-[16px] bg-[var(--accent-dark)] text-white shadow-[var(--shadow-lg)]"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><div><div className="data-label text-white/45">MEREY · ПАНЕЛЬ МАГАЗИНА</div><b className="mt-1 block">Сегодня, 4 августа</b></div><span className="badge bg-[var(--accent-bright)] text-[var(--accent-dark)]"><span className="size-2 rounded-full bg-[var(--accent-dark)]"/>В ЭФИРЕ</span></div><div className="grid sm:grid-cols-[1.15fr_.85fr]"><div className="border-b border-white/10 p-6 sm:border-b-0 sm:border-r"><div className="data-label text-white/45">ВЫРУЧКА СЕГОДНЯ</div><strong className="tabular mt-5 block text-4xl md:text-5xl">284 500 ₸</strong><div className="mt-6 flex h-24 items-end gap-2">{[36,54,42,68,59,82,73,100,88,96,77,91].map((h,i)=><span key={i} className="flex-1 bg-[var(--accent-bright)]/75" style={{height:`${h}%`}}/>)}</div></div><div className="grid grid-cols-2 sm:grid-cols-1"><div className="border-r border-white/10 p-5 sm:border-b sm:border-r-0"><div className="data-label text-white/45">ЗАКАЗЫ</div><b className="tabular mt-3 block text-3xl">18</b><small className="text-white/52">5 ждут сборки</small></div><div className="p-5"><div className="data-label text-white/45">ОСТАТКИ</div><b className="tabular mt-3 block text-3xl">97%</b><small className="text-white/52">данные точны</small></div></div></div><div>{rows.map(({time,icon:Icon,title,note,state})=><div key={title} className="grid grid-cols-[48px_40px_1fr_auto] items-center gap-3 border-t border-white/10 px-5 py-4"><span className="tabular text-xs text-white/38">{time}</span><span className="grid size-9 place-items-center rounded-[9px] bg-white/8 text-[var(--accent-bright)]"><Icon size={17}/></span><div><b className="block text-sm">{title}</b><small className="text-white/45">{note}</small></div><span className="data-label text-[var(--accent-bright)]">{state}</span></div>)}</div></div>
  </div></section>
  <section id="system" className="container py-20 md:py-28"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><h2 className="text-4xl font-extrabold leading-tight md:text-5xl">Не ещё один сайт.<br/>Рабочая система.</h2><p className="mt-5 max-w-md text-lg leading-8 text-[var(--ink-60)]">Покупатель видит аккуратный магазин. Владелец — точную картину бизнеса. Между ними нет ручной сверки.</p></div><div className="border-y border-[var(--line)]">{features.map(([title,text,Icon],i)=><article key={title} className="grid gap-5 border-b border-[var(--line)] py-7 last:border-0 sm:grid-cols-[48px_1fr_64px] sm:items-center"><Icon className="text-[var(--accent)]"/><div><h3 className="text-xl font-extrabold">{title}</h3><p className="mt-2 max-w-xl leading-7 text-[var(--ink-60)]">{text}</p></div><span className="data-label text-right">0{i+1}</span></article>)}</div></div></section>
  <section className="bg-[var(--accent-dark)] py-20 text-white md:py-28"><div className="container grid gap-10 lg:grid-cols-[1fr_1fr] lg:items-center"><div><h2 className="text-4xl font-extrabold leading-tight md:text-6xl">Меньше рутины.<br/>Больше контроля.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/62">Добавили товар, приняли заказ, изменили остаток — Dukenim проводит изменение через всю систему и оставляет понятный след.</p></div><div className="border-y border-white/12">{[["01","Добавьте товар на витрину"],["02","Получите заказ в кабинете"],["03","Продайте — остаток обновится"]].map(([n,t])=><div key={n} className="grid grid-cols-[54px_1fr_auto] items-center border-b border-white/12 py-5 last:border-0"><span className="tabular text-sm text-white/35">{n}</span><b>{t}</b><Check className="text-[var(--accent-bright)]" size={19}/></div>)}</div></div></section>
  <section className="container py-20 md:py-28"><div className="grid overflow-hidden rounded-[16px] bg-[var(--cta)] text-white lg:grid-cols-[1fr_auto]"><div className="p-8 md:p-14"><h2 className="text-4xl font-extrabold md:text-5xl">Торговля уже движется.<br/>Управляйте ею.</h2><p className="mt-5 max-w-xl text-lg leading-8 text-white/82">Единый вход для владельца магазина и администратора платформы.</p></div><div className="flex items-center border-t border-white/18 p-8 lg:border-l lg:border-t-0"><Link href="/login" className="btn bg-white text-[var(--accent-dark)]">Перейти ко входу <ArrowRight size={18}/></Link></div></div></section>
  <footer className="border-t border-[var(--line)] py-8"><div className="container flex flex-wrap items-center justify-between gap-3 text-sm"><b className="flex items-center gap-2"><Store size={16}/>Dukenim</b><span className="text-[var(--ink-60)]">© 2026 · Платформа для современной торговли</span></div></footer>
</main>}
