import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, Check, LayoutDashboard, ShieldCheck, ShoppingBag, Store } from "lucide-react";

const demoUrl = "https://dukenim-new.vercel.app/s/demo-shop";
const capabilities = [
  { icon: ShoppingBag, title: "Своя онлайн-витрина", text: "Каталог, карточки товаров, корзина и оформление заказов под брендом клиента." },
  { icon: LayoutDashboard, title: "Управление магазином", text: "Товары, остатки, заказы и клиенты в одном понятном кабинете." },
  { icon: BarChart3, title: "Продажи и аналитика", text: "Онлайн- и офлайн-продажи, выручка и популярные товары в реальном времени." },
  { icon: ShieldCheck, title: "Надёжное разделение", text: "Каждый клиент видит только свой магазин и управляет только своими данными." },
];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#f6f8f6]">
    <header className="border-b border-black/5 bg-white/90 backdrop-blur"><div className="container flex items-center justify-between py-4"><Link href="/" className="flex items-center gap-3 text-xl font-bold"><span className="grid size-10 place-items-center rounded-xl bg-[var(--accent)] text-white"><Store size={21}/></span>Dukenim</Link><nav className="flex items-center gap-3"><a href="#possibilities" className="desktop-only px-3 text-sm font-semibold text-[var(--ink-60)]">Возможности</a><Link href={demoUrl} className="desktop-only px-3 text-sm font-semibold text-[var(--ink-60)]">Демо-магазин</Link><Link href="/login" className="btn btn-primary">Войти <ArrowRight size={17}/></Link></nav></div></header>

    <section className="relative border-b border-black/5 bg-[#0a4438] py-20 text-white md:py-28"><div className="pointer-events-none absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_75%_30%,#12a87e_0,transparent_34%)]"/><div className="container relative grid items-center gap-14 md:grid-cols-[1.1fr_.9fr]"><div><span className="inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-semibold">Платформа для магазинов Казахстана</span><h1 className="mt-7 max-w-3xl text-5xl font-semibold leading-[1.02] tracking-tight md:text-7xl">Магазин, которым легко управлять</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">Dukenim объединяет онлайн-витрину, товары, склад, заказы, клиентов и аналитику. Изменения в кабинете сразу появляются на сайте магазина.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/login" className="btn bg-white text-[var(--accent-dark)]">Войти в кабинет <ArrowRight size={18}/></Link><Link href={demoUrl} className="btn border-white/20 bg-white/10 text-white">Посмотреть демо</Link></div></div><div className="rounded-[28px] border border-white/15 bg-white/10 p-4 shadow-2xl backdrop-blur"><div className="rounded-2xl bg-[#f7f8f7] p-5 text-[var(--ink)]"><div className="flex items-center justify-between border-b border-[var(--line)] pb-4"><b>Панель магазина</b><span className="badge">Онлайн</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="card p-4"><span className="muted text-xs">Выручка сегодня</span><strong className="mt-2 block text-2xl">284 500 ₸</strong></div><div className="card p-4"><span className="muted text-xs">Новые заказы</span><strong className="mt-2 block text-2xl">18</strong></div></div><div className="card mt-3 p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Boxes size={20}/></span><div><b>Каталог и склад</b><p className="muted text-sm">Все остатки синхронизированы</p></div></div></div></div></div></div></section>

    <section id="possibilities" className="container py-20 md:py-28"><div className="max-w-2xl"><span className="badge">Всё необходимое</span><h2 className="mt-5 text-4xl font-semibold md:text-5xl">Одна система для всей торговли</h2><p className="muted mt-4 text-lg leading-8">Клиент получает собственную витрину и рабочий кабинет. Владелец Dukenim управляет всей платформой через отдельную защищённую панель.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{capabilities.map(({icon:Icon,title,text})=><article key={title} className="card p-7"><span className="grid size-12 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={23}/></span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="muted mt-2 leading-7">{text}</p></article>)}</div></section>
    <section className="border-y border-[var(--line)] bg-white py-20"><div className="container grid gap-10 md:grid-cols-2 md:items-center"><div><span className="badge">Для владельцев магазинов</span><h2 className="mt-5 text-4xl font-semibold">Управление без программиста</h2><p className="muted mt-4 text-lg leading-8">Добавляйте товары и фотографии, меняйте цены, следите за заказами и остатками прямо с телефона.</p></div><div className="space-y-3">{["Изменения сразу видны на витрине","Каждый сотрудник работает только со своим магазином","Заказы покупателей автоматически попадают в кабинет","Данные защищены на уровне базы"].map(item=><div key={item} className="card flex items-center gap-3 p-4"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--accent-soft)] text-[var(--accent)]"><Check size={17}/></span><b>{item}</b></div>)}</div></div></section>
    <section className="container py-20 text-center md:py-28"><h2 className="text-4xl font-semibold md:text-5xl">Ваш бизнес — в одном кабинете</h2><p className="muted mx-auto mt-4 max-w-xl text-lg">Войдите в Dukenim, чтобы управлять магазином или всей платформой.</p><Link href="/login" className="btn btn-primary mt-8">Перейти ко входу <ArrowRight size={18}/></Link></section>
    <footer className="border-t border-[var(--line)] bg-white py-7"><div className="container flex flex-wrap items-center justify-between gap-3 text-sm"><b>Dukenim</b><span className="muted">© 2026 · Платформа для современной торговли</span></div></footer>
  </main>;
}
