"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";import{requireRole}from"@/lib/auth";import{addStockCorrection,createChangeRequest,createMessage,createOfflineSale,createProduct,setProductActive,updateOrderStatus,updateProduct,updateTenantBranding,updateVariant,uploadProductImage}from"@/lib/queries/owner";import type{Database}from"@/types/database";
async function owner(){const context=await requireRole(["owner","superadmin"]);if(!context.tenantId)throw new Error("Магазин не привязан");return{context,client:await createClient()}}
export async function toggleProduct(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await setProductActive(client,context.tenantId!,String(form.get("productId")),String(form.get("active"))!=="true");revalidatePath("/admin/catalog");revalidatePath("/s/[slug]","page")}
export async function createProductAction(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)redirect("/admin/catalog");const{context,client}=await owner();const tenantId=context.tenantId!;const images:string[]=[];for(const value of form.getAll("images")){if(value instanceof File&&value.size){if(value.size>5_000_000||!value.type.startsWith("image/"))throw new Error("Фото должно быть изображением до 5 МБ");const uploaded=await uploadProductImage(client,tenantId,value);if(uploaded.error)throw uploaded.error;if(uploaded.url)images.push(uploaded.url)}}const sizes=form.getAll("size").map(String);const colors=form.getAll("color").map(String);const stocks=form.getAll("stock").map(Number);const skus=form.getAll("sku").map(String);const rows=sizes.map((size,i)=>({size,color:colors[i]??"",stock:Number.isInteger(stocks[i])?stocks[i]:0,sku:skus[i]??""})).filter((v,i)=>i===0||v.size||v.color||v.sku||v.stock>0);const variants=rows.length?rows:[{size:"",color:"",stock:0,sku:""}];const{error}=await createProduct(client,{tenantId,title:String(form.get("title")??""),description:String(form.get("description")??""),price:Number(form.get("price")),oldPrice:form.get("oldPrice")?Number(form.get("oldPrice")):null,categoryId:form.get("categoryId")?String(form.get("categoryId")):null,images,isActive:form.get("isActive")==="on",variants});if(error)throw error;revalidatePath("/admin/catalog");redirect("/admin/catalog")}
export async function offlineSale(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();const{error}=await createOfflineSale(client,context.tenantId!,String(form.get("variantId")),Number(form.get("qty")??1));if(error)throw error;revalidatePath("/admin/stock");revalidatePath("/admin")}
export async function updateProductAction(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)redirect("/admin/catalog");const{context,client}=await owner();const tenantId=context.tenantId!;const productId=String(form.get("productId"));const{error}=await updateProduct(client,tenantId,productId,{title:String(form.get("title")),description:String(form.get("description")??""),price:Number(form.get("price")),old_price:form.get("oldPrice")?Number(form.get("oldPrice")):null,is_active:form.get("isActive")==="on"});if(error)throw error;const ids=form.getAll("variantId").map(String),sizes=form.getAll("size").map(String),colors=form.getAll("color").map(String),skus=form.getAll("sku").map(String),current=form.getAll("currentStock").map(Number),target=form.getAll("stock").map(Number);for(let i=0;i<ids.length;i++){await updateVariant(client,tenantId,ids[i],{size:sizes[i]||null,color:colors[i]||null,sku:skus[i]||null});const delta=target[i]-current[i];if(delta)await addStockCorrection(client,tenantId,ids[i],delta)}revalidatePath("/admin/catalog");revalidatePath("/admin/stock");redirect("/admin/catalog")}
export async function changeOrderStatus(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await updateOrderStatus(client,context.tenantId!,String(form.get("orderId")),String(form.get("status"))as Database["public"]["Enums"]["order_status"]);revalidatePath("/admin/orders")}
export async function sendRequest(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const text=String(form.get("text")??"").trim();if(!text)return;const{context,client}=await owner();await Promise.all([createChangeRequest(client,context.tenantId!,text),createMessage(client,context.tenantId!,text)]);revalidatePath("/admin/requests")}
export async function saveStoreSettings(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await updateTenantBranding(client,context.tenantId!,{name:String(form.get("name")),tagline:String(form.get("tagline")??""),city:String(form.get("city")??""),phone:String(form.get("phone")??""),accent_color:String(form.get("accentColor")??"#0E5C4A")});revalidatePath("/admin");revalidatePath("/s/[slug]","layout")}
