"use server";
import{revalidatePath}from"next/cache";import{redirect}from"next/navigation";import{createClient}from"@/lib/supabase/server";import{requireRole}from"@/lib/auth";import{addStockCorrection,addStockMovement,createChangeRequest,createMessage,createOfflineSale,createProduct,setProductActive,updateOrderStatus,updateProduct,updateTenantBranding,updateTenantPolicies,updateVariant,uploadProductImage,saveStorefrontSettings,saveStorefrontCampaign}from"@/lib/queries/owner";import type{Database}from"@/types/database";import{hasPlan,type Plan}from"@/lib/plans";import{launchTemplatesForPlan,palettes,safeBrandColor,templateCatalog}from"@/lib/storefront-theme";
export type ProductActionState={error?:string};
export type CatalogActionState={error?:string};
export type StockMovementState={error?:string;success?:string};
async function owner(){const context=await requireRole(["owner","superadmin"]);if(!context.tenantId)throw new Error("Магазин не привязан");return{context,client:await createClient()}}
export async function createCatalogAction(_:CatalogActionState,form:FormData):Promise<CatalogActionState>{
if(!process.env.NEXT_PUBLIC_SUPABASE_URL)redirect("/admin/catalog/new");
const catalogName=String(form.get("catalogName")??"").trim();
if(catalogName.length<2)return{error:"Введите название каталога — минимум 2 символа."};
if(catalogName.length>80)return{error:"Название каталога должно быть не длиннее 80 символов."};
const templateKey=String(form.get("templateKey")??""),paletteKey=String(form.get("paletteKey")??"");
if(!palettes.some((item)=>item.key===paletteKey))return{error:"Выберите цветовую палитру для витрины."};
try{const{context,client}=await owner();const tenantResult=await client.from("tenants").select("plan,accent_color").eq("id",context.tenantId!).single();const tenant=tenantResult.data;if(tenantResult.error||!tenant)return{error:"Не удалось определить тариф магазина. Обновите страницу и попробуйте ещё раз."};const plan=tenant.plan as Plan;if(!launchTemplatesForPlan(plan).some((item)=>item.key===templateKey))return{error:"Выбранный шаблон недоступен на вашем тарифе."};const customColor=hasPlan(plan,"standard")?safeBrandColor(String(form.get("brandColor")??""),tenant.accent_color):null;const theme=await saveStorefrontSettings(client,context.tenantId!,{template_key:templateKey,palette_key:paletteKey,brand_color:customColor,hero_title:null,hero_subtitle:null,hero_image_url:null,hero_cta_label:"Смотреть каталог"});if(theme.error)return{error:`Не удалось сохранить оформление: ${theme.error.message}`};const{data,error}=await client.from("tenants").update({catalog_name:catalogName,catalog_status:"building",catalog_created_at:new Date().toISOString()}).eq("id",context.tenantId!).select("id").maybeSingle();if(error||!data)return{error:`Не удалось создать каталог${error?`: ${error.message}`:". Проверьте права доступа и попробуйте ещё раз."}`};}
catch(error){return{error:error instanceof Error?`Не удалось создать каталог: ${error.message}`:"Не удалось создать каталог. Попробуйте ещё раз."}}
revalidatePath("/admin");revalidatePath("/admin/catalog");redirect("/admin/catalog/new")}
export async function toggleProduct(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await setProductActive(client,context.tenantId!,String(form.get("productId")),String(form.get("active"))!=="true");revalidatePath("/admin/catalog");revalidatePath("/s/[slug]","page")}
export async function createProductAction(_:ProductActionState,form:FormData):Promise<ProductActionState>{
if(!process.env.NEXT_PUBLIC_SUPABASE_URL)redirect("/admin/catalog");
try{const title=String(form.get("title")??"").trim(),price=Number(form.get("price")),oldPriceValue=String(form.get("oldPrice")??"").trim(),oldPrice=oldPriceValue?Number(oldPriceValue):null;
if(title.length<2)return{error:"Введите название товара — минимум 2 символа."};
if(!Number.isInteger(price)||price<0)return{error:"Укажите цену товара целым числом в тенге."};
if(oldPrice!==null&&(!Number.isInteger(oldPrice)||oldPrice<price))return{error:"Старая цена должна быть не меньше текущей цены."};
const files=form.getAll("images").filter((value):value is File=>value instanceof File&&value.size>0);
if(files.length>4)return{error:"Можно добавить не более 4 фотографий."};
const{context,client}=await owner(),tenantId=context.tenantId!,images:string[]=[];
const lifecycle=await client.from("tenants").select("catalog_status").eq("id",tenantId).single();
if(lifecycle.error||lifecycle.data?.catalog_status==="not_started")return{error:"Сначала создайте каталог, затем добавляйте товары."};
for(const file of files){if(file.size>5_000_000||!file.type.startsWith("image/"))return{error:"Каждая фотография должна быть изображением размером до 5 МБ."};const uploaded=await uploadProductImage(client,tenantId,file);if(uploaded.error)return{error:`Не удалось загрузить фотографию: ${uploaded.error.message}`};if(uploaded.url)images.push(uploaded.url)}
const sizes=form.getAll("size").map(String),colors=form.getAll("color").map(String),stocks=form.getAll("stock").map(Number),skus=form.getAll("sku").map(String);
const rows=sizes.map((size,i)=>({size,color:colors[i]??"",stock:Number.isInteger(stocks[i])&&stocks[i]>=0?stocks[i]:0,sku:skus[i]??""})).filter((variant,i)=>i===0||variant.size||variant.color||variant.sku||variant.stock>0);
const variants=rows.length?rows:[{size:"",color:"",stock:0,sku:""}];
const{error}=await createProduct(client,{tenantId,title,description:String(form.get("description")??"").trim(),price,oldPrice,categoryId:form.get("categoryId")?String(form.get("categoryId")):null,images,isActive:form.get("isActive")==="on",variants});
if(error)return{error:`Не удалось сохранить товар: ${error.message}`};
const statusUpdate=await client.from("tenants").update({catalog_status:"ready"}).eq("id",tenantId).select("id").maybeSingle();
if(statusUpdate.error||!statusUpdate.data)return{error:"Товар сохранён, но статус каталога не обновился. Обновите страницу и попробуйте ещё раз."};
}catch(error){return{error:error instanceof Error?`Не удалось сохранить товар: ${error.message}`:"Не удалось сохранить товар. Попробуйте ещё раз."}}
revalidatePath("/admin/catalog");revalidatePath("/admin");redirect("/admin/catalog")}
export async function offlineSale(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();const{error}=await createOfflineSale(client,context.tenantId!,String(form.get("variantId")),Number(form.get("qty")??1));if(error)throw error;revalidatePath("/admin/stock");revalidatePath("/admin")}
export async function createStockMovement(_:StockMovementState,form:FormData):Promise<StockMovementState>{
  if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return{error:"Склад временно недоступен."};
  const variantId=String(form.get("variantId")??"");
  const quantity=Number(form.get("quantity")??0);
  const action=String(form.get("action")??"");
  if(!variantId)return{error:"Не удалось определить вариант товара."};
  if(!Number.isInteger(quantity)||quantity<1)return{error:"Укажите целое количество от 1."};
  if(!["restock","writeoff","increase","decrease"].includes(action))return{error:"Выберите действие со складом."};
  const delta=action==="restock"||action==="increase"?quantity:-quantity;
  const reason=action==="restock"?"restock":action==="writeoff"?"writeoff":"correction";
  try{const{context,client}=await owner();const{error}=await addStockMovement(client,context.tenantId!,variantId,delta,reason);if(error)return{error:error.message.includes("Insufficient stock")?"Нельзя списать больше, чем есть в наличии.":`Не удалось обновить остаток: ${error.message}`};}
  catch(error){return{error:error instanceof Error?`Не удалось обновить остаток: ${error.message}`:"Не удалось обновить остаток."}}
  revalidatePath("/admin/stock");revalidatePath("/admin");revalidatePath("/admin/catalog");
  return{success:action==="restock"?"Поступление добавлено в журнал.":action==="writeoff"?"Списание добавлено в журнал.":"Корректировка добавлена в журнал."};
}
export async function updateProductAction(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)redirect("/admin/catalog");const{context,client}=await owner();const tenantId=context.tenantId!;const productId=String(form.get("productId"));const{error}=await updateProduct(client,tenantId,productId,{title:String(form.get("title")),description:String(form.get("description")??""),price:Number(form.get("price")),old_price:form.get("oldPrice")?Number(form.get("oldPrice")):null,is_active:form.get("isActive")==="on"});if(error)throw error;const ids=form.getAll("variantId").map(String),sizes=form.getAll("size").map(String),colors=form.getAll("color").map(String),skus=form.getAll("sku").map(String),current=form.getAll("currentStock").map(Number),target=form.getAll("stock").map(Number);for(let i=0;i<ids.length;i++){await updateVariant(client,tenantId,ids[i],{size:sizes[i]||null,color:colors[i]||null,sku:skus[i]||null});const delta=target[i]-current[i];if(delta)await addStockCorrection(client,tenantId,ids[i],delta)}revalidatePath("/admin/catalog");revalidatePath("/admin/stock");redirect("/admin/catalog")}
export async function changeOrderStatus(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await updateOrderStatus(client,context.tenantId!,String(form.get("orderId")),String(form.get("status"))as Database["public"]["Enums"]["order_status"]);revalidatePath("/admin/orders")}
export async function sendRequest(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const text=String(form.get("text")??"").trim();if(!text)return;const{context,client}=await owner();await Promise.all([createChangeRequest(client,context.tenantId!,text),createMessage(client,context.tenantId!,text)]);revalidatePath("/admin/requests")}
export async function saveStoreSettings(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();await updateTenantBranding(client,context.tenantId!,{name:String(form.get("name")),tagline:String(form.get("tagline")??""),city:String(form.get("city")??""),phone:String(form.get("phone")??""),accent_color:String(form.get("accentColor")??"#0E5C4A")});revalidatePath("/admin");revalidatePath("/s/[slug]","layout")}
export async function saveStorePolicies(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();const delivery=String(form.get("deliveryPolicy")??"").trim(),returns=String(form.get("returnPolicy")??"").trim();if(delivery.length>2000||returns.length>2000)throw new Error("Каждое условие должно быть не длиннее 2000 символов");const{error}=await updateTenantPolicies(client,context.tenantId!,{delivery_policy:delivery||null,return_policy:returns||null});if(error)throw error;revalidatePath("/admin/settings");revalidatePath("/s/[slug]","page")}
export async function saveThemeSettings(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();const tenant=(await client.from("tenants").select("plan,accent_color").eq("id",context.tenantId!).single()).data;if(!tenant)throw new Error("Магазин не найден");const templateKey=String(form.get("templateKey")??"atelier");const template=templateCatalog.find((item)=>item.key===templateKey);if(!template||!hasPlan(tenant.plan as Plan,template.minPlan as Plan))throw new Error("Этот шаблон доступен на тарифе «Бренд»");const paletteKey=String(form.get("paletteKey")??"ink-brass");if(!palettes.some((item)=>item.key===paletteKey))throw new Error("Выберите палитру из списка");const customColor=hasPlan(tenant.plan as Plan,"standard")?safeBrandColor(String(form.get("brandColor")??""),tenant.accent_color):null;const{error}=await saveStorefrontSettings(client,context.tenantId!,{template_key:templateKey,palette_key:paletteKey,brand_color:customColor,hero_title:String(form.get("heroTitle")??"").trim()||null,hero_subtitle:String(form.get("heroSubtitle")??"").trim()||null,hero_image_url:String(form.get("heroImageUrl")??"").trim()||null,hero_cta_label:String(form.get("heroCtaLabel")??"Смотреть каталог").trim().slice(0,40)||"Смотреть каталог"});if(error)throw error;revalidatePath("/admin/settings");revalidatePath("/s/[slug]","layout")}
export async function createCampaign(form:FormData){if(!process.env.NEXT_PUBLIC_SUPABASE_URL)return;const{context,client}=await owner();const tenant=(await client.from("tenants").select("plan").eq("id",context.tenantId!).single()).data;if(!tenant||!hasPlan(tenant.plan as Plan,"standard"))throw new Error("Акции доступны на тарифе «Бренд»");const title=String(form.get("title")??"").trim();if(title.length<2||title.length>90)throw new Error("Заголовок акции должен содержать от 2 до 90 символов");const status=form.get("status")==="published"?"published":"draft";const{error}=await saveStorefrontCampaign(client,context.tenantId!,{title,eyebrow:String(form.get("eyebrow")??"").trim()||null,body:String(form.get("body")??"").trim()||null,cta_label:String(form.get("ctaLabel")??"Смотреть").trim().slice(0,40)||"Смотреть",cta_href:"#catalog",status});if(error)throw error;revalidatePath("/admin/settings");revalidatePath("/s/[slug]","page")}
