import { Image } from "expo-image";
import { StyleSheet, View } from "react-native";
import { AppText as Text } from "@/components/app-text";
import type { MerchantBrandTheme } from "@/components/merchant-brand-theme";
import { mobileApproachForTemplate } from "@/lib/story-placement";

type Neighbor = { title: string; imageUri?: string | null };

export function StoryPlacementPreview({theme,storeName,templateKey,title,assetUri,assetType,heroUri,neighbors=[]}:{theme:MerchantBrandTheme;storeName:string;templateKey?:string|null;title:string;assetUri?:string|null;assetType?:"image"|"video"|null;heroUri?:string|null;neighbors?:Neighbor[]}){
  const approach=mobileApproachForTemplate(templateKey);
  const story=<View style={[s.story,{backgroundColor:theme.surface,borderRadius:approach==="assortment"?16:Math.min(theme.cardRadius,24),width:approach==="assortment"?94:approach==="guided"?116:126,height:approach==="assortment"?122:approach==="guided"?142:158}]}>{assetType==="image"&&assetUri?<Image alt="Предпросмотр истории" source={{uri:assetUri}} contentFit="cover" style={s.image}/>:<Text style={[s.placeholder,{color:theme.accentStrong}]}>{assetType==="video"?"Видео":"Добавьте медиа"}</Text>}<View style={s.shade}/><Text style={s.storyTitle}>{title.trim()||"Заголовок истории"}</Text></View>;
  const hero=<View style={[s.hero,{backgroundColor:theme.surface,borderRadius:theme.cardRadius}]}>{heroUri?<Image alt="Фото витрины" source={{uri:heroUri}} contentFit="cover" style={StyleSheet.absoluteFill}/>:null}<View style={[s.heroShade,{backgroundColor:heroUri?"rgba(20,12,25,.42)":"transparent"}]}/><Text style={[s.eyebrow,{color:heroUri?"white":theme.accentStrong}]}>Витрина магазина</Text><Text style={[s.heroTitle,{color:heroUri?"white":theme.accentStrong}]}>{storeName}</Text></View>;
  const visibleNeighbors=neighbors.slice(0,3);
  return <View accessibilityLabel={`Точное место истории: ${approach}`} style={[s.root,{backgroundColor:theme.background,borderColor:theme.accent,borderRadius:theme.cardRadius}]}>
    <View style={s.header}><Text numberOfLines={1} style={[s.store,{color:theme.accentStrong}]}>{storeName}</Text><View style={[s.cart,{backgroundColor:theme.accent,borderRadius:theme.buttonRadius}]}><Text style={[s.cartText,{color:theme.accentInk}]}>Корзина</Text></View></View>
    <Text style={[s.label,{color:theme.accentStrong}]}>Реальный порядок · {approach==="collection"?"коллекция":approach==="assortment"?"ассортимент":"подбор"}</Text>
    {approach==="collection"&&<>{hero}<View style={s.circles}>{visibleNeighbors.map((item,index)=><View key={`${item.title}-${index}`} style={s.circleItem}>{item.imageUri?<Image alt="" source={{uri:item.imageUri}} contentFit="cover" style={[s.circle,{borderColor:theme.accent}]}/>:<View style={[s.circle,{backgroundColor:theme.surface,borderColor:theme.accent}]}/>}<Text numberOfLines={1} style={[s.circleLabel,{color:theme.accentStrong}]}>{item.title}</Text></View>)}</View><View style={s.rail}>{story}</View><View style={s.catalog}><Text style={[s.section,{color:theme.accentStrong}]}>Каталог</Text><Text style={[s.control,{borderColor:theme.accent,color:theme.accentStrong}]}>Поиск · Фильтры</Text></View></>}
    {approach==="assortment"&&<><View style={s.rail}>{story}</View><View style={s.chips}><Text style={[s.chip,{backgroundColor:theme.accent,color:theme.accentInk}]}>Все</Text>{visibleNeighbors.slice(0,2).map((item,index)=><Text key={`${item.title}-${index}`} numberOfLines={1} style={[s.chip,{maxWidth:112,backgroundColor:theme.surface,color:theme.accentStrong}]}>{item.title}</Text>)}</View><View style={s.catalog}><Text style={[s.section,{color:theme.accentStrong}]}>Меню</Text><Text style={[s.control,{borderColor:theme.accent,color:theme.accentStrong}]}>Поиск · Фильтры</Text></View></>}
    {approach==="guided"&&<>{hero}<View style={s.rail}>{story}</View><Text style={[s.section,{color:theme.accentStrong}]}>Начните с категории</Text><View style={s.guidedGrid}>{visibleNeighbors.slice(0,2).map((item,index)=><View key={`${item.title}-${index}`} style={[s.guidedCard,{backgroundColor:theme.surface,borderRadius:Math.min(theme.cardRadius,18)}]}>{item.imageUri?<Image alt="" source={{uri:item.imageUri}} contentFit="cover" style={s.guidedImage}/>:null}<Text numberOfLines={1} style={[s.guidedLabel,{color:theme.accentStrong}]}>{item.title}</Text></View>)}</View><View style={s.catalog}><Text style={[s.section,{color:theme.accentStrong}]}>Каталог</Text><Text style={[s.control,{borderColor:theme.accent,color:theme.accentStrong}]}>Поиск · Фильтры</Text></View></>}
  </View>;
}

const s=StyleSheet.create({root:{borderWidth:1,padding:14,gap:12},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12},store:{flex:1,fontSize:15,fontWeight:"900"},cart:{paddingHorizontal:13,paddingVertical:9},cartText:{fontSize:11,fontWeight:"900"},label:{fontSize:11,fontWeight:"800",opacity:.72},hero:{height:148,overflow:"hidden",justifyContent:"flex-end",padding:14,gap:4},heroShade:{position:"absolute",top:0,right:0,bottom:0,left:0},eyebrow:{fontSize:10,opacity:.82},heroTitle:{fontSize:20,fontWeight:"900"},rail:{flexDirection:"row"},story:{overflow:"hidden",justifyContent:"center",alignItems:"center"},image:{width:"100%",height:"100%"},placeholder:{fontSize:12,fontWeight:"800"},shade:{position:"absolute",left:0,right:0,bottom:0,height:74,backgroundColor:"rgba(20,12,25,.5)"},storyTitle:{position:"absolute",left:12,right:10,bottom:12,color:"white",fontSize:14,fontWeight:"900"},circles:{flexDirection:"row",gap:12},circleItem:{width:62,alignItems:"center",gap:5},circle:{width:52,height:52,borderRadius:26,borderWidth:2},circleLabel:{width:62,textAlign:"center",fontSize:9,fontWeight:"800"},chips:{flexDirection:"row",gap:7,overflow:"hidden"},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,fontSize:11,fontWeight:"800"},catalog:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},section:{fontSize:13,fontWeight:"900"},control:{borderWidth:1,borderRadius:999,paddingHorizontal:10,paddingVertical:7,fontSize:10},guidedGrid:{flexDirection:"row",gap:8},guidedCard:{flex:1,minWidth:0,overflow:"hidden"},guidedImage:{width:"100%",height:58},guidedLabel:{padding:8,fontSize:10,fontWeight:"800"}});
