"use client";

import {useEffect,useRef,useState} from "react";
import {FoodOptionsEditor} from "@/components/admin/food-options-editor";

const storageKey="dukenim:synthetic-acceptance:v1";
const steps=["logo","palette","type","product","preview"] as const;
type Step=typeof steps[number];
type Draft={step:Step;completed:Step[];brand:{logoName:string|null;background:string;surface:string;accent:string};businessType:string;product?:{name:string;price:string;foodOptions:string}};
const initial:Draft={step:"logo",completed:[],brand:{logoName:"existing-brand.svg",background:"#fff7e8",surface:"#fffdf8",accent:"#ed8b00"},businessType:"Донерная"};

export function AcceptanceClient(){
 const[draft,setDraft]=useState<Draft>(initial);const[ready,setReady]=useState(false);const productForm=useRef<HTMLFormElement>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(storageKey);if(saved)setDraft({...initial,...JSON.parse(saved)});}finally{setReady(true);}},[]);
 const persist=(next:Draft)=>{setDraft(next);localStorage.setItem(storageKey,JSON.stringify(next));};
 const complete=(step:Step,next:Step,patch:Partial<Draft>={})=>persist({...draft,...patch,step:next,completed:Array.from(new Set([...draft.completed,step]))});
 const index=steps.indexOf(draft.step);
 if(!ready)return <p role="status">Загружаем синтетический черновик…</p>;
 return <div className="mx-auto max-w-4xl space-y-6" data-testid="acceptance-root">
  <header className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-orange-700">Synthetic local acceptance</p><h1 className="mt-2 text-3xl font-black">Логотип → палитра → тип → товар → preview</h1><p className="mt-2 text-sm text-neutral-600">Изолированный localStorage backend. Он проверяет браузерные обработчики и сериализацию, но не Supabase/RLS.</p><nav className="mt-5 flex flex-wrap gap-2">{steps.map((step,itemIndex)=>itemIndex<index?<button key={step} type="button" data-step={step} onClick={()=>persist({...draft,step})} className="rounded-full bg-amber-100 px-3 py-2 text-xs font-bold">✓ {step}</button>:itemIndex===index?<strong key={step} data-current-step={step} className="rounded-full bg-[#28170d] px-3 py-2 text-xs text-white">{step}</strong>:<button key={step} type="button" data-future-step={step} disabled className="rounded-full bg-neutral-100 px-3 py-2 text-xs text-neutral-400">{step}</button>)}</nav></header>

  {draft.step==="logo"&&<section data-testid="step-logo" className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Логотип</h2><p className="mt-2 text-sm">Текущий бренд: <b data-testid="current-logo">{draft.brand.logoName??"текстовый знак"}</b>. Пропуск не удаляет его.</p><label className="mt-5 block rounded-2xl border-2 border-dashed p-5 font-bold">Выбрать синтетический логотип<input data-testid="logo-file" className="mt-3 block" type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)persist({...draft,brand:{...draft.brand,logoName:file.name}});}}/></label><div className="mt-5 flex flex-wrap gap-3"><button data-testid="save-logo" disabled={!draft.brand.logoName} className="btn btn-primary" onClick={()=>complete("logo","palette")}>Сохранить логотип</button><button data-testid="skip-logo" className="btn btn-secondary" onClick={()=>complete("logo","palette")}>Продолжить без замены</button></div></section>}
  {draft.step==="palette"&&<section data-testid="step-palette" className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Палитра</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><button data-testid="palette-bulka" className="rounded-2xl border p-5 text-left" style={{background:"#fff7e8"}} onClick={()=>persist({...draft,brand:{...draft.brand,background:"#fff7e8",surface:"#fffdf8",accent:"#ed8b00"}})}><b>Bulka</b><span className="mt-3 block h-10 rounded-xl bg-[#ed8b00]"/></button><button data-testid="palette-berry" className="rounded-2xl border p-5 text-left" style={{background:"#fff5f3"}} onClick={()=>persist({...draft,brand:{...draft.brand,background:"#fff5f3",surface:"#fffdfb",accent:"#9d2141"}})}><b>Berry</b><span className="mt-3 block h-10 rounded-xl bg-[#9d2141]"/></button></div><button data-testid="save-palette" className="btn btn-primary mt-5" onClick={()=>complete("palette","type")}>Сохранить палитру</button></section>}
  {draft.step==="type"&&<section data-testid="step-type" className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Тип бизнеса</h2><label className="mt-5 block font-bold">Формат<input data-testid="business-type" className="input mt-2" value={draft.businessType} onChange={event=>persist({...draft,businessType:event.target.value})}/></label><button data-testid="save-type" disabled={draft.businessType.trim().length<2} className="btn btn-primary mt-5" onClick={()=>complete("type","product")}>Сохранить формат</button></section>}
  {draft.step==="product"&&<section data-testid="step-product" className="rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Первый товар</h2><form ref={productForm} className="mt-5 space-y-4"><label className="block font-bold">Название<input name="productName" data-testid="product-name" defaultValue={draft.product?.name??"Донер классический"} className="input mt-2"/></label><label className="block font-bold">Цена<input name="productPrice" data-testid="product-price" defaultValue={draft.product?.price??"2200"} className="input mt-2" inputMode="numeric"/></label><FoodOptionsEditor key="acceptance-product-options" initial={draft.product?.foodOptions?JSON.parse(draft.product.foodOptions):{nutrition:{weightGrams:350,kcal:0,protein:0,fat:0,carbs:0},ingredients:[],groups:[]}} choices={[{id:"11111111-1111-4111-8111-111111111111",label:"Айран 0,3 л"},{id:"22222222-2222-4222-8222-222222222222",label:"Картофель фри"}]}/><button data-testid="save-product" type="button" className="btn btn-primary" onClick={()=>{const form=new FormData(productForm.current!);complete("product","preview",{product:{name:String(form.get("productName")),price:String(form.get("productPrice")),foodOptions:String(form.get("foodOptions"))}});}}>Сохранить товар</button></form></section>}
  {draft.step==="preview"&&<section data-testid="step-preview" className="overflow-hidden rounded-3xl border bg-white" style={{background:draft.brand.background}}><div className="p-6" style={{background:draft.brand.accent,color:"white"}}><p className="text-xs font-bold uppercase">{draft.brand.logoName}</p><h2 className="mt-3 text-3xl font-black">{draft.businessType}</h2></div><div className="p-6"><article className="rounded-3xl p-5 shadow-sm" style={{background:draft.brand.surface}}><b className="text-xl">{draft.product?.name}</b><p className="mt-2 font-black">{draft.product?.price} ₸</p><button className="mt-4 rounded-full px-5 py-3 font-black text-white" style={{background:draft.brand.accent}}>Добавить</button></article><pre data-testid="persisted-draft" className="mt-5 max-h-48 overflow-auto rounded-xl bg-black p-3 text-xs text-white">{JSON.stringify(draft,null,2)}</pre><button data-testid="reset-acceptance" className="btn btn-secondary mt-5" onClick={()=>{localStorage.removeItem(storageKey);setDraft(initial);}}>Сбросить fixture</button></div></section>}

  <section className="rounded-3xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-black">Комбо без доступных вариантов</h2><FoodOptionsEditor key="acceptance-empty-options" initial={{ingredients:[{id:"seed",name:"Лаваш",removable:false}],groups:[]}} choices={[]}/></section>
 </div>;
}
