"use client";
import { useState } from "react";
import { ArrowRight, LockKeyhole, PackagePlus, Sparkles } from "lucide-react";
type Intent = "hero" | "promotion" | "catalog_copy" | "catalog_structure" | "banner";
type Draft = { eyebrow?: string; title: string; body: string; ctaLabel: string };
type Banner = { imageUrl: string };
type Structure = { sections: Array<{ name: string; description: string }> };
const intents: Array<{ id: Intent; title: string; text: string }> = [
  { id: "hero", title: "Главный блок", text: "Переосмыслить обещание и CTA витрины." },
  { id: "promotion", title: "Акция", text: "Собрать честный черновик кампании." },
  { id: "catalog_copy", title: "Подборка", text: "Описать категорию или сезонный выбор." },
  { id: "catalog_structure", title: "Структура каталога", text: "Собрать разделы под выбранный тип бизнеса." },
  { id: "banner", title: "Рекламный баннер", text: "Создать визуальную основу кампании без товара и текста." },
];
export function AiStudioClient({ enabled, imageEnabled, brand, catalogReady }: { enabled: boolean; imageEnabled: boolean; brand: boolean; catalogReady: boolean }) {
  const [intent, setIntent] = useState<Intent>("catalog_structure"), [brief, setBrief] = useState(""), [pending, setPending] = useState(false), [error, setError] = useState(""), [draft, setDraft] = useState<Draft | null>(null), [structure, setStructure] = useState<Structure | null>(null), [banner, setBanner] = useState<Banner | null>(null);
  async function createDraft() { setPending(true); setError(""); setDraft(null); setStructure(null); setBanner(null); try { const endpoint = intent === "banner" ? "/api/ai-studio/banner" : "/api/ai-studio/draft"; const body = intent === "banner" ? { brief } : { intent, brief }; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setDraft(data.draft ?? null); setStructure(data.structure ?? null); setBanner(data.imageUrl ? { imageUrl: data.imageUrl } : null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось создать результат."); } finally { setPending(false); } }
  if (!catalogReady) return <div className="ai-studio-first-run"><div><span className="data-label">ПЕРВЫЙ ШАГ</span><h2>Сначала создайте каталог</h2><p>Выберите тип бизнеса, основу витрины и добавьте первый товар. После этого AI Studio откроет рабочие инструменты для вашего магазина.</p><a className="btn btn-primary" href="/admin/catalog/create"><PackagePlus size={17}/> Создать каталог <ArrowRight size={17}/></a></div><div className="ai-studio-locked-illustration" aria-hidden="true"><span>КАТАЛОГ</span><i/><i/><i/></div></div>;
  if (!brand) return <div className="ai-studio-lock"><LockKeyhole/><div><b>AI Studio доступен на тарифе «Бренд»</b><p>Инструмент уже виден в рабочем центре, но запуск генерации откроется после выбора тарифа.</p></div><a className="btn btn-primary" href="/admin/plan">Сравнить тарифы <ArrowRight size={17}/></a></div>;
  const canRun = intent === "banner" ? imageEnabled : enabled;
  return <div className="ai-studio-grid"><div className="ai-studio-form">{intents.map((item) => <button key={item.id} onClick={() => setIntent(item.id)} type="button" className={intent === item.id ? "is-selected" : ""}><b>{item.title}</b><span>{item.text}</span></button>)}<label>Опишите ваш бизнес и задачу<textarea value={brief} onChange={(event) => setBrief(event.target.value)} maxLength={800} placeholder="Например: женская одежда, базовые вещи на каждый день, спокойная палитра."/></label><button onClick={createDraft} disabled={!canRun || brief.trim().length < 8 || pending} className="btn btn-primary">{pending ? "AI собирает результат…" : <><Sparkles size={17}/>Создать результат</>}</button>{!canRun && <p className="ai-studio-note">Этот сценарий пока не подключён к серверу.</p>}{error && <p role="alert" className="ai-studio-error">{error} <a href="/admin/requests?source=ai-studio">Нужна помощь человека →</a></p>}</div><aside className="ai-studio-preview"><span className="data-label">ПРЕДПРОСМОТР — НЕ ОПУБЛИКОВАНО</span>{banner ? <><img src={banner.imageUrl} alt="Предпросмотр рекламного баннера" className="ai-studio-banner-preview"/><em>Проверьте изображение и скачайте его перед публикацией.</em></> : structure ? <><h2>Структура каталога</h2><div className="ai-studio-structure-list">{structure.sections.map((section) => <div key={section.name}><b>{section.name}</b><p>{section.description}</p></div>)}</div><em>Проверьте разделы и перенесите подходящие в каталог вручную.</em></> : draft ? <><small>{draft.eyebrow}</small><h2>{draft.title}</h2><p>{draft.body}</p><button type="button">{draft.ctaLabel}</button><em>Сначала проверьте текст, затем вручную перенесите его в настройки витрины или акцию.</em></> : <><h2>Ваш результат появится здесь.</h2><p>AI подготовит черновик, который вы проверите перед публикацией.</p></>}</aside></div>;
}
