"use client";
import { useState } from "react";
import Image from "next/image";
import { ArrowRight, LockKeyhole, PackagePlus, Sparkles } from "lucide-react";
type Intent = "hero" | "promotion" | "catalog_copy" | "catalog_structure" | "banner";
type Draft = { eyebrow?: string; title: string; body: string; ctaLabel: string };
type Banner = { imageUrl: string; generationId: string };
type Structure = { sections: Array<{ name: string; description: string }> };
const intents: Array<{ id: Intent; title: string; text: string }> = [
  { id: "hero", title: "Главный блок", text: "Переосмыслить обещание и CTA витрины." },
  { id: "promotion", title: "Акция", text: "Собрать честный черновик кампании." },
  { id: "catalog_copy", title: "Подборка", text: "Описать категорию или сезонный выбор." },
  { id: "catalog_structure", title: "Структура каталога", text: "Собрать разделы под выбранный тип бизнеса." },
  { id: "banner", title: "Рекламный баннер · Бренд", text: "Создать визуальную основу кампании без товара и текста." },
];
export function AiStudioClient({ enabled, imageEnabled, brand, catalogStatus }: { enabled: boolean; imageEnabled: boolean; brand: boolean; catalogStatus: "not_started" | "building" | "ready" }) {
  const [intent, setIntent] = useState<Intent>("catalog_structure"), [brief, setBrief] = useState(""), [pending, setPending] = useState(false), [purchasePending, setPurchasePending] = useState(false), [campaignPending, setCampaignPending] = useState(false), [campaignId, setCampaignId] = useState<string | null>(null), [error, setError] = useState(""), [draft, setDraft] = useState<Draft | null>(null), [structure, setStructure] = useState<Structure | null>(null), [banner, setBanner] = useState<Banner | null>(null), [creditsRemaining, setCreditsRemaining] = useState<number | null>(null);
  async function createDraft() { setPending(true); setError(""); setDraft(null); setStructure(null); setBanner(null); setCampaignId(null); try { const endpoint = intent === "banner" ? "/api/ai-studio/banner" : "/api/ai-studio/draft"; const body = intent === "banner" ? { brief } : { intent, brief }; const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { if (data.needsTopup) setCreditsRemaining(0); throw new Error(data.error); } setDraft(data.draft ?? null); setStructure(data.structure ?? null); setBanner(data.imageUrl && data.generationId ? { imageUrl: data.imageUrl, generationId: data.generationId } : null); if (typeof data.creditsRemaining === "number") setCreditsRemaining(data.creditsRemaining); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось создать результат."); } finally { setPending(false); } }
  async function buyCredits() { setPurchasePending(true); setError(""); try { const response = await fetch("/api/polar/ai-credits", { method: "POST" }); const data = await response.json(); if (!response.ok || !data.url) throw new Error(data.error ?? "Не удалось открыть оплату."); window.location.assign(data.url); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось открыть оплату."); setPurchasePending(false); } }
  async function addBannerToCampaigns() { if (!banner) return; setCampaignPending(true); setError(""); try { const response = await fetch("/api/ai-studio/banner/campaign", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ generationId: banner.generationId }) }); const data = await response.json(); if (!response.ok || !data.campaignId) throw new Error(data.error ?? "Не удалось создать кампанию."); setCampaignId(data.campaignId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось создать кампанию."); } finally { setCampaignPending(false); } }
  if (catalogStatus !== "ready") {
    const building = catalogStatus === "building";
    return <div className="ai-studio-first-run"><div><span className="data-label">ПЕРВЫЙ ШАГ</span><h2>{building ? "Добавьте первый товар" : "Сначала создайте каталог"}</h2><p>{building ? "Основа каталога уже готова. Добавьте название, цену, остаток и фотографию первого товара — после сохранения AI Studio откроет рабочие инструменты." : "Выберите тип бизнеса и основу витрины. Затем добавьте первый товар — после этого AI Studio откроет рабочие инструменты вашего магазина."}</p><a className="btn btn-primary" href={building ? "/admin/catalog/new" : "/admin/catalog/create"}><PackagePlus size={17}/> {building ? "Добавить первый товар" : "Создать каталог"} <ArrowRight size={17}/></a></div><div className="ai-studio-locked-illustration" aria-hidden="true"><span>{building ? "ПЕРВЫЙ ТОВАР" : "КАТАЛОГ"}</span><i/><i/><i/></div></div>;
  }
  const canRun = intent === "banner" ? imageEnabled : enabled;
  const unavailable = intent === "banner" && !brand
    ? <><LockKeyhole size={16}/> Баннеры входят в тариф «Бренд». Тексты и структура каталога доступны уже сейчас.</>
    : "Этот сценарий пока не подключён к серверу.";
  const supportHref = `/admin/requests?source=ai-studio&intent=${intent}`;
  return <div className="ai-studio-grid"><div className="ai-studio-form">{intents.map((item) => <button key={item.id} onClick={() => setIntent(item.id)} type="button" className={intent === item.id ? "is-selected" : ""}><b>{item.title}</b><span>{item.text}</span></button>)}<label>Опишите ваш бизнес и задачу<textarea value={brief} onChange={(event) => setBrief(event.target.value)} maxLength={800} placeholder="Например: женская одежда, базовые вещи на каждый день, спокойная палитра."/></label><button onClick={createDraft} disabled={!canRun || brief.trim().length < 8 || pending} className="btn btn-primary">{pending ? "AI собирает результат…" : <><Sparkles size={17}/>Создать результат</>}</button>{!canRun && <p className="ai-studio-note">{unavailable}</p>}{creditsRemaining !== null && creditsRemaining <= 20 && <div className="ai-studio-credit-warning"><span>Осталось AI-кредитов: <b>{creditsRemaining}</b></span><button type="button" onClick={buyCredits} disabled={purchasePending}>{purchasePending ? "Открываем оплату…" : "Добавить 100 кредитов"}</button></div>}{error && <p role="alert" className="ai-studio-error">{error} <a href={supportHref}>Нужна помощь человека →</a></p>}</div><aside className="ai-studio-preview"><span className="data-label">ПРЕДПРОСМОТР — НЕ ОПУБЛИКОВАНО</span>{banner ? <><Image unoptimized width={1600} height={900} src={banner.imageUrl} alt="Предпросмотр рекламного баннера" className="ai-studio-banner-preview"/><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={addBannerToCampaigns} disabled={campaignPending || Boolean(campaignId)} className="btn btn-primary">{campaignPending ? "Создаём черновик…" : campaignId ? "Черновик создан" : "Добавить в кампании"}</button><a href={banner.imageUrl} target="_blank" rel="noopener noreferrer" className="btn btn-secondary">Открыть изображение <ArrowRight size={16}/></a></div>{campaignId && <a href="/admin/settings#campaigns" className="mt-3 inline-flex text-sm font-bold text-[var(--accent)]">Настроить и опубликовать кампанию →</a>}<em>Проверьте изображение и текст кампании перед публикацией.</em></> : structure ? <><h2>Структура каталога</h2><div className="ai-studio-structure-list">{structure.sections.map((section) => <div key={section.name}><b>{section.name}</b><p>{section.description}</p></div>)}</div><em>Проверьте разделы и перенесите подходящие в каталог вручную.</em></> : draft ? <><small>{draft.eyebrow}</small><h2>{draft.title}</h2><p>{draft.body}</p><button type="button">{draft.ctaLabel}</button><em>Сначала проверьте текст, затем вручную перенесите его в настройки витрины или акцию.</em></> : <><h2>Ваш результат появится здесь.</h2><p>AI подготовит черновик, который вы проверите перед публикацией.</p></>}</aside></div>;
}
