import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { getStorefrontCampaigns,getTenant } from "@/lib/queries/owner";
import { createCampaign,updateCampaign } from "@/app/admin/actions";
import { hasPlan,type Plan } from "@/lib/plans";
import { computeEntitlement } from "@/lib/entitlement";
import { campaignDateTimeInput, campaignHorizons, campaignIdeaBrief, campaignMonthLabel, getCampaignPlanningMonths, normalizeCampaignHorizon } from "@/lib/campaign-calendar";
export default async function Campaigns({searchParams}:{searchParams:Promise<{horizon?:string;idea?:string}>}){
 const params=await searchParams;
 const {tenantId}=await requireRole(["owner","superadmin"]);
 const client=await createClient();const tenant=(await getTenant(client,tenantId!)).data;
 if(!tenant)return null;
 const entitlement=computeEntitlement(tenant);
 const plan=entitlement.plan as Plan;
 const canManage=entitlement.active&&hasPlan(plan,"standard");
 const campaigns=canManage?(await getStorefrontCampaigns(client,tenantId!)).data??[]:[];
 const horizon=normalizeCampaignHorizon(params.horizon);
 const planningMonths=getCampaignPlanningMonths(horizon,tenant.business_vertical);
 const selectedIdea=planningMonths.find(idea=>idea.key===params.idea);
 const aiHref=selectedIdea?`/admin/ai-studio?intent=promotion&brief=${encodeURIComponent(campaignIdeaBrief(tenant.catalog_name??tenant.name,selectedIdea))}`:null;
 const dateInput=campaignDateTimeInput;
 const dateFields=(startsAt:string|null=null,endsAt:string|null=null)=><><label className="text-xs font-bold">Начало показа<input type="datetime-local" name="startsAt" className="input mt-1" defaultValue={dateInput(startsAt)}/></label><label className="text-xs font-bold">Окончание показа<input type="datetime-local" name="endsAt" className="input mt-1" defaultValue={dateInput(endsAt)}/></label></>;
 return <section id="campaigns" className="card scroll-mt-24 p-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-xl font-bold">Акции и кампании</h2><p className="muted mt-1 text-sm">Сохраните предложение, задайте даты, проверьте его и подтвердите публикацию сами.</p></div>{canManage&&<b className="badge">{campaigns.length}</b>}</div>{canManage?<>
 <div className="mt-5 rounded-2xl border border-[var(--line)] bg-[var(--surface-2)] p-4"><p className="data-label">ПЛАН АКЦИЙ ПО МЕСЯЦАМ · ТАРИФ «КАТАЛОГ»</p><h3 className="mt-1 text-lg font-bold">Выберите горизонт</h3><p className="muted mt-1 text-sm">Темы — идеи для планирования по вашему сегменту, не официальный календарь праздников.</p><div className="mt-3 flex flex-wrap gap-2">{campaignHorizons.map(value=><Link key={value} aria-current={horizon===value?"true":undefined} href={`/admin/catalog/campaigns?horizon=${value}#campaigns`} className={`btn ${horizon===value?"btn-primary":"btn-secondary"}`}>{value} {value===1?"месяц":value<5?"месяца":"месяцев"}</Link>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">{planningMonths.map(idea=><article key={idea.key} className={`rounded-xl border p-4 ${selectedIdea?.key===idea.key?"border-[var(--accent)] bg-[var(--accent-soft)]":"border-[var(--line)] bg-white"}`}><p className="data-label">{campaignMonthLabel(idea.key)}</p><h4 className="mt-1 font-bold">{idea.title}</h4><p className="muted mt-1 text-sm">{idea.subtitle}</p><p className="muted mt-2 text-xs">{idea.startsAt} — {idea.endsAt}</p><Link href={`/admin/catalog/campaigns?horizon=${horizon}&idea=${idea.key}#campaign-builder`} className="mt-3 inline-flex text-sm font-bold text-[var(--accent)]">Добавить тему в черновик →</Link></article>)}</div>{selectedIdea&&aiHref&&<p className="mt-3 rounded-xl bg-[var(--accent-soft)] p-3 text-sm">Тема и период выбраны. <Link className="font-bold underline" href={aiHref}>Подготовить текст с AI</Link> — это откроет редактируемый вариант, он не сохранится и не опубликуется без вашего решения.</p>}</div>
 <details id="campaign-builder" open={Boolean(selectedIdea)} className="mt-5"><summary className="btn btn-secondary cursor-pointer">+ Добавить акцию</summary><form action={createCampaign} className="mt-5 grid gap-3 md:grid-cols-2"><input name="title" required minLength={2} maxLength={90} className="input" placeholder="Название предложения" defaultValue={selectedIdea?.title}/><input name="eyebrow" maxLength={40} className="input" placeholder="Короткая метка · необязательно" defaultValue={selectedIdea?campaignMonthLabel(selectedIdea.key):""}/><input name="body" maxLength={300} className="input md:col-span-2" placeholder="Что получает покупатель и на каких условиях"/><input name="ctaLabel" maxLength={40} className="input" placeholder="Текст кнопки · Смотреть"/>{dateFields(selectedIdea?`${selectedIdea.startsAt}T00:00`:null,selectedIdea?`${selectedIdea.endsAt}T23:59`:null)}<p className="muted text-xs md:col-span-2">Сохранение создаст черновик. Перед публикацией проверьте даты, товары и условия. Публикует только владелец.</p><button className="btn btn-primary w-fit">Сохранить черновик</button></form></details>
 <div className="mt-7 space-y-4">{campaigns.map((campaign)=><form key={campaign.id} action={updateCampaign} className="rounded-[var(--r-card)] border border-[var(--line)] bg-[var(--surface-2)] p-4"><input type="hidden" name="campaignId" value={campaign.id}/><div className="grid gap-4 md:grid-cols-[150px_1fr]"><div className="min-h-28 rounded-xl bg-[var(--accent-soft)] bg-cover bg-center" style={campaign.image_url?.startsWith("https://")?{backgroundImage:`url(${campaign.image_url})`}:undefined}/><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">Заголовок<input name="title" required minLength={2} maxLength={90} className="input mt-1" defaultValue={campaign.title}/></label><label className="text-xs font-bold">Метка<input name="eyebrow" maxLength={40} className="input mt-1" defaultValue={campaign.eyebrow??""}/></label><label className="text-xs font-bold md:col-span-2">Описание<input name="body" maxLength={300} className="input mt-1" defaultValue={campaign.body??""}/></label><label className="text-xs font-bold">Текст кнопки<input name="ctaLabel" maxLength={40} className="input mt-1" defaultValue={campaign.cta_label}/></label><label className="text-xs font-bold">Статус<select name="status" className="input mt-1" defaultValue={campaign.status}><option value="draft">Черновик</option><option value="published">Опубликована</option><option value="archived">В архиве</option></select></label>{dateFields(campaign.starts_at,campaign.ends_at)}</div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs font-bold text-[var(--ink-60)]">{campaign.ai_generation_id?"Создано с помощью AI":"Создано вручную"} · {campaign.status==="published"?"покупателям показывается в заданный период":campaign.status==="archived"?"скрыто в архиве":"черновик не опубликован"}</span><button className="btn btn-secondary text-sm">Сохранить изменения</button></div></form>)}{!campaigns.length&&<p className="muted rounded-xl border border-dashed border-[var(--line)] p-5 text-sm">Акций пока нет. Сохраните первую как черновик.</p>}</div></>:<p className="mt-5 text-sm font-bold text-[var(--accent)]">Пробный доступ завершён. Подключите тариф «Каталог», чтобы продолжить работу со всеми функциями магазина.</p>}</section>;
}
