import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors, money } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Order={status:string;payment_status:string;total:number;created_at:string};
export default function Analytics(){const{store,loading}=useOwnerStore();const[orders,setOrders]=useState<Order[]>([]);const[message,setMessage]=useState("");const load=useCallback(async()=>{if(!store||!supabase)return;const since=new Date(Date.now()-30*86400000).toISOString();const{data,error}=await supabase.from("orders").select("status,payment_status,total,created_at").eq("tenant_id",store.id).gte("created_at",since);if(error)setMessage("Не удалось загрузить аналитику.");else setOrders((data??[]) as Order[]);},[store]);useEffect(()=>{void load();},[load]);const stats=useMemo(()=>{const completed=orders.filter(o=>o.payment_status==="paid"&&!(["cancelled"].includes(o.status)));const revenue=completed.reduce((s,o)=>s+o.total,0);return{orders:orders.length,revenue,avg:completed.length?Math.round(revenue/completed.length):0,newOrders:orders.filter(o=>o.status==="new").length,done:orders.filter(o=>o.status==="done").length};},[orders]);return <AppScreen section="Аналитика" store={store?.name}><Text style={ui.title}>Последние 30 дней</Text><Text style={ui.subtitle}>Деньги считаются только по заказам, отмеченным магазином как оплаченные. Это управленческий показатель, не банковская сверка.</Text>{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<View style={s.hero}><Text style={s.heroLabel}>ОПЛАЧЕННЫЕ ЗАКАЗЫ</Text><Text style={s.heroNumber}>{money(stats.revenue)}</Text><Text style={s.heroMeta}>{stats.orders} заказов за период</Text></View><View style={s.grid}><Metric label="Средний чек" value={money(stats.avg)}/><Metric label="Новые" value={String(stats.newOrders)}/><Metric label="Завершены" value={String(stats.done)}/><Metric label="Конверсия статуса" value={stats.orders?`${Math.round(stats.done/stats.orders*100)}%`:"0%"}/></View></AppScreen>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.value}>{value}</Text><Text style={s.label}>{label}</Text></View>}
const s=StyleSheet.create({hero:{borderRadius:22,backgroundColor:colors.navyDark,padding:22,gap:7},heroLabel:{color:"#BDD0DC",fontSize:10,fontWeight:"900",letterSpacing:1.3},heroNumber:{color:"white",fontSize:31,fontWeight:"900"},heroMeta:{color:"#D7E3E9"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},metric:{width:"48%",minHeight:104,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:16,backgroundColor:"white",justifyContent:"center"},value:{fontSize:20,fontWeight:"900",color:colors.ink},label:{marginTop:6,color:colors.muted,fontSize:12}});
