import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import * as Linking from "expo-linking";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
import { workspaceRoute } from "@/lib/owner";
export default function AuthCallback(){const url=Linking.useURL();const[ready,setReady]=useState(false);const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[pending,setPending]=useState(false);useEffect(()=>{const client=supabase;if(!client)return;const complete=async()=>{const current=await client.auth.getSession();if(current.data.session){setReady(true);return;}if(!url)return;const parsed=Linking.parse(url);const code=typeof parsed.queryParams?.code==="string"?parsed.queryParams.code:"";if(code){const{error}=await client.auth.exchangeCodeForSession(code);if(!error)setReady(true);return;}const fragment=url.includes("#")?new URLSearchParams(url.split("#")[1]):null;const access=fragment?.get("access_token"),refresh=fragment?.get("refresh_token");if(access&&refresh){const{error}=await client.auth.setSession({access_token:access,refresh_token:refresh});if(!error)setReady(true);}};void complete();},[url]);const save=async()=>{if(!supabase||password.length<10||password!==confirm){Alert.alert("Проверьте пароль","Нужно не меньше 10 символов; оба поля должны совпадать.");return;}setPending(true);const{error}=await supabase.auth.updateUser({password});setPending(false);if(error)Alert.alert("Пароль не изменён","Запросите новую ссылку восстановления.");else{Alert.alert("Пароль обновлён");router.replace(await workspaceRoute() as never);}};return <SafeAreaView style={s.page}>{!ready?<View style={s.center}><ActivityIndicator color={colors.navy}/><Text style={s.copy}>Проверяем защищённую ссылку…</Text><Pressable onPress={()=>router.replace("/")}><Text style={s.back}>Вернуться ко входу</Text></Pressable></View>:<View style={s.center}><Text style={s.title}>Новый пароль</Text><Text style={s.copy}>Задайте пароль для входа на сайте и в приложении.</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Минимум 10 символов" style={s.input}/><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry placeholder="Повторите пароль" style={s.input}/><Pressable disabled={pending} onPress={()=>void save()} style={s.button}><Text style={s.buttonText}>Сохранить пароль</Text></Pressable></View>}</SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"white",padding:24},center:{flex:1,justifyContent:"center",gap:16},title:{fontSize:34,fontWeight:"900",color:colors.ink},copy:{color:colors.muted,fontSize:15,lineHeight:22,textAlign:"center"},back:{color:colors.navy,fontWeight:"900",textAlign:"center"},input:{minHeight:54,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,fontSize:16},button:{minHeight:54,borderRadius:14,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},buttonText:{color:"white",fontWeight:"900"}});
