import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors, money } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Customer={id:string;name:string|null;phone:string;orders_count:number;total_spent:number;last_order:string|null};
export default function Customers(){const{store,loading}=useOwnerStore();const[rows,setRows]=useState<Customer[]>([]);const[query,setQuery]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error}=await supabase.from("customers").select("id,name,phone,orders_count,total_spent,last_order").eq("tenant_id",store.id).order("last_order",{ascending:false});if(error)setMessage("Не удалось загрузить клиентов.");else setRows((data??[]) as Customer[]);},[store]);useEffect(()=>{void load();},[load]);const visible=useMemo(()=>rows.filter(row=>`${row.name??""} ${row.phone}`.toLowerCase().includes(query.trim().toLowerCase())),[rows,query]);return <AppScreen section="Клиенты" store={store?.name}><Text style={ui.title}>Клиенты</Text><Text style={ui.subtitle}>История формируется из заказов магазина и синхронизируется с сайтом.</Text><TextInput value={query} onChangeText={setQuery} placeholder="Имя или телефон" keyboardType="default" style={ui.input}/>{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<View style={s.summary}><View><Text style={s.number}>{rows.length}</Text><Text style={s.label}>клиентов</Text></View><View><Text style={s.number}>{money(rows.reduce((sum,row)=>sum+row.total_spent,0))}</Text><Text style={s.label}>сумма заказов</Text></View></View><View style={{gap:10}}>{visible.map(row=><View key={row.id} style={ui.card}><View style={s.top}><View><Text style={s.name}>{row.name||"Покупатель"}</Text><Text style={s.phone}>{row.phone}</Text></View><Text style={s.spent}>{money(row.total_spent)}</Text></View><Text style={s.meta}>{row.orders_count} заказов{row.last_order?` · последний ${new Date(row.last_order).toLocaleDateString("ru-RU")}`:""}</Text></View>)}</View>{!loading&&!visible.length?<Text style={ui.subtitle}>Клиентов пока нет.</Text>:null}</AppScreen>}
const s=StyleSheet.create({summary:{flexDirection:"row",gap:26,borderRadius:20,backgroundColor:colors.navyDark,padding:18},number:{color:"white",fontSize:20,fontWeight:"900"},label:{color:"#BDD0DC",fontSize:11,marginTop:3},top:{flexDirection:"row",justifyContent:"space-between",gap:10},name:{fontWeight:"900",fontSize:17,color:colors.ink},phone:{color:colors.muted,marginTop:4},spent:{fontWeight:"900",color:colors.navyDark},meta:{color:colors.muted,fontSize:12}});
