import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Location={address?:string;map_2gis?:string;map_yandex?:string};
type Settings={delivery_enabled:boolean;pickup_enabled:boolean;kaspi_remote_enabled:boolean;kaspi_remote_link:string|null;pickup_location:Location|null};
const validMap=(value:string,service:"2gis"|"yandex")=>{if(!value)return true;try{const url=new URL(value);return url.protocol==="https:"&&(service==="2gis"?(url.hostname==="2gis.kz"||url.hostname.endsWith(".2gis.kz")||url.hostname==="2gis.com"||url.hostname.endsWith(".2gis.com")):(url.hostname==="yandex.kz"||url.hostname.endsWith(".yandex.kz")||url.hostname==="yandex.ru"||url.hostname.endsWith(".yandex.ru")||url.hostname==="yandex.com"||url.hostname.endsWith(".yandex.com")));}catch{return false;}};
export default function Delivery(){
 const{store,loading}=useOwnerStore();const[settings,setSettings]=useState<Settings|null>(null);const[address,setAddress]=useState("");const[map2gis,setMap2gis]=useState("");const[mapYandex,setMapYandex]=useState("");const[kaspi,setKaspi]=useState("");const[pickup,setPickup]=useState(true);const[delivery,setDelivery]=useState(false);const[kaspiEnabled,setKaspiEnabled]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error}=await supabase.from("tenant_settings").select("delivery_enabled,pickup_enabled,kaspi_remote_enabled,kaspi_remote_link,pickup_location").eq("tenant_id",store.id).maybeSingle();if(error||!data){setMessage("Не удалось загрузить настройки.");return;}const row=data as unknown as Settings;setSettings(row);setAddress(row.pickup_location?.address??"");setMap2gis(row.pickup_location?.map_2gis??"");setMapYandex(row.pickup_location?.map_yandex??"");setKaspi(row.kaspi_remote_link??"");setPickup(row.pickup_enabled);setDelivery(row.delivery_enabled);setKaspiEnabled(row.kaspi_remote_enabled);},[store]);
 useEffect(()=>{void load();},[load]);
 const save=async()=>{if(!store||!supabase)return;if(!pickup&&!delivery){Alert.alert("Выберите получение заказа","Включите самовывоз или доставку.");return;}if(pickup&&address.trim().length<3){Alert.alert("Укажите адрес самовывоза");return;}if(!validMap(map2gis.trim(),"2gis")||!validMap(mapYandex.trim(),"yandex")){Alert.alert("Проверьте ссылки на карты","Используйте защищённые ссылки 2GIS и Яндекс Карт.");return;}if(kaspiEnabled&&!/^https:\/\/(?:[a-z0-9-]+\.)*kaspi\.kz\//i.test(kaspi.trim())){Alert.alert("Проверьте ссылку Kaspi","Нужна защищённая ссылка на домене kaspi.kz.");return;}setSaving(true);const pickupLocation=pickup?{...(settings?.pickup_location??{}),address:address.trim(),map_2gis:map2gis.trim()||undefined,map_yandex:mapYandex.trim()||undefined}:settings?.pickup_location??null;const saved=await supabase.from("tenant_settings").update({pickup_enabled:pickup,delivery_enabled:delivery,kaspi_remote_enabled:kaspiEnabled,kaspi_remote_link:kaspiEnabled?kaspi.trim():null,pickup_location:pickupLocation}).eq("tenant_id",store.id);let zoneError=saved.error;if(!zoneError&&delivery){const{data:zone,error:readError}=await supabase.from("delivery_zones").select("id").eq("tenant_id",store.id).eq("provider","yandex").maybeSingle();if(readError)zoneError=readError;else{const result=zone?await supabase.from("delivery_zones").update({name:"Яндекс Доставка",cost:0,free_from:null,is_active:true,eta_text:"Цена зависит от расстояния; магазин согласует её после заказа"}).eq("id",zone.id):await supabase.from("delivery_zones").insert({tenant_id:store.id,name:"Яндекс Доставка",provider:"yandex",cost:0,free_from:null,is_active:true,eta_text:"Цена зависит от расстояния; магазин согласует её после заказа"});zoneError=result.error;}}setSaving(false);if(zoneError)Alert.alert("Не удалось сохранить","Настройки не подтверждены полностью. Обновите экран и повторите.");else{await load();Alert.alert("Настройки сохранены","Сайт и приложение используют эти же условия.");}};
 return <AppScreen section="Доставка и оплата" store={store?.name}><Text style={ui.title}>Получение заказа</Text><Text style={ui.subtitle}>Магазин сам заказывает Яндекс Доставку после согласования цены с покупателем. Dukenim не показывает заранее стоимость курьера.</Text>{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<Toggle title="Самовывоз" copy="Покупатель увидит адрес и ссылки на карты." value={pickup} onValue={setPickup}/>{pickup?<View style={ui.card}><Text style={ui.label}>Адрес самовывоза</Text><TextInput value={address} onChangeText={setAddress} style={ui.input} placeholder="Город, улица, дом"/><Text style={ui.label}>Ссылка 2GIS · необязательно</Text><TextInput value={map2gis} onChangeText={setMap2gis} autoCapitalize="none" keyboardType="url" style={ui.input} placeholder="https://2gis.kz/..."/><Text style={ui.label}>Ссылка Яндекс Карт · необязательно</Text><TextInput value={mapYandex} onChangeText={setMapYandex} autoCapitalize="none" keyboardType="url" style={ui.input} placeholder="https://yandex.kz/maps/..."/></View>:null}<Toggle title="Яндекс Доставка" copy="Цена зависит от расстояния. Менеджер оформляет «от двери до двери»." value={delivery} onValue={setDelivery}/><Text style={[ui.title,{fontSize:25,marginTop:6}]}>Удалённая оплата Kaspi</Text><Text style={ui.subtitle}>Покупатель открывает вашу Kaspi-ссылку, вводит сумму заказа и возвращается в «Мои заказы». Деньги подтверждает владелец после проверки.</Text><Toggle title="Принимать через Kaspi" copy="Автоматического списания и проверки поступления нет." value={kaspiEnabled} onValue={setKaspiEnabled}/>{kaspiEnabled?<View style={ui.card}><Text style={ui.label}>Ссылка Kaspi Pay</Text><TextInput value={kaspi} onChangeText={setKaspi} autoCapitalize="none" keyboardType="url" style={ui.input} placeholder="https://pay.kaspi.kz/..."/><Text style={ui.subtitle}>Ссылка откроется только после создания заказа с точной суммой.</Text></View>:null}<Pressable disabled={saving} onPress={()=>void save()} style={ui.button}>{saving?<ActivityIndicator color="white"/>:<Text style={ui.buttonText}>Сохранить настройки</Text>}</Pressable></AppScreen>;
}
function Toggle({title,copy,value,onValue}:{title:string;copy:string;value:boolean;onValue:(value:boolean)=>void}){return <View style={s.toggle}><View style={{flex:1}}><Text style={s.toggleTitle}>{title}</Text><Text style={s.toggleCopy}>{copy}</Text></View><Switch value={value} onValueChange={onValue} trackColor={{false:"#D7DEE3",true:colors.navy}}/></View>}
const s=StyleSheet.create({toggle:{flexDirection:"row",alignItems:"center",gap:14,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:17,backgroundColor:"white"},toggleTitle:{fontSize:17,fontWeight:"900",color:colors.ink},toggleCopy:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:4}});
