import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import { notificationTarget } from "@/lib/notification-target";
import { workspaceRoute } from "@/lib/owner";
import logoMark from "../../assets/images/logo-mark-compact.png";

export default function LoginScreen() {
  const params = useLocalSearchParams<{ orderId?: string; tenantId?: string }>();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(true); const [pending,setPending]=useState(false);
  useEffect(()=>{void supabase?.auth.getSession().then(async({data})=>{if(data.session){const target=notificationTarget(params);router.replace((target?{pathname:"/order",params:target}:await workspaceRoute()) as never);}else setLoading(false);});},[params]);
  const signIn=async()=>{if(!supabase)return;if(!email.trim()||!password){Alert.alert("Заполните данные","Укажите email и пароль.");return;}setPending(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setPending(false);Alert.alert("Не удалось войти","Проверьте email, пароль и подтверждение почты.");return;}try{router.replace(await workspaceRoute() as never);}catch{setPending(false);Alert.alert("Не удалось открыть кабинет","Повторите вход через несколько секунд.");}};
  if(loading)return <View style={styles.loader}><ActivityIndicator color={colors.navy}/></View>;
  return <SafeAreaView style={styles.page}><KeyboardAvoidingView style={styles.center} behavior={Platform.OS==="ios"?"padding":undefined}>
    <View style={styles.brand}><View style={styles.mark}><Image alt="" source={logoMark} resizeMode="contain" style={styles.logo}/></View><View><Text style={styles.brandLabel}>РАБОЧЕЕ ПРИЛОЖЕНИЕ</Text><Text style={styles.brandName}>Dukenim</Text></View></View>
    <View style={styles.hero}><Text style={styles.eyebrow}>ВАШ БИЗНЕС В ТЕЛЕФОНЕ</Text><Text style={styles.title}>Войдите в кабинет</Text><Text style={styles.copy}>Заказы, каталог, AI Studio и команда синхронизируются с dukenim.kz.</Text></View>
    {!isSupabaseConfigured?<Text style={styles.error}>Подключение приложения не настроено.</Text>:<View style={styles.form}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email" placeholderTextColor="#7F8A92" style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete="current-password" placeholder="Пароль" placeholderTextColor="#7F8A92" style={styles.input} onSubmitEditing={()=>void signIn()}/><Pressable disabled={pending} onPress={()=>void signIn()} style={({pressed})=>[styles.primary,(pending||pressed)&&{opacity:.65}]}>{pending?<ActivityIndicator color="white"/>:<Text style={styles.primaryText}>Войти</Text>}</Pressable></View>}
    <View style={styles.links}><Pressable onPress={()=>router.push("/forgot-password" as never)}><Text style={styles.link}>Забыли пароль?</Text></Pressable><Pressable onPress={()=>router.push("/register" as never)}><Text style={styles.linkStrong}>Создать магазин бесплатно →</Text></Pressable></View>
  </KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"#FFFFFF"},center:{flex:1,justifyContent:"center",padding:26,gap:20},loader:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"white"},brand:{flexDirection:"row",alignItems:"center",gap:12},mark:{width:48,height:48,borderRadius:15,borderWidth:1,borderColor:colors.line,alignItems:"center",justifyContent:"center"},logo:{width:29,height:31},brandLabel:{fontSize:10,fontWeight:"900",letterSpacing:1.45,color:colors.navy},brandName:{fontSize:27,fontWeight:"900",color:colors.ink},hero:{gap:8,marginTop:10},eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.6,color:colors.navy},title:{fontSize:36,fontWeight:"900",letterSpacing:-1.3,color:colors.ink},copy:{color:colors.muted,fontSize:15,lineHeight:23},form:{gap:12},input:{minHeight:56,borderRadius:15,borderWidth:1,borderColor:colors.line,paddingHorizontal:16,fontSize:17,color:colors.ink,backgroundColor:"white"},primary:{minHeight:56,borderRadius:15,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},primaryText:{color:"white",fontSize:16,fontWeight:"900"},links:{gap:16,alignItems:"center"},link:{color:colors.navyDark,fontWeight:"800"},linkStrong:{color:colors.navy,fontWeight:"900",fontSize:15},error:{color:colors.danger}});
