import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";
import { notificationTarget } from "@/lib/notification-target";
import { workspaceRoute } from "@/lib/owner";
import { appleAuthReady, signInWithApple, signInWithGoogle } from "@/lib/social-auth";
import { AppleSignInButton } from "@/components/apple-sign-in-button";
import logoMark from "../../assets/images/logo-mark-compact.png";

export default function LoginScreen() {
  const params = useLocalSearchParams<{ orderId?: string; tenantId?: string }>();
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(true); const [pending,setPending]=useState(false); const [showEmail,setShowEmail]=useState(false); const [showLogin,setShowLogin]=useState(false);
  useEffect(()=>{let active=true;void(async()=>{try{if(!supabase)return;const{data,error}=await supabase.auth.getSession();if(error)throw error;if(data.session){const target=notificationTarget(params);const route=target?{pathname:"/order",params:target}:await workspaceRoute();if(active)router.replace(route as never);return;}}catch{if(active)Alert.alert("Не удалось восстановить вход","Проверьте подключение и войдите снова.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[params]);
  const destination=async()=>{const target=notificationTarget(params);return target?{pathname:"/order",params:target}:await workspaceRoute();};
  const signIn=async()=>{if(!supabase)return;if(!email.trim()||!password){Alert.alert("Заполните данные","Укажите email и пароль.");return;}setPending(true);const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setPending(false);Alert.alert("Не удалось войти","Проверьте email, пароль и подтверждение почты.");return;}try{router.replace(await destination() as never);}catch{setPending(false);Alert.alert("Не удалось открыть кабинет","Повторите вход через несколько секунд.");}};
  const social=async(provider:"google"|"apple")=>{setPending(true);try{const success=await(provider==="google"?signInWithGoogle():signInWithApple());if(success)router.replace(await destination() as never);}catch(error){Alert.alert("Вход не завершён",error instanceof Error?error.message:"Попробуйте ещё раз.");}finally{setPending(false);}};
  if(loading)return <View style={styles.loader}><ActivityIndicator color={colors.navy}/></View>;
  if(!showLogin)return <SafeAreaView style={styles.page}><View style={styles.welcomeHeader}><View style={styles.brand}><View style={styles.mark}><Image alt="" source={logoMark} resizeMode="contain" style={styles.logo}/></View><View><Text style={styles.brandName}>Dukenim</Text><Text style={styles.welcomeCaption}>Кабинет продавца</Text></View></View><Text style={styles.welcomePill}>Для магазинов и кафе</Text></View><ScrollView contentContainerStyle={styles.welcomeContent}><Text style={styles.welcomeTitle}>Dukenim для владельца магазина</Text><Text style={styles.copy}>Управляйте витриной, меню и заказами в одном приложении.</Text><View style={styles.welcomeFeatures}><WelcomeFeature icon="▦" title="Витрина и каталог" description="Соберите каталог и делитесь ссылкой на магазин с покупателями."/><WelcomeFeature icon="✓" title="Ручной Kaspi и заказы" description="Покупатель переводит по вашим реквизитам. Вы лично сверяете поступление и подтверждаете заказ."/><WelcomeFeature icon="✦" title="AI Studio" description="AI предлагает оформление, карточки и тексты. Изменения применяются после вашего подтверждения."/><WelcomeFeature icon="7" title="Тариф «Каталог» · 24 900 ₸/мес" description="Все функции доступны в пробный период 7 дней. Карта для начала не нужна."/></View></ScrollView><View style={styles.welcomeActions}><Pressable onPress={()=>router.push("/register" as never)} style={styles.primary}><Text style={styles.primaryText}>Создать магазин бесплатно →</Text></Pressable><Pressable onPress={()=>setShowLogin(true)} style={styles.social}><Text style={styles.socialText}>У меня уже есть магазин · Войти</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={styles.page}><KeyboardAvoidingView style={styles.center} behavior={Platform.OS==="ios"?"padding":undefined}>
    <Pressable accessibilityLabel="Назад" onPress={()=>setShowLogin(false)} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable>
    <View style={styles.brand}><View style={styles.mark}><Image alt="" source={logoMark} resizeMode="contain" style={styles.logo}/></View><View><Text style={styles.brandLabel}>РАБОЧЕЕ ПРИЛОЖЕНИЕ</Text><Text style={styles.brandName}>Dukenim</Text></View></View>
    <View style={styles.hero}><Text style={styles.eyebrow}>ВАШ БИЗНЕС В ТЕЛЕФОНЕ</Text><Text style={styles.title}>Войдите в кабинет</Text><Text style={styles.copy}>Заказы, каталог, AI Studio и команда синхронизируются с dukenim.kz.</Text></View>
    {!isSupabaseConfigured?<Text style={styles.error}>Подключение приложения не настроено.</Text>:<View style={styles.form}><Pressable disabled={pending} onPress={()=>void social("google")} style={({pressed})=>[styles.primary,(pending||pressed)&&{opacity:.65}]}>{pending?<ActivityIndicator color="white"/>:<Text style={styles.primaryText}>Продолжить с Google</Text>}</Pressable>{Platform.OS==="ios"&&appleAuthReady?<AppleSignInButton pending={pending} onPress={()=>void social("apple")}/>:null}<Pressable onPress={()=>setShowEmail(value=>!value)} style={styles.emailToggle}><Text style={styles.link}>{showEmail?"Скрыть вход по email":"Войти по email и паролю"}</Text></Pressable>{showEmail?<View style={styles.emailForm}><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" autoComplete="email" keyboardType="email-address" placeholder="Email" placeholderTextColor="#7F8A92" style={styles.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete="current-password" placeholder="Пароль" placeholderTextColor="#7F8A92" style={styles.input} onSubmitEditing={()=>void signIn()}/><Pressable disabled={pending} onPress={()=>void signIn()} style={styles.social}><Text style={styles.socialText}>Войти по паролю</Text></Pressable><Pressable onPress={()=>router.push("/forgot-password" as never)}><Text style={styles.link}>Забыли пароль?</Text></Pressable></View>:null}</View>}
    <View style={styles.links}><Pressable onPress={()=>router.push("/register" as never)}><Text style={styles.linkStrong}>Создать магазин бесплатно →</Text></Pressable></View>
  </KeyboardAvoidingView></SafeAreaView>;
}
function WelcomeFeature({icon,title,description}:{icon:string;title:string;description:string}){return <View style={styles.welcomeFeature}><View style={styles.featureIcon}><Text style={styles.featureIconText}>{icon}</Text></View><View style={{flex:1,gap:4}}><Text style={styles.featureTitle}>{title}</Text><Text style={styles.featureCopy}>{description}</Text></View></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:"#FFFFFF"},center:{flex:1,justifyContent:"center",padding:26,gap:20},loader:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"white"},brand:{flexDirection:"row",alignItems:"center",gap:12},mark:{width:48,height:48,borderRadius:15,borderWidth:1,borderColor:colors.line,alignItems:"center",justifyContent:"center"},logo:{width:29,height:31},brandLabel:{fontSize:10,fontWeight:"900",letterSpacing:1.45,color:colors.navy},brandName:{fontSize:27,fontWeight:"900",color:colors.ink},hero:{gap:8,marginTop:10},eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.6,color:colors.navy},title:{fontSize:36,fontWeight:"900",letterSpacing:-1.3,color:colors.ink},copy:{color:colors.muted,fontSize:15,lineHeight:23},form:{gap:12,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:18},emailForm:{gap:12},emailToggle:{alignItems:"center",paddingVertical:7},input:{minHeight:56,borderRadius:15,borderWidth:1,borderColor:colors.line,paddingHorizontal:16,fontSize:17,color:colors.ink,backgroundColor:"white"},primary:{minHeight:56,borderRadius:15,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},primaryText:{color:"white",fontSize:16,fontWeight:"900"},social:{minHeight:48,borderWidth:1,borderColor:colors.line,borderRadius:14,alignItems:"center",justifyContent:"center"},socialText:{fontSize:15,fontWeight:"900",color:colors.ink},links:{gap:16,alignItems:"center"},link:{color:colors.navyDark,fontWeight:"800"},linkStrong:{color:colors.navy,fontWeight:"900",fontSize:15},error:{color:colors.danger},back:{width:44,height:44,borderRadius:22,alignItems:"center",justifyContent:"center"},backText:{fontSize:33,color:colors.ink,lineHeight:37},welcomeHeader:{paddingHorizontal:20,paddingTop:12,paddingBottom:14,borderBottomWidth:1,borderColor:colors.line,flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},welcomeCaption:{fontSize:11,color:colors.muted},welcomePill:{fontSize:10,fontWeight:"800",color:colors.navyDark,backgroundColor:colors.navySoft,paddingHorizontal:10,paddingVertical:7,borderRadius:18,overflow:"hidden"},welcomeContent:{padding:20,paddingBottom:30,gap:12},welcomeTitle:{fontSize:29,lineHeight:35,fontWeight:"900",letterSpacing:-.8,color:colors.ink,marginTop:12},welcomeFeatures:{gap:10,marginTop:14},welcomeFeature:{flexDirection:"row",gap:13,padding:15,borderRadius:16,backgroundColor:"#F7F9FA"},featureIcon:{height:38,width:38,borderRadius:12,backgroundColor:colors.navySoft,alignItems:"center",justifyContent:"center"},featureIconText:{color:colors.navy,fontSize:20,fontWeight:"900"},featureTitle:{fontSize:16,fontWeight:"800",color:colors.ink},featureCopy:{fontSize:13,lineHeight:19,color:colors.muted},welcomeActions:{padding:18,paddingBottom:12,gap:10,borderTopWidth:1,borderColor:colors.line,backgroundColor:"white"}});
