import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { EditorScreen } from "@/components/editor-screen";
import { ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";

const providers=[
  {key:"poster",label:"Poster",group:"Рестораны и кафе"},{key:"iiko",label:"iiko",group:"Рестораны и кафе"},{key:"moysklad",label:"МойСклад",group:"Торговля и учёт"},
  {key:"bitrix24",label:"Bitrix24",group:"CRM"},{key:"kommo",label:"Kommo / amoCRM",group:"CRM"},{key:"planfix",label:"Planfix",group:"CRM"},
  {key:"rosta",label:"Rosta",group:"Казахстан"},{key:"umag",label:"UMAG",group:"Казахстан"},{key:"other",label:"Другая система",group:"Другое"},
] as const;
type RequestRow={id:string;provider:string;status:string;account_url:string|null;admin_contact:string|null;updated_at:string};

export default function Integrations(){
  const{store}=useOwnerStore();const[rows,setRows]=useState<RequestRow[]>([]);const[provider,setProvider]=useState<(typeof providers)[number]["key"]>("poster");const[url,setUrl]=useState("");const[contact,setContact]=useState("");const[notes,setNotes]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{if(!store||!supabase)return;setLoading(true);const{data}=await supabase.from("crm_integration_requests").select("id,provider,status,account_url,admin_contact,updated_at").eq("tenant_id",store.id).order("updated_at",{ascending:false});setRows((data??[]) as RequestRow[]);setLoading(false);},[store]);
  useEffect(()=>{void load();},[load]);
  const save=async()=>{if(!store||!supabase)return;if(url&& !/^https?:\/\//i.test(url)){Alert.alert("Проверьте ссылку","Адрес кабинета должен начинаться с https://");return;}setSaving(true);const status=url.trim()&&contact.trim()?"submitted":"credentials_needed";const{error}=await supabase.from("crm_integration_requests").upsert({tenant_id:store.id,provider,account_url:url.trim()||null,admin_contact:contact.trim()||null,sync_direction:"orders_and_customers",notes:notes.trim()||null,status,submitted_at:status==="submitted"?new Date().toISOString():null,last_status_at:new Date().toISOString(),updated_at:new Date().toISOString()} as never,{onConflict:"tenant_id,provider"});setSaving(false);if(error){Alert.alert("Не удалось сохранить заявку","Проверьте данные и повторите.");return;}setUrl("");setContact("");setNotes("");await load();Alert.alert("Заявка сохранена","Статус подключения виден в приложении и веб-кабинете.");};
  return <EditorScreen title="Интеграции" subtitle={store?.name}>
    <View style={s.hero}><Text style={s.heroLabel}>ЕДИНЫЙ ЦЕНТР</Text><Text style={s.heroTitle}>Подключения магазина</Text><Text style={s.heroCopy}>Kaspi и Яндекс настраиваются в «Доставка и оплата». Здесь создаются заявки для CRM, учётных систем и ресторанных сервисов.</Text></View>
    <Text style={s.heading}>Выберите систему</Text><View style={s.chips}>{providers.map(item=><Pressable key={item.key} onPress={()=>setProvider(item.key)} style={[s.chip,provider===item.key&&s.chipOn]}><Text style={[s.chipText,provider===item.key&&s.chipTextOn]}>{item.label}</Text><Text style={[s.chipGroup,provider===item.key&&s.chipTextOn]}>{item.group}</Text></Pressable>)}</View>
    <View style={ui.card}><Text style={ui.cardTitle}>Данные для подключения</Text><Text style={ui.subtitle}>Можно сохранить заявку сейчас и добавить доступ позже. Пароль от сервиса не нужен.</Text><Text style={ui.label}>Ссылка на кабинет · необязательно</Text><TextInput value={url} onChangeText={setUrl} autoCapitalize="none" keyboardType="url" style={ui.input} placeholder="https://..."/><Text style={ui.label}>Контакт администратора · необязательно</Text><TextInput value={contact} onChangeText={setContact} style={ui.input} placeholder="Email или телефон"/><Text style={ui.label}>Что нужно синхронизировать?</Text><TextInput value={notes} onChangeText={setNotes} multiline style={[ui.input,s.notes]} placeholder="Например: товары, остатки и заказы"/><Pressable disabled={saving} onPress={()=>void save()} style={ui.button}>{saving?<ActivityIndicator color="white"/>:<Text style={ui.buttonText}>Сохранить заявку</Text>}</Pressable></View>
    <Text style={s.heading}>Ваши подключения</Text>{loading?<ActivityIndicator color={colors.navy}/>:rows.length?rows.map(row=><View key={row.id} style={s.status}><View style={{flex:1}}><Text style={s.statusTitle}>{providers.find(item=>item.key===row.provider)?.label??row.provider}</Text><Text style={s.statusCopy}>{statusLabel(row.status)}</Text></View><View style={s.dot}/></View>):<View style={ui.card}><Text style={ui.cardTitle}>Заявок пока нет</Text><Text style={ui.subtitle}>Выберите сервис выше. После сохранения заявка появится и на сайте.</Text></View>}
  </EditorScreen>;
}
function statusLabel(status:string){return status==="connected"?"Подключено":status==="submitted"?"Отправлено на проверку":status==="credentials_needed"?"Нужны данные магазина":status==="details_later"?"Данные добавите позже":"Проверяем подключение"}
const s=StyleSheet.create({hero:{borderRadius:24,backgroundColor:colors.navyDark,padding:20,gap:6},heroLabel:{fontSize:9,fontWeight:"900",letterSpacing:1.4,color:"#C7DCE7"},heroTitle:{fontSize:25,fontWeight:"900",color:"white"},heroCopy:{fontSize:13,lineHeight:20,color:"#DCE8EE"},heading:{fontSize:20,fontWeight:"900",color:colors.ink,marginTop:4},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{width:"48%",borderWidth:1,borderColor:colors.line,borderRadius:16,padding:12,backgroundColor:"white",gap:3},chipOn:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{fontSize:14,fontWeight:"900",color:colors.ink},chipGroup:{fontSize:10,color:colors.muted},chipTextOn:{color:"white"},notes:{minHeight:92,textAlignVertical:"top",paddingTop:14},status:{borderWidth:1,borderColor:colors.line,borderRadius:17,padding:15,flexDirection:"row",alignItems:"center",backgroundColor:"white"},statusTitle:{fontSize:15,fontWeight:"900",color:colors.ink},statusCopy:{fontSize:12,color:colors.muted,marginTop:3},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.navy}});
