import {useCallback,useEffect,useState} from "react";
import {ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {EditorScreen} from "@/components/editor-screen";
import {ui} from "@/components/app-shell";
import {useOwnerStore} from "@/lib/use-owner-store";
import {colors} from "@/lib/theme";
import {supabase} from "@/lib/supabase";
type Unit="g"|"kg"|"ml"|"l"|"pcs";type Material={id:string;name:string;unit:Unit;stock_qty:number};const labels:Record<Unit,string>={g:"г",kg:"кг",ml:"мл",l:"л",pcs:"шт."};
export default function Materials(){const{store}=useOwnerStore();const[rows,setRows]=useState<Material[]>([]),[name,setName]=useState(""),[stock,setStock]=useState("0"),[unit,setUnit]=useState<Unit>("g"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error}=await supabase.from("food_materials").select("id,name,unit,stock_qty").eq("tenant_id",store.id).order("name");if(error)Alert.alert("Не удалось загрузить склад сырья");else setRows((data??[]) as Material[]);setLoading(false);},[store]);useEffect(()=>{void load();},[load]);const save=async(id:string|null,itemName=name,itemUnit=unit,value=Number(stock||0))=>{if(!store||!supabase||itemName.trim().length<1||value<0)return;setSaving(true);const{error}=await supabase.rpc("owner_save_food_material" as never,{p_tenant:store.id,p_id:id,p_name:itemName.trim(),p_unit:itemUnit,p_stock:value} as never);setSaving(false);if(error)Alert.alert("Сырьё не сохранено","Названия не должны повторяться. Проверьте остаток.");else{setName("");setStock("0");await load();}};return <EditorScreen title="Склад сырья" subtitle={store?.name}><Text style={ui.title}>Ингредиенты</Text><Text style={ui.subtitle}>Корректировки записываются в журнал. Сырьё списывается автоматически по сохранённым техкартам после заказа.</Text><View style={ui.card}><Text style={ui.cardTitle}>Добавить сырьё</Text><TextInput style={ui.input} value={name} onChangeText={setName} maxLength={80} placeholder="Например, молоко"/><View style={s.units}>{(Object.keys(labels) as Unit[]).map(value=><Pressable key={value} onPress={()=>setUnit(value)} style={[s.unit,unit===value&&s.unitOn]}><Text style={[s.unitText,unit===value&&s.unitTextOn]}>{labels[value]}</Text></Pressable>)}</View><TextInput style={ui.input} value={stock} onChangeText={value=>setStock(value.replace(/[^\d.]/g,""))} keyboardType="decimal-pad" placeholder="Текущий остаток"/><Pressable disabled={saving} onPress={()=>void save(null)} style={ui.button}><Text style={ui.buttonText}>{saving?"Сохраняем…":"Добавить на склад"}</Text></Pressable></View>{loading?<ActivityIndicator color={colors.navy}/>:rows.map(row=><MaterialRow key={row.id} row={row} onSave={save}/>)}</EditorScreen>}
function MaterialRow({row,onSave}:{row:Material;onSave:(id:string|null,name:string,unit:Unit,value:number)=>Promise<void>}){const[value,setValue]=useState(String(row.stock_qty));return <View style={s.row}><View style={{flex:1}}><Text style={s.name}>{row.name}</Text><Text style={s.meta}>{row.stock_qty} {labels[row.unit]}</Text></View><TextInput style={s.qty} value={value} onChangeText={text=>setValue(text.replace(/[^\d.]/g,""))} keyboardType="decimal-pad" selectTextOnFocus/><Pressable onPress={()=>void onSave(row.id,row.name,row.unit,Number(value||0))} style={s.save}><Text style={s.saveText}>Сохранить</Text></Pressable></View>}
const s=StyleSheet.create({units:{flexDirection:"row",flexWrap:"wrap",gap:7},unit:{minWidth:48,borderWidth:1,borderColor:colors.line,borderRadius:12,paddingHorizontal:11,paddingVertical:9,alignItems:"center"},unitOn:{backgroundColor:colors.navy,borderColor:colors.navy},unitText:{fontWeight:"800",color:colors.muted},unitTextOn:{color:"white"},row:{minHeight:76,borderRadius:18,borderWidth:1,borderColor:colors.line,padding:12,flexDirection:"row",alignItems:"center",gap:8},name:{fontSize:16,fontWeight:"900",color:colors.ink},meta:{fontSize:11,color:colors.muted,marginTop:3},qty:{width:72,height:44,borderRadius:12,borderWidth:1,borderColor:colors.line,textAlign:"center",fontWeight:"900",color:colors.ink},save:{height:44,paddingHorizontal:10,borderRadius:12,backgroundColor:colors.navySoft,alignItems:"center",justifyContent:"center"},saveText:{fontSize:11,fontWeight:"900",color:colors.navyDark}});
