import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import {useState} from "react";
import { router } from "expo-router";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors } from "@/lib/theme";
import { disableCurrentDevicePush } from "@/lib/notifications";
import { supabase } from "@/lib/supabase";
import { clearOrdersWidget } from "@/widgets/orders-widget";
const groups=[
 {title:"Продажи",items:[{title:"Склад",copy:"Остатки и движения",path:"/stock"},{title:"Клиенты",copy:"История покупателей",path:"/customers"},{title:"Аналитика",copy:"Продажи и показатели",path:"/analytics"},{title:"Сканер",copy:"Найти товар по штрихкоду",path:"/scanner"}]},
 {title:"Продвижение",items:[{title:"Сборка магазина",copy:"Все блоки витрины в одном месте",path:"/store-builder"},{title:"Истории",copy:"Фото и видео над меню",path:"/stories"},{title:"Акции",copy:"Баннеры и кампании",path:"/campaigns"},{title:"Лояльность",copy:"Подарки, скидки и друзья",path:"/loyalty"},{title:"Оформление",copy:"Шаблон, обложка и тексты",path:"/brand"}]},
 {title:"Магазин",items:[{title:"Сотрудники",copy:"Приглашения и права",path:"/team"},{title:"Доставка и оплата",copy:"Kaspi, самовывоз и Яндекс",path:"/delivery"},{title:"Интеграции",copy:"CRM, учёт и ресторанные системы",path:"/integrations"},{title:"Ссылка магазина",copy:"Адрес и предпросмотр",path:"/store-link"},{title:"Тариф",copy:"Каталог · 24 900 ₸ в месяц",path:"/plan"},{title:"Поддержка",copy:"Чат с командой Dukenim",path:"/support"},{title:"Настройки",copy:"Уведомления и аккаунт",path:"/settings"}]},
] as const;
export default function More(){const{context,store,select}=useOwnerStore();const[signingOut,setSigningOut]=useState(false);const signOut=()=>{if(signingOut)return;Alert.alert("Выйти из Dukenim?","Уведомления на этом устройстве будут отключены.",[{text:"Отмена",style:"cancel"},{text:"Выйти",style:"destructive",onPress:async()=>{setSigningOut(true);try{if(!supabase)throw new Error("Подключение недоступно");await disableCurrentDevicePush();const{error}=await supabase.auth.signOut();if(error)throw error;clearOrdersWidget();router.replace("/");}catch{Alert.alert("Не удалось выйти","Проверьте соединение и повторите. Для безопасного выхода нужно отключить уведомления этого телефона.");}finally{setSigningOut(false);}}}]);};return <AppScreen section="Управление" store={store?.name}><Text style={ui.title}>Ещё</Text>{store?<View style={s.storeCard}><Text style={s.storeEyebrow}>ВАШ МАГАЗИН</Text><Text style={s.storeName}>{store.name}</Text><Text style={s.storeStatus}>{store.catalog_published?"Витрина опубликована":"Черновик · витрина пока не опубликована"}</Text><Text style={s.storeUrl}>dukenim.kz/s/{store.slug}</Text><View style={s.storeActions}><Pressable onPress={()=>router.push("/store-link" as never)} style={s.storeAction}><Text style={s.storeActionText}>Ссылка и предпросмотр →</Text></Pressable>{!store.catalog_published?<Pressable onPress={()=>router.push((store.catalog_status==="not_started"?"/catalog-builder":"/catalog") as never)} style={s.storeAction}><Text style={s.storeActionText}>Продолжить настройку →</Text></Pressable>:null}</View></View>:null}<Text style={ui.subtitle}>Все разделы работают с тем же магазином, что и веб-кабинет.</Text>{(context?.stores.length??0)>1?<View style={s.switcher}><Text style={s.groupTitle}>ВЫБРАННЫЙ МАГАЗИН</Text><View style={s.storeChips}>{context!.stores.map(item=><Pressable key={item.id} onPress={()=>select(item)} style={[s.storeChip,item.id===store?.id&&s.storeChipOn]}><Text style={[s.storeChipText,item.id===store?.id&&s.storeChipTextOn]}>{item.name}</Text></Pressable>)}</View></View>:null}{groups.map(group=><View key={group.title} style={s.group}><Text style={s.groupTitle}>{group.title.toUpperCase()}</Text><View style={s.list}>{group.items.map(item=><Pressable accessibilityRole="button" key={item.path} onPress={()=>router.push(item.path as never)} style={({pressed})=>[s.row,pressed&&ui.pressed]}><View style={s.icon}><Text style={s.iconText}>{item.title.slice(0,1)}</Text></View><View style={{flex:1}}><Text style={s.title}>{item.title}</Text><Text style={s.copy}>{item.copy}</Text></View><Text style={s.arrow}>›</Text></Pressable>)}</View></View>)}<Pressable disabled={signingOut} onPress={signOut} style={ui.outline}><Text style={ui.outlineText}>{signingOut?"Выходим…":"Выйти из аккаунта"}</Text></Pressable></AppScreen>}
const s=StyleSheet.create({storeCard:{backgroundColor:colors.navyDark,borderRadius:22,padding:20,gap:5},storeEyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.4,color:"#E5CDDA"},storeName:{fontSize:24,fontWeight:"900",color:"white"},storeStatus:{fontSize:13,color:"#EADFE6"},storeUrl:{fontSize:13,color:"white",fontWeight:"800",marginTop:6},storeActions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:10},storeAction:{minHeight:40,borderRadius:11,backgroundColor:"#FFFFFF26",paddingHorizontal:12,alignItems:"center",justifyContent:"center"},storeActionText:{fontSize:12,fontWeight:"900",color:"white"},switcher:{gap:8},storeChips:{flexDirection:"row",flexWrap:"wrap",gap:7},storeChip:{borderRadius:999,borderWidth:1,borderColor:colors.line,paddingHorizontal:12,paddingVertical:9},storeChipOn:{backgroundColor:colors.navy,borderColor:colors.navy},storeChipText:{fontSize:12,fontWeight:"800",color:colors.muted},storeChipTextOn:{color:"white"},group:{gap:8},groupTitle:{fontSize:10,fontWeight:"900",letterSpacing:1.35,color:colors.navy,marginLeft:4,marginTop:4},list:{borderWidth:1,borderColor:colors.line,borderRadius:22,backgroundColor:"white",overflow:"hidden"},row:{minHeight:76,paddingHorizontal:14,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},icon:{width:38,height:38,borderRadius:12,backgroundColor:colors.navySoft,alignItems:"center",justifyContent:"center"},iconText:{fontSize:15,fontWeight:"900",color:colors.navyDark},title:{fontSize:16,fontWeight:"900",color:colors.ink},copy:{fontSize:12,lineHeight:17,color:colors.muted,marginTop:3},arrow:{fontSize:30,fontWeight:"400",color:colors.navy}});
