import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { loadOwnerContext } from "@/lib/owner";
import { supabase } from "@/lib/supabase";

const verticals=[
  ["food","Еда и напитки","Ресторан, донерная, кондитерская, выпечка, кофе с собой"],
  ["fashion","Одежда и аксессуары","Бутик, шоурум, обувь и аксессуары"],
  ["beauty","Красота","Косметика и товары для ухода"],
  ["flowers","Цветы и подарки","Букеты, композиции и подарки"],
  ["home","Дом","Мебель, декор и товары для дома"],
  ["services","Услуги","Запись, консультации и услуги"],
  ["other","Другое","Универсальный каталог"],
] as const;
const plans=[
  {key:"basic",title:"Старт",copy:"Каталог, заказы и основные инструменты для запуска."},
  {key:"standard",title:"Бизнес",copy:"Больше возможностей для растущего магазина."},
] as const;

export default function Onboarding(){
  const[step,setStep]=useState(0);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[tenantId,setTenantId]=useState("");const[vertical,setVertical]=useState("food");const[plan,setPlan]=useState<"basic"|"standard">("basic");const[billing,setBilling]=useState<"monthly"|"annual">("monthly");
  useEffect(()=>{void loadOwnerContext().then(context=>{const selectedId=globalThis.localStorage?.getItem("dukenim_selected_store");const store=context.stores.find(item=>item.id===selectedId)??context.stores[0];if(!store){router.replace("/setup-store" as never);return;}if(store.onboarding_completed){router.replace((store.catalog_status==="not_started"?"/catalog-builder":"/catalog") as never);return;}setTenantId(store.id);setVertical(store.business_vertical??"food");setPlan(store.next_plan==="standard"?"standard":"basic");setBilling(store.preferred_billing_period);setLoading(false);}).catch(()=>router.replace("/" as never));},[]);
  const selectedVertical=useMemo(()=>verticals.find(item=>item[0]===vertical),[vertical]);
  const finish=async()=>{if(!supabase||!tenantId)return;setSaving(true);const{error}=await supabase.rpc("complete_onboarding_v2" as never,{p_tenant_id:tenantId,p_next_plan:plan,p_business_vertical:vertical,p_storefront_format:"catalog",p_preferred_billing_period:billing} as never);setSaving(false);if(error){Alert.alert("Не удалось сохранить", "Проверьте подключение и повторите.");return;}router.replace("/catalog-builder" as never);};
  if(loading)return <View style={s.loader}><ActivityIndicator color={colors.navy}/></View>;
  return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.progress}><View style={[s.progressFill,{width:`${((step+1)/3)*100}%`}]} /></View><Text style={s.kicker}>ШАГ {step+1} ИЗ 3</Text>
    {step===0?<><Text style={s.title}>Ваше направление</Text><Text style={s.copy}>Мы подстроим примеры, каталог и подсказки под ваш бизнес.</Text><View style={s.options}>{verticals.map(item=><Pressable key={item[0]} onPress={()=>setVertical(item[0])} style={[s.option,vertical===item[0]&&s.active]}><Text style={[s.optionTitle,vertical===item[0]&&s.activeText]}>{item[1]}</Text><Text style={s.optionCopy}>{item[2]}</Text></Pressable>)}</View></>:null}
    {step===1?<><Text style={s.title}>Выберите тариф</Text><Text style={s.copy}>Сейчас действует пробный период. Списаний без вашего подтверждения не будет.</Text><View style={s.segment}><Pressable onPress={()=>setBilling("monthly")} style={[s.segmentButton,billing==="monthly"&&s.segmentActive]}><Text style={s.segmentText}>Ежемесячно</Text></Pressable><Pressable onPress={()=>setBilling("annual")} style={[s.segmentButton,billing==="annual"&&s.segmentActive]}><Text style={s.segmentText}>На год выгоднее</Text></Pressable></View><View style={s.options}>{plans.map(item=><Pressable key={item.key} onPress={()=>setPlan(item.key)} style={[s.plan,plan===item.key&&s.active]}><Text style={[s.optionTitle,plan===item.key&&s.activeText]}>{item.title}</Text><Text style={s.optionCopy}>{item.copy}</Text><Text style={s.price}>{item.key==="basic"?"14 900":"34 900"} ₸ / мес.</Text></Pressable>)}</View></>:null}
    {step===2?<><Text style={s.title}>Всё готово для каталога</Text><Text style={s.copy}>Следующий экран соберёт витрину по шагам. Черновик общий для сайта и приложения.</Text><View style={s.summary}><Row label="Направление" value={selectedVertical?.[1]??"Другое"}/><Row label="Тариф после пробного периода" value={plans.find(item=>item.key===plan)?.title??"Старт"}/><Row label="Оплата тарифа" value={billing==="annual"?"Раз в год":"Ежемесячно"}/></View><View style={s.note}><Text style={s.noteTitle}>Дальше — каталог</Text><Text style={s.noteText}>Название → шаблон → цвета → доставка и самовывоз → оплата → проверка.</Text></View></>:null}
    <View style={s.actions}>{step>0?<Pressable onPress={()=>setStep(value=>value-1)} style={s.secondary}><Text style={s.secondaryText}>Назад</Text></Pressable>:null}<Pressable disabled={saving} onPress={()=>step<2?setStep(value=>value+1):void finish()} style={s.primary}>{saving?<ActivityIndicator color="white"/>:<Text style={s.primaryText}>{step<2?"Продолжить":"Собрать каталог"}</Text>}</Pressable></View>
  </ScrollView></SafeAreaView>;
}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"white"},loader:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"white"},content:{padding:24,paddingBottom:42,gap:14},progress:{height:5,borderRadius:9,backgroundColor:colors.navySoft,overflow:"hidden",marginTop:8},progressFill:{height:"100%",backgroundColor:colors.navy},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.5,color:colors.navy,marginTop:8},title:{fontSize:35,fontWeight:"900",color:colors.ink,letterSpacing:-1.2},copy:{fontSize:15,lineHeight:22,color:colors.muted},options:{gap:10,marginTop:4},option:{borderWidth:1,borderColor:colors.line,borderRadius:17,padding:15,gap:4},plan:{borderWidth:1,borderColor:colors.line,borderRadius:20,padding:18,gap:7},active:{borderColor:colors.navy,backgroundColor:colors.navySoft},optionTitle:{fontSize:16,fontWeight:"900",color:colors.ink},activeText:{color:colors.navyDark},optionCopy:{fontSize:13,lineHeight:19,color:colors.muted},price:{fontSize:17,fontWeight:"900",color:colors.navyDark,marginTop:6},segment:{flexDirection:"row",backgroundColor:colors.navySoft,borderRadius:16,padding:4},segmentButton:{flex:1,padding:11,borderRadius:12,alignItems:"center"},segmentActive:{backgroundColor:"white"},segmentText:{fontSize:12,fontWeight:"800",color:colors.navyDark},summary:{borderWidth:1,borderColor:colors.line,borderRadius:20,padding:17,gap:14,marginTop:5},row:{gap:3,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:12},rowLabel:{fontSize:11,color:colors.muted},rowValue:{fontSize:16,fontWeight:"900",color:colors.ink},note:{backgroundColor:colors.navySoft,borderRadius:17,padding:16,gap:5},noteTitle:{fontSize:16,fontWeight:"900",color:colors.navyDark},noteText:{fontSize:13,lineHeight:20,color:colors.muted},actions:{flexDirection:"row",gap:10,marginTop:8},secondary:{minHeight:54,paddingHorizontal:20,borderWidth:1,borderColor:colors.line,borderRadius:15,alignItems:"center",justifyContent:"center"},secondaryText:{fontWeight:"900",color:colors.ink},primary:{minHeight:54,flex:1,borderRadius:15,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},primaryText:{color:"white",fontWeight:"900",fontSize:15}});
