import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors, money } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Product={id:string;title:string;description:string|null;price:number;images:string[];is_active:boolean};
export default function Preview(){const{store,loading}=useOwnerStore();const[products,setProducts]=useState<Product[]>([]);const load=useCallback(async()=>{if(!store||!supabase)return;const{data}=await supabase.from("products").select("id,title,description,price,images,is_active").eq("tenant_id",store.id).eq("is_active",true).order("sort_order");setProducts((data??[]) as Product[]);},[store]);useEffect(()=>{void load();},[load]);return <AppScreen section="Предпросмотр" store={store?.name}><View style={s.hero}><Text style={s.badge}>{store?.catalog_published?"ОПУБЛИКОВАН":"ТОЛЬКО ДЛЯ ВАС"}</Text><Text style={s.store}>{store?.name}</Text><Text style={s.copy}>Так покупатель видит основу вашего каталога.</Text></View>{loading?<ActivityIndicator color={colors.navy}/>:null}<Text style={ui.title}>Каталог</Text><View style={s.grid}>{products.map(product=><View key={product.id} style={s.product}><View style={s.image}><Text style={s.letter}>{product.title.slice(0,1).toUpperCase()}</Text></View><Text numberOfLines={2} style={s.title}>{product.title}</Text><Text style={s.price}>{money(product.price)}</Text></View>)}</View>{!loading&&!products.length?<View style={ui.card}><Text style={ui.cardTitle}>Добавьте первый товар</Text><Text style={ui.subtitle}>После сохранения он появится здесь и в веб-витрине.</Text></View>:null}</AppScreen>}
const s=StyleSheet.create({hero:{borderRadius:24,backgroundColor:colors.navyDark,padding:22,gap:7},badge:{color:"#C5D7E2",fontSize:10,fontWeight:"900",letterSpacing:1.3},store:{color:"white",fontSize:30,fontWeight:"900"},copy:{color:"#D8E4EA"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},product:{width:"48%",borderWidth:1,borderColor:colors.line,borderRadius:19,padding:12,backgroundColor:"white",gap:7},image:{aspectRatio:1,borderRadius:14,backgroundColor:colors.navySoft,alignItems:"center",justifyContent:"center"},letter:{fontSize:38,fontWeight:"900",color:colors.navy},title:{fontWeight:"900",color:colors.ink,minHeight:38},price:{fontWeight:"900",color:colors.navyDark}});
