import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Link, router, useLocalSearchParams } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { Image } from "expo-image";
import * as ImagePicker from "expo-image-picker";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
import { BottomNav } from "@/components/app-shell";

type Category={id:string;name:string};
const integer=(value:string)=>{const normalized=value.replace(/\D/g,"");return normalized?Number(normalized):0;};

export default function NewProductScreen(){
  const {tenantId,tenantName,vertical}=useLocalSearchParams<{tenantId:string;tenantName?:string;vertical?:string}>();
  const [title,setTitle]=useState("");const[description,setDescription]=useState("");const[price,setPrice]=useState("");const[oldPrice,setOldPrice]=useState("");const[stock,setStock]=useState("1");const[sku,setSku]=useState("");
  const[categories,setCategories]=useState<Category[]>([]);const[categoryId,setCategoryId]=useState<string|null>(null);const[saving,setSaving]=useState(false);
  const[ingredients,setIngredients]=useState("");const[weight,setWeight]=useState("");const[kcal,setKcal]=useState("");const[protein,setProtein]=useState("");const[fat,setFat]=useState("");const[carbs,setCarbs]=useState("");
  const[photos,setPhotos]=useState<ImagePicker.ImagePickerAsset[]>([]);
  useEffect(()=>{if(!tenantId||!supabase)return;void supabase.from("categories").select("id,name").eq("tenant_id",tenantId).eq("is_active",true).order("sort_order").then(({data})=>setCategories((data??[]) as Category[]));},[tenantId]);
  const choosePhotos=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert("Нужен доступ к фото","Разрешите выбрать фотографии товара.");const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],allowsMultipleSelection:true,selectionLimit:Math.max(1,5-photos.length),quality:.9});if(!result.canceled)setPhotos(current=>[...current,...result.assets].slice(0,5));};
  const save=async()=>{
    const amount=integer(price),previous=integer(oldPrice),qty=integer(stock);
    if(!tenantId||title.trim().length<2){Alert.alert("Проверьте название","Название должно содержать минимум 2 символа.");return;}
    if(amount<1){Alert.alert("Проверьте цену","Укажите цену товара в тенге.");return;}
    if(previous&&previous<amount){Alert.alert("Проверьте старую цену","Старая цена не может быть ниже текущей.");return;}
    if(qty<0||qty>100000000){Alert.alert("Проверьте остаток","Укажите корректное количество.");return;}
    setSaving(true);
    const uploaded:string[]=[];const paths:string[]=[];
    for(const photo of photos){try{if((photo.fileSize??0)>10*1024*1024)throw new Error();const ext=(photo.fileName?.split(".").pop()||"jpg").toLowerCase();const path=`${tenantId}/${Date.now()}-${Math.random().toString(36).slice(2,10)}.${ext}`;const bytes=await(await fetch(photo.uri)).arrayBuffer();const result=await supabase!.storage.from("product-images").upload(path,bytes,{contentType:photo.mimeType??"image/jpeg",upsert:false});if(result.error)throw result.error;paths.push(path);uploaded.push(supabase!.storage.from("product-images").getPublicUrl(path).data.publicUrl);}catch{if(paths.length)await supabase!.storage.from("product-images").remove(paths);setSaving(false);Alert.alert("Фото не загрузились","Используйте JPG, PNG или WebP до 10 МБ.");return;}}
    const parts=ingredients.split(",").map(value=>value.trim()).filter(Boolean).slice(0,30);const foodOptions={ingredients:parts.map((name,index)=>({id:`ingredient-${Date.now()}-${index}`,name,removable:true})),groups:[],nutrition:{weightGrams:Number(weight)||0,kcal:Number(kcal)||0,protein:Number(protein)||0,fat:Number(fat)||0,carbs:Number(carbs)||0}};
    const args={p_tenant_id:tenantId,p_title:title.trim(),p_description:description.trim(),p_price:amount,p_old_price:previous||null,p_category_id:categoryId,p_images:uploaded,p_is_active:true,p_variants:[{size:"",color:"",sku:sku.trim(),stock:qty}]};
    const {error}=vertical==="food"?await supabase!.rpc("create_food_product" as never,{...args,p_food_options:foodOptions} as never):await supabase!.rpc("create_product_with_variants",args);
    if(!error){const status=await supabase!.from("tenants").update({catalog_status:"ready"}).eq("id",tenantId).eq("catalog_status","building");if(status.error){setSaving(false);Alert.alert("Товар сохранён","Позиция создана, но этап запуска не обновился. Откройте каталог ещё раз.");router.replace("/catalog" as never);return;}}
    setSaving(false);
    if(error){if(paths.length)await supabase!.storage.from("product-images").remove(paths);Alert.alert("Не удалось сохранить","Проверьте данные и повторите. Товар не был создан.");return;}
    Alert.alert("Товар добавлен","Позиция сохранена в каталоге.",[{text:"Открыть каталог",onPress:()=>router.replace("/catalog" as never)}]);
  };
  return <SafeAreaView style={styles.page}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <Link accessibilityLabel="Назад" href={"/catalog" as never} style={styles.back}>‹</Link><Text style={styles.kicker}>НОВАЯ ПОЗИЦИЯ</Text><Text style={styles.title}>Добавить товар</Text><Text style={styles.subtitle}>{tenantName??"Ваш магазин"} · обязательны только название, цена и остаток.</Text>
    <View style={styles.card}><Field label="Фотографии · до 5"><Pressable onPress={()=>void choosePhotos()} style={styles.photoButton}><Text style={styles.photoButtonText}>{photos.length?`Выбрано: ${photos.length} · добавить ещё`:`＋ Добавить фото`}</Text></Pressable>{photos.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{photos.map((photo,index)=><Pressable key={`${photo.uri}-${index}`} onPress={()=>setPhotos(current=>current.filter((_,i)=>i!==index))}><Image source={{uri:photo.uri}} contentFit="cover" style={styles.photo}/><Text style={styles.removePhoto}>Убрать</Text></Pressable>)}</ScrollView>:null}</Field><Field label="Название *"><TextInput value={title} onChangeText={setTitle} maxLength={120} placeholder="Например, Круассан с сыром" placeholderTextColor="#87929A" style={styles.input}/></Field><Field label="Описание"><TextInput value={description} onChangeText={setDescription} maxLength={1200} multiline placeholder="Состав, вес, важные детали" placeholderTextColor="#87929A" style={[styles.input,styles.area]}/></Field>
      <View style={styles.row}><View style={{flex:1}}><Field label="Цена, ₸ *"><TextInput value={price} onChangeText={v=>setPrice(v.replace(/\D/g,""))} keyboardType="number-pad" placeholder="5000" placeholderTextColor="#87929A" style={styles.input}/></Field></View><View style={{flex:1}}><Field label="Старая цена, ₸"><TextInput value={oldPrice} onChangeText={v=>setOldPrice(v.replace(/\D/g,""))} keyboardType="number-pad" placeholder="Необязательно" placeholderTextColor="#87929A" style={styles.input}/></Field></View></View>
      <View style={styles.row}><View style={{flex:1}}><Field label="Остаток *"><TextInput value={stock} onChangeText={v=>setStock(v.replace(/\D/g,""))} keyboardType="number-pad" placeholder="1" placeholderTextColor="#87929A" style={styles.input}/></Field></View><View style={{flex:1}}><Field label="Артикул"><TextInput value={sku} onChangeText={setSku} autoCapitalize="characters" maxLength={80} placeholder="SKU-001" placeholderTextColor="#87929A" style={styles.input}/></Field></View></View>
      {categories.length>0&&<Field label="Категория"><View style={styles.chips}><Pressable onPress={()=>setCategoryId(null)} style={[styles.chip,categoryId===null&&styles.chipActive]}><Text style={[styles.chipText,categoryId===null&&styles.chipTextActive]}>Без категории</Text></Pressable>{categories.map(category=><Pressable key={category.id} onPress={()=>setCategoryId(category.id)} style={[styles.chip,categoryId===category.id&&styles.chipActive]}><Text style={[styles.chipText,categoryId===category.id&&styles.chipTextActive]}>{category.name}</Text></Pressable>)}</View></Field>}
      {vertical==="food"?<View style={styles.food}><Text style={styles.foodTitle}>Состав, вес и КБЖУ</Text><Text style={styles.noteText}>Необязательно. Ингредиенты перечислите через запятую; гость увидит состав в карточке блюда.</Text><Field label="Состав"><TextInput value={ingredients} onChangeText={setIngredients} maxLength={1200} multiline placeholder="Лаваш, говядина, томаты, соус" placeholderTextColor="#87929A" style={[styles.input,styles.area]}/></Field><View style={styles.row}><View style={{flex:1}}><Field label="Вес, г"><TextInput value={weight} onChangeText={v=>setWeight(v.replace(/\D/g,""))} keyboardType="number-pad" style={styles.input}/></Field></View><View style={{flex:1}}><Field label="Ккал"><TextInput value={kcal} onChangeText={v=>setKcal(v.replace(/\D/g,""))} keyboardType="number-pad" style={styles.input}/></Field></View></View><View style={styles.row}><View style={{flex:1}}><Field label="Белки, г"><TextInput value={protein} onChangeText={v=>setProtein(v.replace(/[^\d.]/g,""))} keyboardType="decimal-pad" style={styles.input}/></Field></View><View style={{flex:1}}><Field label="Жиры, г"><TextInput value={fat} onChangeText={v=>setFat(v.replace(/[^\d.]/g,""))} keyboardType="decimal-pad" style={styles.input}/></Field></View><View style={{flex:1}}><Field label="Углеводы, г"><TextInput value={carbs} onChangeText={v=>setCarbs(v.replace(/[^\d.]/g,""))} keyboardType="decimal-pad" style={styles.input}/></Field></View></View><Text style={styles.noteText}>Добавки и комбо можно настроить после создания, когда в меню уже есть товары для набора.</Text></View>:null}
      <Pressable disabled={saving} onPress={()=>{void save();}} style={[styles.save,saving&&{opacity:.55}]}>{saving?<ActivityIndicator color="white"/>:<Text style={styles.saveText}>Сохранить товар</Text>}</Pressable>
    </View>
  </ScrollView></KeyboardAvoidingView><BottomNav/></SafeAreaView>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{gap:8}}><Text style={styles.label}>{label}</Text>{children}</View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.stone},content:{padding:22,paddingBottom:120,gap:12},back:{color:colors.navy,fontWeight:"800",marginBottom:8},kicker:{color:colors.navy,fontSize:11,fontWeight:"900",letterSpacing:1.4},title:{fontSize:34,fontWeight:"900",color:colors.ink,letterSpacing:-1},subtitle:{color:colors.muted,fontSize:14,lineHeight:21},card:{marginTop:8,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:22,padding:18,gap:18},label:{fontSize:13,fontWeight:"800",color:colors.ink},input:{minHeight:50,borderWidth:1,borderColor:"#C9D3DA",borderRadius:13,paddingHorizontal:14,color:colors.ink,fontSize:16,backgroundColor:"white"},area:{minHeight:96,paddingTop:14,textAlignVertical:"top"},photoButton:{minHeight:50,borderRadius:13,borderWidth:1,borderColor:colors.line,backgroundColor:colors.navySoft,alignItems:"center",justifyContent:"center"},photoButtonText:{fontWeight:"900",color:colors.navyDark},photo:{width:88,height:88,borderRadius:13},removePhoto:{fontSize:10,textAlign:"center",color:colors.danger,marginTop:4,fontWeight:"800"},row:{flexDirection:"row",gap:10},chips:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderColor:colors.line,borderRadius:999,paddingHorizontal:12,paddingVertical:9},chipActive:{backgroundColor:colors.navy,borderColor:colors.navy},chipText:{fontSize:12,fontWeight:"700",color:colors.ink},chipTextActive:{color:"white"},food:{borderRadius:18,backgroundColor:"#F6F2FA",borderWidth:1,borderColor:"#E6DDF0",padding:14,gap:13},foodTitle:{fontSize:17,fontWeight:"900",color:colors.ink},noteText:{color:colors.muted,fontSize:12,lineHeight:18},save:{minHeight:52,borderRadius:14,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},saveText:{color:"white",fontSize:15,fontWeight:"900"}});

