import { useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";

export default function RegisterScreen(){
 const[name,setName]=useState("");const[business,setBusiness]=useState("");const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[pending,setPending]=useState(false);const[accepted,setAccepted]=useState(false);
 const submit=async()=>{if(!supabase)return;if(!accepted){Alert.alert("Нужно согласие","Примите оферту и политику конфиденциальности для создания аккаунта.");return;}if(name.trim().length<2||business.trim().length<2||!email.includes("@")||password.length<10||password!==confirm){Alert.alert("Проверьте данные","Укажите имя, название бизнеса, корректный email и одинаковый пароль от 10 символов.");return;}setPending(true);localStorage.setItem("dukenim_pending_business",business.trim());const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{display_name:name.trim(),business_name:business.trim()}}});setPending(false);if(error){Alert.alert("Регистрация не завершена",error.message.includes("registered")?"Этот email уже зарегистрирован. Войдите или восстановите пароль.":"Проверьте данные и повторите.");return;}if(data.session)router.replace("/setup-store" as never);else Alert.alert("Подтвердите email","Мы отправили письмо. После подтверждения вернитесь в приложение и войдите.",[{text:"Понятно",onPress:()=>router.replace("/")}]);};
 return <SafeAreaView style={s.page}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>← Вход</Text></Pressable><Text style={s.kicker}>7 ДНЕЙ БЕСПЛАТНО</Text><Text style={s.title}>Создайте свой магазин</Text><Text style={s.copy}>Один аккаунт для приложения и сайта. После регистрации выберите направление — каталог откроется сразу.</Text><View style={s.card}><Field label="Ваше имя"><TextInput value={name} onChangeText={setName} autoComplete="name" style={s.input} placeholder="Ерсат"/></Field><Field label="Название бизнеса"><TextInput value={business} onChangeText={setBusiness} style={s.input} placeholder="Моя кофейня"/></Field><Field label="Email"><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email" style={s.input} placeholder="name@example.com"/></Field><Field label="Пароль · минимум 10 символов"><TextInput value={password} onChangeText={setPassword} secureTextEntry autoComplete="new-password" style={s.input} placeholder="Придумайте пароль"/></Field><Field label="Повторите пароль"><TextInput value={confirm} onChangeText={setConfirm} secureTextEntry style={s.input} placeholder="Ещё раз"/></Field><Pressable onPress={()=>setAccepted(value=>!value)} style={s.accept}><View style={[s.box,accepted&&s.boxActive]}><Text style={s.check}>{accepted?"✓":""}</Text></View><Text style={s.acceptText}>Принимаю оферту и политику конфиденциальности Dukenim</Text></Pressable><Pressable disabled={pending} onPress={()=>void submit()} style={[s.button,pending&&{opacity:.6}]}>{pending?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>Создать аккаунт</Text>}</Pressable><Text style={s.legal}>Согласие сохраняется как явный выбор перед регистрацией.</Text></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <View style={{gap:7}}><Text style={s.label}>{label}</Text>{children}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:24,paddingBottom:48,gap:14},back:{color:colors.navy,fontWeight:"800"},kicker:{marginTop:14,color:colors.navy,fontSize:10,fontWeight:"900",letterSpacing:1.5},title:{fontSize:36,fontWeight:"900",letterSpacing:-1.3,color:colors.ink},copy:{fontSize:15,lineHeight:23,color:colors.muted},card:{marginTop:8,borderWidth:1,borderColor:colors.line,borderRadius:24,padding:18,gap:15},label:{fontSize:13,fontWeight:"800",color:colors.ink},input:{minHeight:53,borderWidth:1,borderColor:"#C9D3DA",borderRadius:14,paddingHorizontal:14,fontSize:16,color:colors.ink},button:{minHeight:54,borderRadius:14,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},buttonText:{color:"white",fontWeight:"900",fontSize:15},accept:{flexDirection:"row",alignItems:"center",gap:10},box:{width:24,height:24,borderWidth:1,borderColor:colors.line,borderRadius:7,alignItems:"center",justifyContent:"center"},boxActive:{backgroundColor:colors.navy,borderColor:colors.navy},check:{color:"white",fontWeight:"900"},acceptText:{flex:1,color:colors.muted,fontSize:12,lineHeight:18},legal:{fontSize:11,lineHeight:17,color:colors.muted,textAlign:"center"}});
