import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors } from "@/lib/theme";
import { loadOwnerContext, routeForStore } from "@/lib/owner";
import { supabase } from "@/lib/supabase";
const options=[{key:"food",label:"Еда и напитки",hint:"Ресторан, донер, выпечка, кофе"},{key:"fashion",label:"Одежда",hint:"Бутик, шоурум, аксессуары"},{key:"beauty",label:"Красота",hint:"Косметика и уход"},{key:"flowers",label:"Цветы",hint:"Букеты и подарки"},{key:"home",label:"Дом",hint:"Декор и товары для дома"},{key:"other",label:"Другое",hint:"Универсальный каталог"}] as const;
export default function SetupStore(){const[name,setName]=useState(localStorage.getItem("dukenim_pending_business")??"");const[vertical,setVertical]=useState<(typeof options)[number]["key"]>("food");const[pending,setPending]=useState(false);useEffect(()=>{void loadOwnerContext().then(c=>{if(c.stores.length)router.replace(routeForStore(c.stores[0]) as never);}).catch(()=>router.replace("/"));},[]);const create=async()=>{if(!supabase||name.trim().length<2){Alert.alert("Укажите название магазина");return;}setPending(true);const{data,error}=await supabase.rpc("create_mobile_owner_store" as never,{p_name:name.trim(),p_vertical:vertical,p_format:"catalog"} as never);setPending(false);if(error){Alert.alert("Не удалось создать магазин",error.message.includes("Confirm")?"Сначала подтвердите email.":"Проверьте данные и повторите.");return;}if(typeof data==="string")localStorage.setItem("dukenim_selected_store",data);localStorage.removeItem("dukenim_pending_business");router.replace("/onboarding" as never);};return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>СОЗДАНИЕ МАГАЗИНА</Text><Text style={s.title}>Как называется ваш бизнес?</Text><Text style={s.copy}>Начните здесь. Следующие шаги — формат, тариф и каталог — сохранятся в общей учётной записи Dukenim.</Text><View style={s.card}><Text style={s.label}>Название магазина</Text><TextInput value={name} onChangeText={setName} maxLength={80} placeholder="Например, Nurlanshop" style={s.input}/><Text style={s.label}>Что вы продаёте?</Text><View style={s.options}>{options.map(item=><Pressable key={item.key} onPress={()=>setVertical(item.key)} style={[s.option,vertical===item.key&&s.optionActive]}><Text style={[s.optionTitle,vertical===item.key&&s.optionTitleActive]}>{item.label}</Text><Text style={[s.optionHint,vertical===item.key&&s.optionHintActive]}>{item.hint}</Text></Pressable>)}</View><Pressable disabled={pending} onPress={()=>void create()} style={s.button}>{pending?<ActivityIndicator color="white"/>:<Text style={s.buttonText}>Продолжить настройку</Text>}</Pressable></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:24,paddingBottom:40,gap:14},kicker:{marginTop:14,color:colors.navy,fontSize:10,fontWeight:"900",letterSpacing:1.5},title:{fontSize:36,fontWeight:"900",color:colors.ink,letterSpacing:-1.2},copy:{color:colors.muted,fontSize:15,lineHeight:23},card:{borderWidth:1,borderColor:colors.line,borderRadius:24,padding:18,gap:14},label:{fontSize:13,fontWeight:"900",color:colors.ink},input:{minHeight:54,borderWidth:1,borderColor:colors.line,borderRadius:14,paddingHorizontal:14,fontSize:16},options:{gap:9},option:{padding:14,borderRadius:15,borderWidth:1,borderColor:colors.line,backgroundColor:"white"},optionActive:{borderColor:colors.navy,backgroundColor:colors.navySoft},optionTitle:{fontWeight:"900",color:colors.ink},optionTitleActive:{color:colors.navyDark},optionHint:{fontSize:12,color:colors.muted,marginTop:3},optionHintActive:{color:colors.navy},button:{minHeight:54,borderRadius:14,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center",marginTop:4},buttonText:{color:"white",fontWeight:"900"}});
