import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { colors, money } from "@/lib/theme";
import { supabase } from "@/lib/supabase";

type Permissions=Record<string,"none"|"read"|"write">;
type Access={id:string;title:string;permissions:Permissions;active:boolean};
type Shop={id:string;name:string};
type Order={id:string;order_number:number|null;status:string;total:number;delivery_method:string|null};
const labels:Record<string,string>={orders:"Заказы",catalog:"Каталог",stock:"Склад",customers:"Клиенты",analytics:"Аналитика",studio:"AI Studio"};
const statusLabels:Record<string,string>={new:"Новый",confirmed:"Подтверждён",assembled:"Собран",delivering:"В доставке",done:"Готов",cancelled:"Отменён"};
const transitions:Record<string,string[]>={new:["confirmed","cancelled"],confirmed:["assembled","cancelled"],assembled:["delivering","done","cancelled"],delivering:["done"]};

export default function StaffScreen(){
 const[accesses,setAccesses]=useState<Access[]>([]),[shops,setShops]=useState<Shop[]>([]),[orders,setOrders]=useState<Record<string,Order[]>>({}),[modules,setModules]=useState<Record<string,unknown[]>>({}),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{const client=supabase;if(!client)return;const[{data:members,error},{data:directory}]=await Promise.all([client.from("staff_access").select("id,title,permissions,active").eq("active",true),client.rpc("staff_directory" as never)]);if(error){Alert.alert("Доступ недоступен","Попросите владельца проверить приглашение.");setLoading(false);return;}const next=(members??[]) as Access[];setAccesses(next);setShops(Array.isArray(directory)?directory as Shop[]:[]);const orderPairs=await Promise.all(next.filter(a=>a.permissions.orders!=="none").map(async a=>[a.id,(await client.rpc("staff_orders" as never,{p_access:a.id} as never)).data] as const));setOrders(Object.fromEntries(orderPairs.map(([id,data])=>[id,Array.isArray(data)?data:[]])));const modulePairs=await Promise.all(next.flatMap(a=>["catalog","stock","customers","analytics"].filter(module=>a.permissions[module]&&a.permissions[module]!=="none").map(async module=>[`${a.id}:${module}`,(await client.rpc("staff_module_data" as never,{p_access:a.id,p_module:module} as never)).data] as const)));setModules(Object.fromEntries(modulePairs.map(([key,data])=>[key,Array.isArray(data)?data:[]])));setLoading(false);setRefreshing(false);},[]);
 useEffect(()=>{void load();},[load]);
 const signOut=async()=>{await supabase?.auth.signOut();router.replace("/");};
 if(loading)return <View style={s.loader}><ActivityIndicator color={colors.navy}/></View>;
 return <SafeAreaView style={s.page}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load();}}/>} contentContainerStyle={s.content}><Text style={s.kicker}>РАБОЧИЙ КАБИНЕТ</Text><Text style={s.title}>Ваши магазины</Text><Text style={s.copy}>Здесь доступны только разделы и действия, которые открыл владелец. Изменения сразу синхронизируются с сайтом.</Text>{!accesses.length?<View style={s.card}><Text style={s.cardTitle}>Активного доступа нет</Text><Text style={s.copy}>Попросите владельца проверить email приглашения или восстановить доступ.</Text></View>:accesses.map(access=><StaffShop key={access.id} access={access} shop={shops.find(x=>x.id===access.id)} orders={orders[access.id]??[]} modules={modules} reload={load}/>) }<Pressable onPress={()=>void signOut()} style={s.outline}><Text style={s.outlineText}>Выйти</Text></Pressable></ScrollView></SafeAreaView>;
}
function StaffShop({access,shop,orders,modules,reload}:{access:Access;shop?:Shop;orders:Order[];modules:Record<string,unknown[]>;reload:()=>Promise<void>}){const visible=useMemo(()=>Object.keys(labels).filter(key=>access.permissions[key]&&access.permissions[key]!=="none"),[access]);const change=async(order:Order,next:string)=>{if(!supabase)return;const{error}=await supabase.rpc("staff_order_status" as never,{p_access:access.id,p_order:order.id,p_expected:order.status,p_status:next} as never);if(error)Alert.alert("Статус не изменён","Обновите экран: заказ или ваши права уже изменились.");else await reload();};return <View style={s.shop}><View style={s.shopHero}><Text style={s.role}>{access.title}</Text><Text style={s.shopName}>{shop?.name??"Магазин"}</Text><Text style={s.permissions}>{visible.map(key=>labels[key]).join(" · ")||"Права ещё не назначены"}</Text></View>{access.permissions.orders!=="none"&&<View style={s.section}><Text style={s.cardTitle}>Заказы</Text>{orders.length?orders.map(order=><View key={order.id} style={s.order}><View style={{flex:1,gap:3}}><Text style={s.orderTitle}>№{order.order_number??"—"} · {money(order.total)}</Text><Text style={s.meta}>{statusLabels[order.status]??order.status} · {order.delivery_method??"получение не указано"}</Text></View>{access.permissions.orders==="write"&&transitions[order.status]?.map(next=><Pressable key={next} onPress={()=>void change(order,next)} style={s.small}><Text style={s.smallText}>{statusLabels[next]}</Text></Pressable>)}</View>):<Text style={s.copy}>Заказов пока нет.</Text>}</View>}{visible.filter(key=>!["orders","studio"].includes(key)).map(key=>{const count=modules[`${access.id}:${key}`]?.length??0;return <View key={key} style={s.module}><View><Text style={s.cardTitle}>{labels[key]}</Text><Text style={s.meta}>{count} записей · {access.permissions[key]==="write"?"можно изменять":"только просмотр"}</Text></View><Text style={s.count}>{count}</Text></View>})}{access.permissions.studio!=="none"&&<View style={s.card}><Text style={s.cardTitle}>AI Studio</Text><Text style={s.copy}>AI Studio сотрудника доступна на сайте с теми же ограничениями владельца. Нативный чат будет добавлен после отдельной проверки применения дизайна.</Text></View>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"white"},content:{padding:22,paddingBottom:50,gap:15},loader:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"white"},kicker:{fontSize:10,fontWeight:"900",letterSpacing:1.5,color:colors.navy},title:{fontSize:35,fontWeight:"900",color:colors.ink},copy:{fontSize:14,lineHeight:21,color:colors.muted},shop:{gap:11},shopHero:{backgroundColor:colors.navyDark,borderRadius:23,padding:20,gap:6},role:{color:"#C3D5E0",fontSize:10,fontWeight:"900",letterSpacing:1.2},shopName:{color:"white",fontSize:26,fontWeight:"900"},permissions:{color:"#D6E2E9",fontSize:12,lineHeight:18},section:{borderWidth:1,borderColor:colors.line,borderRadius:20,padding:16,gap:10},card:{borderWidth:1,borderColor:colors.line,borderRadius:20,padding:17,gap:8},cardTitle:{fontSize:18,fontWeight:"900",color:colors.ink},order:{gap:8,borderTopWidth:1,borderTopColor:colors.line,paddingTop:10},orderTitle:{fontWeight:"900",color:colors.ink},meta:{fontSize:12,lineHeight:18,color:colors.muted},small:{alignSelf:"flex-start",backgroundColor:colors.navySoft,borderRadius:10,paddingHorizontal:10,paddingVertical:8},smallText:{fontSize:11,fontWeight:"900",color:colors.navyDark},module:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16},count:{fontSize:24,fontWeight:"900",color:colors.navy},outline:{minHeight:52,borderWidth:1,borderColor:colors.line,borderRadius:14,alignItems:"center",justifyContent:"center"},outlineText:{fontWeight:"900",color:colors.navyDark}});
