import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Row={id:string;product_id:string;stock_qty:number;size:string|null;sku:string|null;products:{title:string}|null};
export default function Stock(){const{store,loading}=useOwnerStore();const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error}=await supabase.from("product_variants").select("id,product_id,stock_qty,size,sku,products(title)").eq("tenant_id",store.id).order("product_id");if(error)setMessage("Не удалось загрузить остатки.");else{setMessage("");setRows((data??[]) as unknown as Row[]);}},[store]);useEffect(()=>{void load();},[load]);const save=async(row:Row,value:number)=>{if(!store||!supabase||!Number.isInteger(value)||value<0||value>1_000_000){Alert.alert("Проверьте количество","Введите целое число от 0 до 1 000 000.");return;}if(value===row.stock_qty)return;setBusy(row.id);const{error}=await supabase.rpc("set_variant_stock",{p_tenant_id:store.id,p_variant_id:row.id,p_target:value});if(error)Alert.alert("Остаток не изменён","Обновите экран и повторите.");else await load();setBusy("");};return <AppScreen section="Склад" store={store?.name}><Text style={ui.title}>Остатки</Text><Text style={ui.subtitle}>Изменение создаёт корректировку в журнале stock_movements. Значение синхронизируется с сайтом.</Text>{store?.business_vertical==="food"?<Pressable onPress={()=>router.push("/materials" as never)} style={s.materials}><View style={{flex:1}}><Text style={s.materialsTitle}>Склад сырья</Text><Text style={s.meta}>Молоко, кофе, тесто, соусы и техкарты блюд</Text></View><Text style={s.materialsArrow}>›</Text></Pressable>:null}{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<View style={{gap:10}}>{rows.map(row=><View key={row.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{row.products?.title??"Товар"}</Text><Text style={s.meta}>{row.size||row.sku||"Основной вариант"}</Text></View><Stepper value={row.stock_qty} disabled={busy===row.id} onSave={value=>void save(row,value)}/></View>)}</View>{!loading&&!rows.length?<View style={ui.card}><Text style={ui.cardTitle}>Нет товарных вариантов</Text><Text style={ui.subtitle}>Сначала добавьте товар в каталоге.</Text></View>:null}</AppScreen>}
function Stepper({value,onSave,disabled}:{value:number;onSave:(value:number)=>void;disabled:boolean}){const[text,setText]=useState(String(value));useEffect(()=>setText(String(value)),[value]);const changed=text!==String(value);const valid=text.length>0&&Number(text)<=1_000_000;return <View style={s.stepContainer}><View style={s.step}><Pressable accessibilityLabel="Уменьшить остаток" disabled={disabled||changed||value===0} onPress={()=>onSave(value-1)} style={s.stepButton}><Text style={s.stepText}>−</Text></Pressable><TextInput accessibilityLabel="Количество на складе" value={text} editable={!disabled} onChangeText={v=>setText(v.replace(/\D/g,"").slice(0,7))} keyboardType="number-pad" selectTextOnFocus style={s.qty}/><Pressable accessibilityLabel="Увеличить остаток" disabled={disabled||changed||value>=1_000_000} onPress={()=>onSave(value+1)} style={s.stepButton}><Text style={s.stepText}>＋</Text></Pressable></View>{changed?<View style={s.editActions}><Pressable onPress={()=>setText(String(value))} disabled={disabled}><Text style={s.cancelText}>Отмена</Text></Pressable><Pressable onPress={()=>onSave(Number(text))} disabled={disabled||!valid} style={[s.saveButton,(!valid||disabled)&&s.saveDisabled]}><Text style={s.saveText}>Сохранить</Text></Pressable></View>:null}</View>}
const s=StyleSheet.create({materials:{minHeight:78,borderRadius:18,backgroundColor:colors.navyDark,padding:16,flexDirection:"row",alignItems:"center",gap:10},materialsTitle:{color:"white",fontSize:17,fontWeight:"900"},materialsArrow:{color:"white",fontSize:30},row:{flexDirection:"row",alignItems:"center",gap:12,padding:15,borderWidth:1,borderColor:colors.line,borderRadius:17,backgroundColor:"white"},name:{fontWeight:"900",color:colors.ink,fontSize:16},meta:{fontSize:12,color:colors.muted,marginTop:4},stepContainer:{alignItems:"flex-end",gap:7},step:{flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:colors.line,borderRadius:13,overflow:"hidden"},stepButton:{width:39,height:42,alignItems:"center",justifyContent:"center",backgroundColor:colors.navySoft},stepText:{fontSize:19,fontWeight:"900",color:colors.navyDark},qty:{width:50,textAlign:"center",fontWeight:"900",color:colors.ink},editActions:{flexDirection:"row",alignItems:"center",gap:8},cancelText:{fontSize:11,fontWeight:"800",color:colors.muted},saveButton:{borderRadius:9,backgroundColor:colors.navy,paddingHorizontal:8,paddingVertical:8},saveDisabled:{opacity:.45},saveText:{fontSize:11,fontWeight:"900",color:"white"}});
