import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Row={id:string;product_id:string;stock_qty:number;size:string|null;sku:string|null;products:{title:string}|null};
export default function Stock(){const{store,loading}=useOwnerStore();const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error}=await supabase.from("product_variants").select("id,product_id,stock_qty,size,sku,products(title)").eq("tenant_id",store.id).order("product_id");if(error)setMessage("Не удалось загрузить остатки.");else setRows((data??[]) as unknown as Row[]);},[store]);useEffect(()=>{void load();},[load]);const save=async(row:Row,value:number)=>{if(!store||!supabase||value<0||value>1_000_000)return;setBusy(row.id);const{error}=await supabase.rpc("set_variant_stock",{p_tenant_id:store.id,p_variant_id:row.id,p_target:value});setBusy("");if(error)Alert.alert("Остаток не изменён","Обновите экран и повторите.");else setRows(current=>current.map(item=>item.id===row.id?{...item,stock_qty:value}:item));};return <AppScreen section="Склад" store={store?.name}><Text style={ui.title}>Остатки</Text><Text style={ui.subtitle}>Изменение создаёт корректировку в журнале stock_movements. Значение синхронизируется с сайтом.</Text>{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<View style={{gap:10}}>{rows.map(row=><View key={row.id} style={s.row}><View style={{flex:1}}><Text style={s.name}>{row.products?.title??"Товар"}</Text><Text style={s.meta}>{row.size||row.sku||"Основной вариант"}</Text></View><Stepper value={row.stock_qty} disabled={busy===row.id} onSave={value=>void save(row,value)}/></View>)}</View>{!loading&&!rows.length?<View style={ui.card}><Text style={ui.cardTitle}>Нет товарных вариантов</Text><Text style={ui.subtitle}>Сначала добавьте товар в каталоге.</Text></View>:null}</AppScreen>}
function Stepper({value,onSave,disabled}:{value:number;onSave:(value:number)=>void;disabled:boolean}){const[text,setText]=useState(String(value));useEffect(()=>setText(String(value)),[value]);return <View style={s.step}><Pressable disabled={disabled||value===0} onPress={()=>onSave(Math.max(0,value-1))} style={s.stepButton}><Text style={s.stepText}>−</Text></Pressable><TextInput value={text} onChangeText={v=>setText(v.replace(/\D/g,"").slice(0,7))} onEndEditing={()=>onSave(Number(text||0))} keyboardType="number-pad" selectTextOnFocus style={s.qty}/><Pressable disabled={disabled} onPress={()=>onSave(value+1)} style={s.stepButton}><Text style={s.stepText}>＋</Text></Pressable></View>}
const s=StyleSheet.create({row:{flexDirection:"row",alignItems:"center",gap:12,padding:15,borderWidth:1,borderColor:colors.line,borderRadius:17,backgroundColor:"white"},name:{fontWeight:"900",color:colors.ink,fontSize:16},meta:{fontSize:12,color:colors.muted,marginTop:4},step:{flexDirection:"row",alignItems:"center",borderWidth:1,borderColor:colors.line,borderRadius:13,overflow:"hidden"},stepButton:{width:39,height:42,alignItems:"center",justifyContent:"center",backgroundColor:colors.navySoft},stepText:{fontSize:19,fontWeight:"900",color:colors.navyDark},qty:{width:50,textAlign:"center",fontWeight:"900",color:colors.ink}});
