import {useCallback,useEffect,useRef,useState} from "react";
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View} from "react-native";
import {EditorScreen} from "@/components/editor-screen";
import {ui} from "@/components/app-shell";
import {useOwnerStore} from "@/lib/use-owner-store";
import {colors} from "@/lib/theme";
import {supabase} from "@/lib/supabase";
type Message={id:string;from_role:"owner"|"superadmin";text:string;created_at:string;read_at?:string|null};
export default function Support(){const{store}=useOwnerStore();const[rows,setRows]=useState<Message[]>([]),[text,setText]=useState(""),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState("");const channel=useRef<ReturnType<NonNullable<typeof supabase>["channel"]>|null>(null);const load=useCallback(async()=>{if(!store||!supabase)return;const{data,error:readError}=await supabase.from("messages").select("id,from_role,text,created_at,read_at").eq("tenant_id",store.id).is("request_id",null).order("created_at");if(readError)setError("Не удалось загрузить чат.");else{setRows((data??[]) as Message[]);await supabase.rpc("mark_general_support_read" as never,{p_tenant:store.id} as never);}setLoading(false);},[store]);useEffect(()=>{void load();if(!store||!supabase)return;channel.current=supabase.channel(`mobile-support-${store.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`tenant_id=eq.${store.id}`},()=>void load()).subscribe();return()=>{if(channel.current)void supabase?.removeChannel(channel.current);};},[load,store]);const send=async()=>{const value=text.trim();if(!store||!supabase||value.length<2||sending)return;setSending(true);setError("");const{error:sendError}=await supabase.from("messages").insert({tenant_id:store.id,request_id:null,from_role:"owner",text:value});setSending(false);if(sendError)setError("Сообщение не отправлено. Повторите попытку.");else{setText("");await load();}};return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==="ios"?"padding":undefined}><EditorScreen title="Поддержка" subtitle={store?.name}><Text style={ui.title}>Чат с Dukenim</Text><Text style={ui.subtitle}>Сообщения синхронизируются с кабинетом суперадминистратора. Никогда не отправляйте сюда пароли, коды подтверждения и банковские ключи.</Text>{loading?<ActivityIndicator color={colors.navy}/>:rows.map(row=><View key={row.id} style={[s.bubble,row.from_role==="owner"?s.owner:s.support]}><Text style={[s.message,row.from_role==="owner"&&{color:"white"}]}>{row.text}</Text><Text style={[s.time,row.from_role==="owner"&&{color:"#D7E5EC"}]}>{new Date(row.created_at).toLocaleString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}{row.from_role==="owner"?row.read_at?"  ✓✓":"  ✓":""}</Text></View>)}{!loading&&!rows.length?<View style={ui.card}><Text style={ui.cardTitle}>Мы на связи</Text><Text style={ui.subtitle}>Опишите задачу. Ответ появится здесь с отметкой о прочтении.</Text></View>:null}{error?<Text style={ui.error}>{error}</Text>:null}<View style={s.composer}><TextInput style={s.input} value={text} onChangeText={setText} multiline maxLength={3000} placeholder="Сообщение…"/><Pressable disabled={sending||text.trim().length<2} onPress={()=>void send()} style={[s.send,(sending||text.trim().length<2)&&{opacity:.4}]}><Text style={s.sendText}>↑</Text></Pressable></View></EditorScreen></KeyboardAvoidingView>}
const s=StyleSheet.create({bubble:{maxWidth:"88%",borderRadius:19,paddingHorizontal:14,paddingVertical:11,gap:5},owner:{alignSelf:"flex-end",backgroundColor:colors.navy,borderBottomRightRadius:6},support:{alignSelf:"flex-start",backgroundColor:"#F1F5F7",borderBottomLeftRadius:6},message:{fontSize:15,lineHeight:21,color:colors.ink},time:{fontSize:9,color:colors.muted,alignSelf:"flex-end"},composer:{minHeight:58,borderWidth:1,borderColor:colors.line,borderRadius:29,padding:7,flexDirection:"row",alignItems:"flex-end",gap:7},input:{flex:1,minHeight:44,maxHeight:110,paddingHorizontal:8,paddingVertical:11,fontSize:15,color:colors.ink},send:{width:44,height:44,borderRadius:22,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center"},sendText:{fontSize:23,fontWeight:"900",color:"white"}});
