import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, Share, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { AppScreen, ui } from "@/components/app-shell";
import { useOwnerStore } from "@/lib/use-owner-store";
import { colors, site } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
type Level="none"|"read"|"write";
type Permissions={orders:Level;catalog:Level;stock:Level;customers:Level;analytics:"none"|"read";studio:Level};
type Member={id:string;title:string;permissions:Permissions;active:boolean;notify_orders:boolean;revision:number;created_at:string};
type Invite={id:string;email:string;title:string;expires_at:string;accepted_at:string|null;revoked_at:string|null};
const manager:Permissions={orders:"write",catalog:"write",stock:"write",customers:"read",analytics:"read",studio:"write"};
const viewer:Permissions={orders:"read",catalog:"read",stock:"read",customers:"read",analytics:"read",studio:"read"};

export default function Team(){
 const{store,loading}=useOwnerStore();const[members,setMembers]=useState<Member[]>([]);const[invites,setInvites]=useState<Invite[]>([]);const[email,setEmail]=useState("");const[title,setTitle]=useState("Менеджер");const[write,setWrite]=useState(true);const[pending,setPending]=useState(false);const[message,setMessage]=useState("");
 const load=useCallback(async()=>{if(!store||!supabase)return;const[a,b]=await Promise.all([supabase.from("staff_access").select("id,title,permissions,active,notify_orders,revision,created_at").eq("tenant_id",store.id).order("created_at"),supabase.from("staff_invitations").select("id,email,title,expires_at,accepted_at,revoked_at").eq("tenant_id",store.id).order("created_at",{ascending:false})]);if(a.error||b.error)setMessage("Не удалось загрузить команду.");else{setMembers((a.data??[]) as unknown as Member[]);setInvites((b.data??[]) as Invite[]);}},[store]);
 useEffect(()=>{void load();},[load]);
 const invite=async()=>{if(!store||!supabase||!email.includes("@")||title.trim().length<1){Alert.alert("Проверьте email и должность");return;}setPending(true);const recipient=email.trim();const{data:{session}}=await supabase.auth.getSession();try{const response=await fetch(`${site}/api/mobile/team`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token??""}`},body:JSON.stringify({tenantId:store.id,email:recipient,title:title.trim(),permissions:write?manager:viewer})});const body=await response.json() as{url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error||"Не удалось создать ссылку.");setEmail("");await load();await Share.share({title:"Приглашение в Dukenim",message:`Вас пригласили в команду ${store.name}. Откройте ссылку, зарегистрируйтесь с адресом ${recipient} и придумайте пароль:\n${body.url}`});}catch(e){Alert.alert("Приглашение не создано",e instanceof Error?e.message:"Повторите позже.");}finally{setPending(false);}};
 const update=async(member:Member,changes:{active:boolean;title:string;permissions:Permissions})=>{if(!store||!supabase)return;const{error}=await supabase.rpc("manage_staff",{p_tenant:store.id,p_action:"update",p_data:{id:member.id,revision:member.revision,title:changes.title,permissions:changes.permissions,active:changes.active,notify_orders:changes.active&&changes.permissions.orders!=="none"&&member.notify_orders}});if(error)Alert.alert("Доступ не изменён","Обновите список и повторите.");else{await load();Alert.alert("Права сохранены");}};
 const remove=(member:Member)=>Alert.alert("Удалить сотрудника?","Доступ перестанет работать сразу.",[{text:"Отмена",style:"cancel"},{text:"Удалить",style:"destructive",onPress:async()=>{if(!store||!supabase)return;const{error}=await supabase.rpc("manage_staff",{p_tenant:store.id,p_action:"remove",p_data:{id:member.id}});if(error)Alert.alert("Не удалось удалить");else await load();}}]);
 const revoke=async(inviteId:string)=>{if(!store||!supabase)return;const{error}=await supabase.rpc("manage_staff",{p_tenant:store.id,p_action:"revoke_invite",p_data:{id:inviteId}});if(error)Alert.alert("Не удалось отозвать ссылку");else await load();};
 return <AppScreen section="Сотрудники" store={store?.name}><Text style={ui.title}>Команда и доступ</Text><Text style={ui.subtitle}>Создайте ссылку и отправьте её лично. Сотрудник регистрируется с указанным email и придумывает свой пароль. Ссылка действует 48 часов.</Text>{loading?<ActivityIndicator color={colors.navy}/>:null}{message?<Text style={ui.error}>{message}</Text>:null}<View style={ui.card}><Text style={ui.cardTitle}>Пригласить сотрудника</Text><Text style={ui.label}>Email сотрудника</Text><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" style={ui.input} placeholder="employee@example.com"/><Text style={ui.label}>Должность</Text><TextInput value={title} onChangeText={setTitle} style={ui.input} placeholder="Менеджер"/><View style={s.permission}><View style={{flex:1}}><Text style={s.name}>Может изменять</Text><Text style={s.meta}>{write?"Заказы, каталог, склад и AI Studio":"Только просмотр доступных разделов"}</Text></View><Switch value={write} onValueChange={setWrite} trackColor={{false:"#D7DEE3",true:colors.navy}}/></View><Pressable disabled={pending} onPress={()=>void invite()} style={ui.button}>{pending?<ActivityIndicator color="white"/>:<Text style={ui.buttonText}>Создать и отправить ссылку</Text>}</Pressable></View><Text style={s.heading}>Сотрудники · {members.length}</Text>{members.map(member=><MemberEditor key={`${member.id}-${member.revision}`} member={member} onSave={changes=>void update(member,changes)} onRemove={()=>remove(member)}/>)}<Text style={s.heading}>Приглашения</Text>{invites.filter(i=>!i.accepted_at&&!i.revoked_at&&new Date(i.expires_at)>new Date()).map(invite=><View key={invite.id} style={s.invite}><View style={{flex:1}}><Text style={s.name}>{invite.email}</Text><Text style={s.meta}>{invite.title} · до {new Date(invite.expires_at).toLocaleString("ru-RU")}</Text></View><Pressable onPress={()=>void revoke(invite.id)}><Text style={s.danger}>Отозвать</Text></Pressable></View>)}</AppScreen>;
}

function MemberEditor({member,onSave,onRemove}:{member:Member;onSave:(value:{active:boolean;title:string;permissions:Permissions})=>void;onRemove:()=>void}){const[active,setActive]=useState(member.active);const[title,setTitle]=useState(member.title);const[permissions,setPermissions]=useState(member.permissions);const set=(key:keyof Permissions,value:Level)=>setPermissions(current=>({...current,[key]:key==="analytics"&&value==="write"?"read":value}));return <View style={ui.card}><View style={s.top}><TextInput value={title} onChangeText={setTitle} maxLength={80} style={[ui.input,{flex:1}]}/><Switch value={active} onValueChange={setActive} trackColor={{false:"#D7DEE3",true:colors.navy}}/></View><Text style={s.meta}>{active?"Доступ включён":"Доступ приостановлен"} · версия прав {member.revision}</Text>{(["orders","catalog","stock","customers","analytics","studio"] as (keyof Permissions)[]).map(key=><View key={key} style={s.accessRow}><Text style={s.accessName}>{({orders:"Заказы",catalog:"Каталог",stock:"Склад",customers:"Клиенты",analytics:"Аналитика",studio:"AI Studio"} as Record<string,string>)[key]}</Text><View style={s.levels}>{(["none","read",...(key==="analytics"?[]:["write"])] as Level[]).map(level=><Pressable key={level} onPress={()=>set(key,level)} style={[s.level,permissions[key]===level&&s.levelActive]}><Text style={[s.levelText,permissions[key]===level&&s.levelTextActive]}>{level==="none"?"Нет":level==="read"?"Просмотр":"Изменение"}</Text></Pressable>)}</View></View>)}<Pressable onPress={()=>onSave({active,title:title.trim(),permissions})} style={ui.button}><Text style={ui.buttonText}>Сохранить права</Text></Pressable><Pressable onPress={onRemove}><Text style={s.danger}>Удалить доступ</Text></Pressable></View>}
const s=StyleSheet.create({permission:{flexDirection:"row",alignItems:"center",gap:12,backgroundColor:colors.navySoft,borderRadius:14,padding:13},name:{fontWeight:"900",color:colors.ink,fontSize:16},meta:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:3},heading:{fontWeight:"900",color:colors.ink,fontSize:20,marginTop:4},top:{flexDirection:"row",alignItems:"center",gap:10},danger:{color:colors.danger,fontWeight:"900",fontSize:13},invite:{flexDirection:"row",alignItems:"center",gap:10,borderWidth:1,borderColor:colors.line,borderRadius:17,padding:15,backgroundColor:"white"},accessRow:{gap:8,borderTopWidth:1,borderTopColor:colors.line,paddingTop:10},accessName:{fontWeight:"800",color:colors.ink},levels:{flexDirection:"row",gap:6},level:{flex:1,borderWidth:1,borderColor:colors.line,borderRadius:10,paddingVertical:8,alignItems:"center"},levelActive:{backgroundColor:colors.navySoft,borderColor:colors.navy},levelText:{fontSize:10,fontWeight:"800",color:colors.muted},levelTextActive:{color:colors.navyDark}});
