"use client";
import {useActionState} from "react";
import {editStaffRecord} from "./actions";
export function ModuleRecord({access,module,record,write}:{access:string;module:string;record:Record<string,unknown>;write:boolean}){
 const[state,action,pending]=useActionState(editStaffRecord,{});
 const text=(key:string)=>String(record[key]??"");
 return <form action={action} className="space-y-3 rounded-xl border bg-white p-4"><input type="hidden" name="access" value={access}/><input type="hidden" name="module" value={module}/><input type="hidden" name="id" value={text("id")}/>
 <fieldset disabled={!write||pending} className="space-y-3">
 {module==="catalog"?<><input type="hidden" name="expected_price" value={text("price")}/><input type="hidden" name="expected_title" value={text("title")}/><label className="block">Название<input name="title" defaultValue={text("title")} required maxLength={200} className="block w-full rounded-lg border p-2"/></label><label className="block">Описание<textarea name="description" defaultValue={text("description")} maxLength={4000} className="block w-full rounded-lg border p-2"/></label><label className="block">Цена, ₸<input type="number" name="price" min={0} max={2000000000} required defaultValue={text("price")} className="block rounded-lg border p-2"/></label><label className="flex gap-2"><input type="checkbox" name="active" defaultChecked={Boolean(record.is_active)}/>Товар доступен</label></>:module==="stock"?<><p>{text("title")} · {text("size")} {text("color")}</p><input type="hidden" name="expected" value={text("stock_qty")}/><label>Фактическое количество<input name="quantity" type="number" min={0} max={9999999} required defaultValue={text("stock_qty")} className="block rounded-lg border p-2"/></label><p className="text-xs">Изменение записывается в журнал движений склада.</p></>:module==="customers"?<><input type="hidden" name="expected_phone" value={text("phone")}/><label className="block">Имя<input name="name" required maxLength={100} defaultValue={text("name")} className="block rounded-lg border p-2"/></label><label className="block">Телефон<input name="phone" required maxLength={30} defaultValue={text("phone")} className="block rounded-lg border p-2"/></label></>:<><p>{text("title")}</p><p>{text("count")} заказов · {Number(record.total??0).toLocaleString("ru-RU")} ₸</p></>}
 {write&&<button className="rounded-lg bg-neutral-900 px-4 py-2 text-white">Сохранить</button>}</fieldset>{state.error&&<p role="alert">{state.error}</p>}{state.success&&<p role="status">{state.success}</p>}</form>;
}
