import {afterEach,beforeEach,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({cookie:vi.fn(),admin:vi.fn(),rpc:vi.fn(),identity:vi.fn()}));
vi.mock("next/headers",()=>({cookies:async()=>({get:mocks.cookie})}));
vi.mock("@/lib/supabase/admin",()=>({createAdminClient:mocks.admin}));
vi.mock("@/lib/buyer-identity",()=>({buyerIdentity:mocks.identity,setBuyerCookie:vi.fn()}));
vi.mock("@/lib/loyalty-db",()=>({loyaltyClient:()=>({rpc:mocks.rpc})}));
import {GET} from "./route";
import {signGuestOrders} from "@/lib/guest-orders";
const tenant="11111111-1111-4111-8111-111111111111",id="22222222-2222-4222-8222-222222222222";
afterEach(()=>vi.unstubAllEnvs());
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("SUPABASE_SERVICE_ROLE_KEY","fixture-signing-key");mocks.identity.mockResolvedValue({userId:"verified-user",hash:"a".repeat(64),token:"b".repeat(64)});mocks.admin.mockReturnValue({from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{id:tenant}})})})})});mocks.rpc.mockResolvedValue({data:{orders:[]},error:null});});
it("never trusts a forged receipt and scopes history to verified identity",async()=>{mocks.cookie.mockReturnValue({value:"forged"});const response=await GET(new Request("https://example.test/api/my-orders?slug=shop&userId=attacker"));expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith("claim_buyer_orders",{p_tenant:tenant,p_user:"verified-user",p_guest_hash:"a".repeat(64),p_receipts:[]});expect(response.headers.get("cache-control")).toContain("no-store");});
it("never transfers a signed receipt from another tenant",async()=>{mocks.cookie.mockReturnValue({value:signGuestOrders([{id,tenant:"33333333-3333-4333-8333-333333333333",expires:Date.now()+10000}],"fixture-signing-key")});await GET(new Request("https://example.test/api/my-orders?slug=shop"));expect(mocks.rpc).toHaveBeenCalledWith("claim_buyer_orders",expect.objectContaining({p_receipts:[]}));});
it("migrates a verified legacy receipt and paginates server history",async()=>{mocks.cookie.mockReturnValue({value:signGuestOrders([{id,tenant,expires:Date.now()+10000}],"fixture-signing-key")});const response=await GET(new Request("https://example.test/api/my-orders?slug=shop&offset=20"));expect(response.status).toBe(200);expect(mocks.rpc).toHaveBeenCalledWith("claim_buyer_orders",expect.objectContaining({p_receipts:[id]}));expect(mocks.rpc).toHaveBeenCalledWith("buyer_history",expect.objectContaining({p_tenant:tenant,p_offset:20,p_user:"verified-user"}));});
it("fails closed when account verification fails",async()=>{mocks.identity.mockRejectedValue(new Error("Auth unavailable"));const response=await GET(new Request("https://example.test/api/my-orders?slug=shop"));expect(response.status).toBe(503);expect(mocks.rpc).not.toHaveBeenCalled();});
